dialogId("m-tatinek", "font_small", "")
dialogStr("Tatínek měl pravdu, linuxáci musí být šílení.")
dialogId("v-kdojiny", "font_big", "")
dialogStr("Kdo jiný by vytvořil takové množství překážek?")
dialogId("m-zadarmo", "font_small", "")
dialogStr("A ještě k tomu zadarmo.")

dialogId("m-zamykali", "font_small", "")
dialogStr("Teď už mi to je jasné, oni se před námi zamykali.")
dialogId("v-horydoly", "font_big", "")
dialogStr("Stavěli hory, doly...")
dialogId("m-linuxaci", "font_small", "")
dialogStr("Linuxáci!")
dialogId("v-ven", "font_big", "")
dialogStr("Teď už je jen dostat ven.")


dialogId("v-musime", "font_big", "")
dialogStr("Musíme je odtut dostat.")
dialogId("m-radi", "font_small", "")
dialogStr("Myslím, že budeme rádi, když dostaneme ven jednoho.")
dialogId("v-radeji", "font_big", "")
dialogStr("Ale když odstraníme oba, budeme ještě raději.")

dialogId("m-nemyslis", "font_small", "")
dialogStr("Nemyslíš, že stačí dostat ven jednoho?")
dialogId("v-forkovat", "font_big", "")
dialogStr("Ne, ten, co by tu zůstal, by se mohl vyforkovat.")


dialogId("m-ukolem", "font_small", "")
dialogStr("Naším úkolem je usmířit ty linuxáky.")
dialogId("v-alespon", "font_big", "")
dialogStr("Nebo je alespoň dostat ven.")


dialogId("m-vykaslat", "font_small", "")
dialogStr("Co takhle se na ty linuxáky prostě vykašlat, vždyť nebyli ani v popisu práce.")
dialogId("v-nabourali", "font_big", "")
dialogStr("Jenže oni se do té hry nabourali, a doukud je nedostanem ven, nemůžeme vyhrát.")


dialogId("v-snazit", "font_big", "")
dialogStr("Teda hráči, ty jsi se musel asi hodně snažit, abys dostal ven jen jednoho linuxáka, podařilo se ti překonat tu ocelovou konstrukci.")
dialogId("m-nestaci", "font_small", "")
dialogStr("Ale k vítězství to nestačí.")


dialogId("v-vyrobil", "font_big", "")
dialogStr("Chtěl bych hráče upozornit, aby tuto místnost nebral příliš vážně, vždyť ji vyrobil sám linuxák.")
dialogId("m-sileny", "font_small", "")
dialogStr("Asi byl šílený.")

dialogId("v-osobne", "font_big", "")
dialogStr("Pokud jsi hráči linuxák, tak si to šílenství neber osobně.")
dialogId("m-ostatni", "font_small", "")
dialogStr("My nemyslíme tebe, my myslíme ty ostatní.")



dialogId("m-samem", "font_small", "")
dialogStr("Je zajímavé, že se dokáží přít stále o tom samém.")
dialogId("v-argumenty", "font_big", "")
dialogStr("A používat stále stejné argumenty.")

dialogId("v-dole", "font_big", "")
dialogStr("Co to tam dole máš?")
dialogId("2-bubliny", "font_linuxer2", "")
dialogStr("To jsou mražené bubliny.")
dialogId("1-odpadnou", "font_linuxer1", "")
dialogStr("Když k sobě dostanete tři stejné barvy, tak odpadnou.")

dialogId("m-vtipni", "font_small", "")
dialogStr("Kdyby ti linuxáci byli aspoň vtipní.")
dialogId("1-rozdil", "font_linuxer1", "")
dialogStr("Já znám jeden super vtip, víš jaký je rozdíl mezi chattr a chmod?")
dialogId("text14", "font_white", "man chattr > 1; man chmod > 2; diff 1 2")
dialogStr("man chattr > 1; man chmod > 2; diff 1 2")
dialogId("2-trapnejsi", "font_linuxer2", "")
dialogStr("To je ještě trapnější než poslední komix na rootu.")
dialogId("1-trilobyte", "font_linuxer1", "")
dialogStr("A víš, kolik je 8 trilobitů? Jeden trilobyte.")
dialogId("text15", "font_white", "Ha ha ha")
dialogStr("Ha ha ha")



dialogId("2-nezaujata", "font_linuxer2", "")
dialogStr("Podívej, jak se snaží být tato místnost nezaujatá, na pozadí je tučňák, ale kdyby tam bylo logo Debianu, Fedory, ....")
dialogId("1-prvni", "font_linuxer1", "")
dialogStr("Proč jsi řekl jako první Debian?")
dialogId("2-abecedy", "font_linuxer2", "")
dialogStr("Vyjmenovávám podle abecedy.")

dialogId("1-archlinux", "font_linuxer1", "")
dialogStr("To bys měl ale začít Arch linuxem.")
dialogId("2-zapomel", "font_linuxer2", "")
dialogStr("Pravda, na ten jsem zapomněl, takže Arch linuxu, Debianu, ...")
dialogId("1-podruhe", "font_linuxer1", "")
dialogStr("Proč jsi řekl Debian podruhé?")

dialogId("2-naprogramovana", "font_linuxer2", "")
dialogStr("Tahle hra byla na Debianu naprogramována.")
dialogId("1-ubuntu", "font_linuxer1", "")
dialogStr("Proč ne na Ubuntu?")
dialogId("2-vykradacka", "font_linuxer2", "")
dialogStr("Ubuntu je vykrádačka Debianu, a navíc pěkně nepovedená.")

dialogId("1-zkousel", "font_linuxer1", "")
dialogStr("Zkoušel jsi vůbec někdy Ubuntu?")
dialogId("2-root", "font_linuxer2", "")
dialogStr("Ne, ale stačí mi, co jsem o něm slyšel. Umíš se tam přihlásit jako root?")
dialogId("1-nepotrebuje", "font_linuxer1", "")
dialogStr("Ubuntu takové starobylosti jako je root vůbec nepotřebuje.")
dialogId("2-postavene", "font_linuxer2", "")
dialogStr("Ale je na nich postavené.")
dialogId("1-rozhrani", "font_linuxer1", "")
dialogStr("Každá distribuce má určité rozhraní mezi unixem a uživatelem.")

dialogId("2-slackware", "font_linuxer2", "")
dialogStr("Co takhle Slackware?")
dialogId("1-balickovaci", "font_linuxer1", "")
dialogStr("No jo, ale ten má mizerný balíčkovací systém.")
dialogId("2-svuj", "font_linuxer2", "")
dialogStr("Ale aspoň svůj.")


dialogId("2-hadi", "font_linuxer2", "")
dialogStr("Jestli pak víš, proč jsou tu ti hadi?")
dialogId("1-jazyka", "font_linuxer1", "")
dialogStr("Ovšem, je to logo nejlepšího programovacího jazyka.")
dialogId("2-C", "font_linuxer2", "")
dialogStr("Odkdy má C-čko v logu hady?")
dialogId("1-prekonane", "font_linuxer1", "")
dialogStr("C-čko uč je dávno překonané, už třeba C-pluspluskem a pak Javou.")
dialogId("2-pomala", "font_linuxer2", "")
dialogStr("Java je interpretovaný jazyk, a tak je strašně pomalá, stejně jako ten tvůj Python.")
dialogId("1-pohodli", "font_linuxer1", "")
dialogStr("Mně nejde o rychlost, ale o pohodlí programátora.")
dialogId("2-prave", "font_linuxer2", "")
dialogStr("No právě")


dialogId("1-wilber", "font_linuxer1", "")
dialogStr("Podívej, Wilber.")
dialogId("2-maskot", "font_linuxer2", "")
dialogStr("Maskot jednoho skvělého grafického programu.")
dialogId("1-dohnat", "font_linuxer1", "")
dialogStr("Který se marně snaži dohnat Photoshop.")
dialogId("2-neni", "font_linuxer2", "")
dialogStr("GIMP není Photoshop, funguje na jiných základech.")
dialogId("1-zamaskovali", "font_linuxer1", "")
dialogStr("To jenom tvrdí jeho vývojáři, aby zamaskovali svou neschopnost.")


dialogId("1-nebavi", "font_linuxer1", "")
dialogStr("Už mě ta hudba nebaví.")
dialogId("2-skriptik", "font_linuxer2", "")
dialogStr("To sis na to nemoh napsat skriptík?")
dialogId("v-prepinani", "font_big", "")
dialogStr("A mne zase nebaví to neustálé přepínání hudby.")

dialogId("text0", "font_white",  "mplayer kufrik.ogg")
dialogStr("mplayer kufrik.ogg")
dialogId("text1", "font_white",  "mplayer menu.ogg")
dialogStr("mplayer menu.ogg")
dialogId("text2", "font_white",  "mplayer rybky01.ogg")
dialogStr("mplayer rybky01.ogg")
dialogId("text3", "font_white",  "mplayer rybky02.ogg")
dialogStr("mplayer rybky02.ogg")
dialogId("text4", "font_white",  "mplayer rybky03.ogg")
dialogStr("mplayer rybky03.ogg")
dialogId("text5", "font_white",  "mplayer rybky04.ogg")
dialogStr("mplayer rybky04.ogg")
dialogId("text6", "font_white",  "mplayer rybky05.ogg")
dialogStr("mplayer rybky05.ogg")
dialogId("text7", "font_white",  "mplayer rybky06.ogg")
dialogStr("mplayer rybky06.ogg")
dialogId("text8", "font_white",  "mplayer rybky07.ogg")
dialogStr("mplayer rybky07.ogg")
dialogId("text9", "font_white",  "mplayer rybky09.ogg")
dialogStr("mplayer rybky09.ogg")
dialogId("text10", "font_white", "mplayer rybky10.ogg")
dialogStr("mplayer rybky10.ogg")
dialogId("text11", "font_white", "mplayer rybky13.ogg")
dialogStr("mplayer rybky13.ogg")
dialogId("text12", "font_white", "mplayer rybky14.ogg")
dialogStr("mplayer rybky14.ogg")
dialogId("text13", "font_white", "mplayer rybky15.ogg")
dialogStr("mplayer rybky15.ogg")
