dialog_addDialog("uts-m-otresy", "en", "", "font_small", "My goodness, the impact created cave-in!")
dialog_addDialog("uts-m-otresy", "cs", "sound/"..codename.."/cs/uts-m-otresy.ogg", "font_small", "Probůh, to otřesy způsobily zával!")
dialog_addDialog("uts-m-otresy", "fr", "", "font_small", "Mon dieu, l'impact a causé cet affaissement.")
dialog_addDialog("uts-m-otresy", "de", "", "font_small", "Meine Güte, durch den Aufschlag ist die Höhle eingestürzt!")
dialog_addDialog("uts-m-otresy", "it", "", "font_small", "Mio dio, l'impatto ha causato una frana!")

dialog_addDialog("uts-v-projet0", "en", "", "font_big", "I can`t go through this cave-in, we have to find another exit.")
dialog_addDialog("uts-v-projet0", "cs", "sound/"..codename.."/cs/uts-v-projet0.ogg", "font_big", "Nemůžu kolem toho závalu projet, musíme zkusit jiný východ.")
dialog_addDialog("uts-v-projet0", "fr", "", "font_big", "Je ne peux pas passer dessous, nous devrons trouver un autre chemin pour sortir.")
dialog_addDialog("uts-v-projet0", "de", "", "font_big", "Ich komme da nicht durch, wir müssen einen anderen Ausgang finden.")
dialog_addDialog("uts-v-projet0", "it", "", "font_big", "Non posso andare oltre questo smottamento, dobbiamo trovare un'altra uscita.")

dialog_addDialog("uts-v-projet1", "en", "", "font_big", "This is not the way.")
dialog_addDialog("uts-v-projet1", "cs", "sound/"..codename.."/cs/uts-v-projet1.ogg", "font_big", "Tudy to asi nepůjde.")
dialog_addDialog("uts-v-projet1", "fr", "", "font_big", "Ce n'est pas le but.")
dialog_addDialog("uts-v-projet1", "de", "", "font_big", "Das geht nicht.")
dialog_addDialog("uts-v-projet1", "it", "", "font_big", "Non è questa la strada.")

dialog_addDialog("uts-v-sam", "en", "", "font_big", "I won`t make it alone.")
dialog_addDialog("uts-v-sam", "cs", "sound/"..codename.."/cs/uts-v-sam.ogg", "font_big", "Sám to tady asi nezvládnu.")
dialog_addDialog("uts-v-sam", "fr", "", "font_big", "Je n'y arriverai pas tout seul.")
dialog_addDialog("uts-v-sam", "de", "", "font_big", "Ich schaffe das nicht alleine.")
dialog_addDialog("uts-v-sam", "it", "", "font_big", "Non andrò avanti da solo.")

dialog_addDialog("uts-m-lastura", "en", "", "font_small", "I probably should have had lifted that shell first.")
dialog_addDialog("uts-m-lastura", "cs", "sound/"..codename.."/cs/uts-m-lastura.ogg", "font_small", "Asi jsem měla tu lasturu nejdřív zvednout.")
dialog_addDialog("uts-m-lastura", "fr", "", "font_small", "Je dois probablement soulever ce coquillage d'abord.")
dialog_addDialog("uts-m-lastura", "de", "", "font_small", "Ich hätte wahrscheinlich diese Muschel zuerst anheben sollen.")
dialog_addDialog("uts-m-lastura", "it", "", "font_small", "Forse, prima, dovevo alzare quella conchiglia.")

dialog_addDialog("uts-v-poradi", "en", "", "font_big", "Maybe we would have to switch these objects.")
dialog_addDialog("uts-v-poradi", "cs", "sound/"..codename.."/cs/uts-v-poradi.ogg", "font_big", "Možná bude potřeba vyměnit pořadí těch předmětů.")
dialog_addDialog("uts-v-poradi", "fr", "", "font_big", "Peut-être devrions-nous échanger la place de ces objets.")
dialog_addDialog("uts-v-poradi", "de", "", "font_big", "Vielleicht müssen wir diese Gegenstände vertauschen.")
dialog_addDialog("uts-v-poradi", "it", "", "font_big", "Mi sa che dovremmo scambiare questi oggetti.")

dialog_addDialog("uts-m-matrace", "en", "", "font_small", "Mattress. The best thing you can get under water.")
dialog_addDialog("uts-m-matrace", "cs", "sound/"..codename.."/cs/uts-m-matrace.ogg", "font_small", "Matrace. To nejlepší, co pod vodou seženete.")
dialog_addDialog("uts-m-matrace", "fr", "", "font_small", "Un matelas. La meilleure chose que l'on peut trouver sous l'eau.")
dialog_addDialog("uts-m-matrace", "de", "", "font_small", "Eine Matratze. Das beste Ding, das man unter Wasser haben kann.")
dialog_addDialog("uts-m-matrace", "it", "", "font_small", "Un materasso. La miglior cosa che puoi avere sott'acqua.")

dialog_addDialog("uts-m-snek", "en", "", "font_small", "Now we can drop the snail on the mattress.")
dialog_addDialog("uts-m-snek", "cs", "sound/"..codename.."/cs/uts-m-snek.ogg", "font_small", "Teď můžeme shodit šneka na tu matraci.")
dialog_addDialog("uts-m-snek", "fr", "", "font_small", "Maintenant nous pouvons faire tomber les escargots sur le matelas.")
dialog_addDialog("uts-m-snek", "de", "", "font_small", "Jetzt können wir die Schnecke auf die Matratze fallen lassen.")
dialog_addDialog("uts-m-snek", "it", "", "font_small", "Ora possiamo adagiare la lumachina sul materasso.")

dialog_addDialog("uts-m-nezvedneme", "en", "", "font_small", "It will be difficult to pick up that snail from there.")
dialog_addDialog("uts-m-nezvedneme", "cs", "sound/"..codename.."/cs/uts-m-nezvedneme.ogg", "font_small", "Odtam toho šneka už asi nezvedneme.")
dialog_addDialog("uts-m-nezvedneme", "fr", "", "font_small", "Ca va être difficile de récupérer cet escargot.")
dialog_addDialog("uts-m-nezvedneme", "de", "", "font_small", "Es wird schwierig, die Schnecke von dort aufzuheben.")
dialog_addDialog("uts-m-nezvedneme", "it", "", "font_small", "Sarà difficile togliere quella lumaca da lì.")

dialog_addDialog("uts-v-konecne", "en", "", "font_big", "Finally, it`s there.")
dialog_addDialog("uts-v-konecne", "cs", "sound/"..codename.."/cs/uts-v-konecne.ogg", "font_big", "Konečně je tam.")
dialog_addDialog("uts-v-konecne", "fr", "", "font_big", "Finalement ça y est.")
dialog_addDialog("uts-v-konecne", "de", "", "font_big", "Endlich ist sie da.")
dialog_addDialog("uts-v-konecne", "it", "", "font_big", "Finalmente, ci siamo.")

dialog_addDialog("uts-m-chudak", "en", "", "font_small", "The poor snail...")
dialog_addDialog("uts-m-chudak", "cs", "sound/"..codename.."/cs/uts-m-chudak.ogg", "font_small", "Chudáček šneček...")
dialog_addDialog("uts-m-chudak", "fr", "", "font_small", "Pauvre escargot...")
dialog_addDialog("uts-m-chudak", "de", "", "font_small", "Die arme Schnecke...")
dialog_addDialog("uts-m-chudak", "it", "", "font_small", "Povera lumaca...")

dialog_addDialog("uts-v-koraly", "en", "", "font_big", "We should search the coral reefs.")
dialog_addDialog("uts-v-koraly", "cs", "sound/"..codename.."/cs/uts-v-koraly.ogg", "font_big", "Měli bychom se podívat do korálových útesů.")
dialog_addDialog("uts-v-koraly", "fr", "", "font_big", "Nous devons fouiller le récif de corail.")
dialog_addDialog("uts-v-koraly", "de", "", "font_big", "Wir sollten die Korallenriffe absuchen.")
dialog_addDialog("uts-v-koraly", "it", "", "font_big", "Dovremmo cercare nelle barriere coralline.")

dialog_addDialog("uts-m-tvorove", "en", "", "font_small", "There are going to be many interesting beings to investigate there.")
dialog_addDialog("uts-m-tvorove", "cs", "sound/"..codename.."/cs/uts-m-tvorove.ogg", "font_small", "Tam bude jistě spousta živých tvorů ke zkoumání.")
dialog_addDialog("uts-m-tvorove", "fr", "", "font_small", "Il va y avoir beaucoup de chose intéressante à étudier là bas.")
dialog_addDialog("uts-m-tvorove", "de", "", "font_small", "Dort werden viele interessante Wesen zu untersuchen sein.")
dialog_addDialog("uts-m-tvorove", "it", "", "font_small", "Ci saranno un sacco di cose interessanti da investigare, lì.")

dialog_addDialog("uts-v-mikroskop", "en", "", "font_big", "Don`t we need a microscope to investigate corals?")
dialog_addDialog("uts-v-mikroskop", "cs", "sound/"..codename.."/cs/uts-v-mikroskop.ogg", "font_big", "Nejsou korály náhodou zkoumatelné jen pod mikroskopem?")
dialog_addDialog("uts-v-mikroskop", "fr", "", "font_big", "Aurons-nous besoin d'un microscope pour étudier le corail ?")
dialog_addDialog("uts-v-mikroskop", "de", "", "font_big", "Brauchen wir nicht ein Mikroskop, um Korallen zu untersuchen?")
dialog_addDialog("uts-v-mikroskop", "it", "", "font_big", "Non ci serve un microscopio per investigare sui coralli?")

dialog_addDialog("uts-m-zivocich", "en", "", "font_small", "Yes, they are small. But there can be other life forms.")
dialog_addDialog("uts-m-zivocich", "cs", "sound/"..codename.."/cs/uts-m-zivocich.ogg", "font_small", "No, jsou malé. Ale mohou tam být i jiní živočichové.")
dialog_addDialog("uts-m-zivocich", "fr", "", "font_small", "Oui ils sont minuscules. Mais il peut y avoir d'autres formes de vie.")
dialog_addDialog("uts-m-zivocich", "de", "", "font_small", "Ja, die sind klein. Aber dort können auch andere Lebensformen sein.")
dialog_addDialog("uts-m-zivocich", "it", "", "font_small", "Sì, quelli sono piccoli. Ma possono esserci anche altre forme di vita.")

dialog_addDialog("uts-m-zelvy", "en", "", "font_small", "Coral turtles, for example.")
dialog_addDialog("uts-m-zelvy", "cs", "sound/"..codename.."/cs/uts-m-zelvy.ogg", "font_small", "Třeba korálové želvy.")
dialog_addDialog("uts-m-zelvy", "fr", "", "font_small", "Les tortues corail, par exemple.")
dialog_addDialog("uts-m-zelvy", "de", "", "font_small", "Zum Beispiel Korallenschildkröten.")
dialog_addDialog("uts-m-zelvy", "it", "", "font_small", "Tartarughe dei coralli, per esempio.")

dialog_addDialog("uts-m-batyskaf", "en", "", "font_small", "And moreover I have a suspicion that microscope is in one bathyscaph.")
dialog_addDialog("uts-m-batyskaf", "cs", "sound/"..codename.."/cs/uts-m-batyskaf.ogg", "font_small", "A navíc mi něco říká, že mikroskop je v jednom batyskafu.")
dialog_addDialog("uts-m-batyskaf", "fr", "", "font_small", "De plus je crois que le microscope se trouve dans un bathyscaphe.")
dialog_addDialog("uts-m-batyskaf", "de", "", "font_small", "Und außerdem habe ich den Verdacht, dass dieses Mikroskop in einem Tauchboot ist.")
dialog_addDialog("uts-m-batyskaf", "de_CH", "", "font_small", "Und ausserdem habe ich den Verdacht, dass dieses Mikroskop in einem Tauchboot ist.")
dialog_addDialog("uts-m-batyskaf", "it", "", "font_small", "E inoltre ho il sospetto che il microscopio si trovi in un batiscafo.")