
dialog_addDialog("cil-v-hlaska0", "en", "", "font_big", "I think we have a job to do here.")
dialog_addDialog("cil-v-hlaska0", "cs", "sound/share/border/cs/cil-v-hlaska0.ogg", "font_big", "Myslím, že tu ještě máme práci.")
dialog_addDialog("cil-v-hlaska0", "fr", "", "font_big", "Je crois qu'il nous reste du travail ici.")
dialog_addDialog("cil-v-hlaska0", "de", "", "font_big", "Ich denke, wir müssen hier einen Auftrag erledigen.")
dialog_addDialog("cil-v-hlaska0", "it", "", "font_big", "Abbiamo un lavoro da svolgere qui.")

dialog_addDialog("cil-m-hlaska0", "en", "", "font_small", "I think we have a job to do here.")
dialog_addDialog("cil-m-hlaska0", "cs", "sound/share/border/cs/cil-m-hlaska0.ogg", "font_small", "Myslím, že tu ještě máme práci.")
dialog_addDialog("cil-m-hlaska0", "fr", "", "font_small", "Je crois qu'il nous reste du travail ici.")
dialog_addDialog("cil-m-hlaska0", "de", "", "font_small", "Ich denke, wir müssen hier einen Auftrag erledigen.")
dialog_addDialog("cil-m-hlaska0", "it", "", "font_small", "Abbiamo un lavoro da svolgere qui.")

dialog_addDialog("cil-v-hlaska1", "en", "", "font_big", "We didn`t fulfill our mission yet.")
dialog_addDialog("cil-v-hlaska1", "cs", "sound/share/border/cs/cil-v-hlaska1.ogg", "font_big", "Ještě jsme nesplnili svoje poslání.")
dialog_addDialog("cil-v-hlaska1", "fr", "", "font_big", "Nous n'avons pas encore rempli notre mission.")
dialog_addDialog("cil-v-hlaska1", "de", "", "font_big", "Wir haben unseren Auftrag noch nicht erfüllt.")
dialog_addDialog("cil-v-hlaska1", "it", "", "font_big", "Non abbiamo ancora completato la nostra missione.")

dialog_addDialog("cil-m-hlaska1", "en", "", "font_small", "We didn`t fulfill our mission yet.")
dialog_addDialog("cil-m-hlaska1", "cs", "sound/share/border/cs/cil-m-hlaska1.ogg", "font_small", "Ještě jsme nesplnili svoje poslání.")
dialog_addDialog("cil-m-hlaska1", "fr", "", "font_small", "Nous n'avons pas encore rempli notre mission.")
dialog_addDialog("cil-m-hlaska1", "de", "", "font_small", "Wir haben unseren Auftrag noch nicht erfüllt.")
dialog_addDialog("cil-m-hlaska1", "it", "", "font_small", "Non abbiamo ancora completato la nostra missione.")

dialog_addDialog("cil-m-hlaska2", "en", "", "font_small", "The Agency relies upon us. We must not fail.")
dialog_addDialog("cil-m-hlaska2", "cs", "sound/share/border/cs/cil-m-hlaska2.ogg", "font_small", "Agentura se na nás spoléhá, nemůžeme ji zklamat.")
dialog_addDialog("cil-m-hlaska2", "fr", "", "font_small", "L'Agence compte sur nous. Nous ne devons pas échouer.")
dialog_addDialog("cil-m-hlaska2", "de", "", "font_small", "Die Agentur verlässt sich auf uns. Wir dürfen nicht versagen.")
dialog_addDialog("cil-m-hlaska2", "it", "", "font_small", "L'Agenzia fa affidamento su di noi. Non dobbiamo fallire.")

dialog_addDialog("cil-v-hlaska2", "en", "", "font_big", "The Agency relies upon us. We must not fail.")
dialog_addDialog("cil-v-hlaska2", "cs", "sound/share/border/cs/cil-v-hlaska2.ogg", "font_big", "Agentura se na nás spoléhá, nemůžeme ji zklamat.")
dialog_addDialog("cil-v-hlaska2", "fr", "", "font_big", "L'Agence compte sur nous. Nous ne devons pas échouer.")
dialog_addDialog("cil-v-hlaska2", "de", "", "font_big", "Die Agentur verlässt sich auf uns. Wir dürfen nicht versagen.")
dialog_addDialog("cil-v-hlaska2", "it", "", "font_big", "L'Agenzia fa affidamento su di noi. Non dobbiamo fallire.")

dialog_addDialog("cil-v-hlaska3", "en", "", "font_big", "Certainly, we are not going to run away with the end in sight.")
dialog_addDialog("cil-v-hlaska3", "cs", "sound/share/border/cs/cil-v-hlaska3.ogg", "font_big", "Přece neutečem těsně před koncem.")
dialog_addDialog("cil-v-hlaska3", "fr", "", "font_big", "Evidemment, nous n'allons pas abandonner si près de la fin.")
dialog_addDialog("cil-v-hlaska3", "de", "", "font_big", "So kurz vorm Ziel werden wir sicher nicht aufgeben.")
dialog_addDialog("cil-v-hlaska3", "it", "", "font_big", "Di sicuro non ce ne andremo così prossimi alla soluzione.")

dialog_addDialog("cil-m-hlaska3", "en", "", "font_small", "Certainly, we are not going to run away with the end in sight.")
dialog_addDialog("cil-m-hlaska3", "cs", "sound/share/border/cs/cil-m-hlaska3.ogg", "font_small", "Přece neutečem těsně před koncem.")
dialog_addDialog("cil-m-hlaska3", "fr", "", "font_small", "Evidemment, nous n'allons pas abandonner si près de la fin.")
dialog_addDialog("cil-m-hlaska3", "de", "", "font_small", "So kurz vorm Ziel werden wir sicher nicht aufgeben.")
dialog_addDialog("cil-m-hlaska3", "it", "", "font_small", "Di sicuro non ce ne andremo, così vicini alla soluzione.")
