dialog_addDialog("ob-m-neverim", "en", "", "font_small", "I don`t believe we can make it...")
dialog_addDialog("ob-m-neverim", "cs", "sound/share/borejokes/cs/ob-m-neverim.ogg", "font_small", "Nevěřím, že to půjde...")
dialog_addDialog("ob-m-neverim", "fr", "", "font_small", "Je ne crois pas que nous y arriverons...")
dialog_addDialog("ob-m-neverim", "de", "", "font_small", "Ich glaube nicht, dass wir es schaffen...")
dialog_addDialog("ob-m-neverim", "it", "", "font_small", "Penso che non ce la faremo mai...")

dialog_addDialog("ob-m-nedosataneme", "en", "", "font_small", "We aren`t going to get out of here.")
dialog_addDialog("ob-m-nedosataneme", "cs", "sound/share/borejokes/cs/ob-m-nedosataneme.ogg", "font_small", "Už se odsud nikdy nedostaneme.")
dialog_addDialog("ob-m-nedosataneme", "fr", "", "font_small", "Nous ne sortirons pas d'ici.")
dialog_addDialog("ob-m-nedosataneme", "de", "", "font_small", "Hier kommen wir nicht raus.")
dialog_addDialog("ob-m-nedosataneme", "it", "", "font_small", "Non ne usciremo vivi.")

dialog_addDialog("ob-m-naveky", "en", "", "font_small", "We are shut here forever.")
dialog_addDialog("ob-m-naveky", "cs", "sound/share/borejokes/cs/ob-m-naveky.ogg", "font_small", "Jsme tu na věky zavření.")
dialog_addDialog("ob-m-naveky", "fr", "", "font_small", "Nous sommes enfermés ici pour l'éternité.")
dialog_addDialog("ob-m-naveky", "de", "", "font_small", "Wir sind hier für immer eingeschlossen.")
dialog_addDialog("ob-m-naveky", "it", "", "font_small", "Resterremo chiusi qui per sempre.")

dialog_addDialog("ob-v-jit0", "en", "", "font_big", "There must be a way out.")
dialog_addDialog("ob-v-jit0", "cs", "sound/share/borejokes/cs/ob-v-jit0.ogg", "font_big", "Musí to nějak jít.")
dialog_addDialog("ob-v-jit0", "fr", "", "font_big", "Il doit y avoir un moyen de sortir.")
dialog_addDialog("ob-v-jit0", "de", "", "font_big", "Es muss einen Weg raus geben.")
dialog_addDialog("ob-v-jit0", "it", "", "font_big", "Ci dev'essere una via d'uscita.")

dialog_addDialog("ob-v-jit1", "en", "", "font_big", "There is some solution, only we cannot see it.")
dialog_addDialog("ob-v-jit1", "cs", "sound/share/borejokes/cs/ob-v-jit1.ogg", "font_big", "Řešení tu je, jen ho nevidíme.")
dialog_addDialog("ob-v-jit1", "fr", "", "font_big", "Il y a une solution, nous ne pouvons simplement pas la voir.")
dialog_addDialog("ob-v-jit1", "de", "", "font_big", "Es gibt eine Lösung, wir können sie nur nicht sehen.")
dialog_addDialog("ob-v-jit1", "it", "", "font_big", "C'è di sicuro una soluzione, solo noi non riusciamo a vederla.")

dialog_addDialog("ob-v-musi", "en", "", "font_big", "Lift up your head, there must be a way.")
dialog_addDialog("ob-v-musi", "cs", "sound/share/borejokes/cs/ob-v-musi.ogg", "font_big", "Hlavu vzhůru, nějak to jít musí.")
dialog_addDialog("ob-v-musi", "fr", "", "font_big", "Ressaisis-toi, il doit y avoir une solution.")
dialog_addDialog("ob-v-musi", "de", "", "font_big", "Kopf hoch! Es muss einen Weg geben.")
dialog_addDialog("ob-v-musi", "it", "", "font_big", "Tira su la testa, ci deve essere un modo.")

dialog_addDialog("ob-v-klid", "en", "", "font_big", "Take it easy.")
dialog_addDialog("ob-v-klid", "cs", "sound/share/borejokes/cs/ob-v-klid.ogg", "font_big", "Jen klid.")
dialog_addDialog("ob-v-klid", "fr", "", "font_big", "Détends toi.")
dialog_addDialog("ob-v-klid", "de", "", "font_big", "Nur keine Hektik.")
dialog_addDialog("ob-v-klid", "it", "", "font_big", "Calma e gesso.")

dialog_addDialog("ob-v-neobvykle", "en", "", "font_big", "There is something strange about it...")
dialog_addDialog("ob-v-neobvykle", "cs", "sound/share/borejokes/cs/ob-v-neobvykle.ogg", "font_big", "V tom bude něco neobvyklého...")
dialog_addDialog("ob-v-neobvykle", "fr", "", "font_big", "Il y a quelque chose d'étrange...")
dialog_addDialog("ob-v-neobvykle", "de", "", "font_big", "Irgendwas ist komisch...")
dialog_addDialog("ob-v-neobvykle", "it", "", "font_big", "C'è qualcosa che non quadra...")

dialog_addDialog("ob-m-teorie", "en", "", "font_small", "Just spare me your theories, please.")
dialog_addDialog("ob-m-teorie", "cs", "sound/share/borejokes/cs/ob-m-teorie.ogg", "font_small", "Nepokoušej se zase rozvíjet ty svoje teorie.")
dialog_addDialog("ob-m-teorie", "fr", "", "font_small", "Epargne moi tes théories, s'il te plaît.")
dialog_addDialog("ob-m-teorie", "de", "", "font_small", "Erspare mir bitte deine Theorien.")
dialog_addDialog("ob-m-teorie", "it", "", "font_small", "Risparmiami le tue teorie, per favore.")

dialog_addDialog("ob-v-mamto", "en", "", "font_big", "I`ve got it. If we push that one...")
dialog_addDialog("ob-v-mamto", "cs", "sound/share/borejokes/cs/ob-v-mamto.ogg", "font_big", "Mám to! Když posuneme támhle tu ...")
dialog_addDialog("ob-v-mamto", "fr", "", "font_big", "Euréka. Si nous poussons celui là...")
dialog_addDialog("ob-v-mamto", "de", "", "font_big", "Ich hab es. Wenn wir den dort schieben...")
dialog_addDialog("ob-v-mamto", "it", "", "font_big", "Ci sono! Se spostiamo quel...")

dialog_addDialog("ob-m-pokracuj", "en", "", "font_small", "Go on!")
dialog_addDialog("ob-m-pokracuj", "cs", "sound/share/borejokes/cs/ob-m-pokracuj.ogg", "font_small", "Pokračuj!")
dialog_addDialog("ob-m-pokracuj", "fr", "", "font_small", "Allons y!")
dialog_addDialog("ob-m-pokracuj", "de", "", "font_small", "Weiter!")
dialog_addDialog("ob-m-pokracuj", "it", "", "font_small", "Va avanti!")

dialog_addDialog("ob-v-napad", "en", "", "font_big", "Oh no, it was just an idea...")
dialog_addDialog("ob-v-napad", "cs", "sound/share/borejokes/cs/ob-v-napad.ogg", "font_big", "Ale ne, byl to jen takový nápad...")
dialog_addDialog("ob-v-napad", "fr", "", "font_big", "Non, c'était juste une idée...")
dialog_addDialog("ob-v-napad", "de", "", "font_big", "Ach nö, war nur eine Idee...")
dialog_addDialog("ob-v-napad", "it", "", "font_big", "Oh no, era solo un'idea...")

dialog_addDialog("ob-v-vyzkousej", "en", "", "font_big", "What if we try that...")
dialog_addDialog("ob-v-vyzkousej", "cs", "sound/share/borejokes/cs/ob-v-vyzkousej.ogg", "font_big", "Co kdybychom vyzkoušeli támhle...")
dialog_addDialog("ob-v-vyzkousej", "fr", "", "font_big", "Et si on essayait ça...")
dialog_addDialog("ob-v-vyzkousej", "de", "", "font_big", "Und wenn wir versuchen, dieses...")
dialog_addDialog("ob-v-vyzkousej", "it", "", "font_big", "E se provassimo...")

dialog_addDialog("ob-m-co", "en", "", "font_small", "What?")
dialog_addDialog("ob-m-co", "cs", "sound/share/borejokes/cs/ob-m-co.ogg", "font_small", "Co?")
dialog_addDialog("ob-m-co", "fr", "", "font_small", "Quoi ?")
dialog_addDialog("ob-m-co", "de", "", "font_small", "Was?")
dialog_addDialog("ob-m-co", "it", "", "font_small", "Cosa?")

dialog_addDialog("ob-v-alenic", "en", "", "font_big", "Nothing. Just an idea.")
dialog_addDialog("ob-v-alenic", "cs", "sound/share/borejokes/cs/ob-v-alenic.ogg", "font_big", "Ale nic, to byl jen takový nápad.")
dialog_addDialog("ob-v-alenic", "fr", "", "font_big", "Rien. Juste une idée.")
dialog_addDialog("ob-v-alenic", "de", "", "font_big", "Nichts. Nur eine Idee.")
dialog_addDialog("ob-v-alenic", "it", "", "font_big", "Niente. Solo un'idea.")

dialog_addDialog("ob-m-zase", "en", "", "font_small", "Not again.")
dialog_addDialog("ob-m-zase", "cs", "sound/share/borejokes/cs/ob-m-zase.ogg", "font_small", "Už zase...")
dialog_addDialog("ob-m-zase", "fr", "", "font_small", "Arrête.")
dialog_addDialog("ob-m-zase", "de", "", "font_small", "Nicht schon wieder.")
dialog_addDialog("ob-m-zase", "it", "", "font_small", "Non di nuovo.")

dialog_addDialog("ob-v-nebavi", "en", "", "font_big", "I`m tired of it.")
dialog_addDialog("ob-v-nebavi", "cs", "sound/share/borejokes/cs/ob-v-nebavi.ogg", "font_big", "Už mě to nebaví.")
dialog_addDialog("ob-v-nebavi", "fr", "", "font_big", "Il me fatigue.")
dialog_addDialog("ob-v-nebavi", "de", "", "font_big", "Ich habe es satt.")
dialog_addDialog("ob-v-nebavi", "it", "", "font_big", "Sono stanco.")

dialog_addDialog("ob-v-hrej", "en", "", "font_big", "Just play, we want to get out.")
dialog_addDialog("ob-v-hrej", "cs", "sound/share/borejokes/cs/ob-v-hrej.ogg", "font_big", "No tak, hrej, chceme se dostat ven.")
dialog_addDialog("ob-v-hrej", "fr", "", "font_big", "Allez joue, nous voulons sortir.")
dialog_addDialog("ob-v-hrej", "de", "", "font_big", "Spiel einfach, wir wollen raus.")
dialog_addDialog("ob-v-hrej", "it", "", "font_big", "Gioca e basta, dobbiamo uscirne fuori.")

dialog_addDialog("ob-v-sami", "en", "", "font_big", "If the player keeps doing nothing, we`ll solve it ourselves.")
dialog_addDialog("ob-v-sami", "cs", "sound/share/borejokes/cs/ob-v-sami.ogg", "font_big", "Jestli nezačne ten hráč něco dělat, vyřešíme si to sami.")
dialog_addDialog("ob-v-sami", "fr", "", "font_big", "Si le joueur ne fait rien, nous allons trouver la solution nous-même.")
dialog_addDialog("ob-v-sami", "de", "", "font_big", "Wenn der Spieler weiter nichts tut, werden wir es selbst lösen.")
dialog_addDialog("ob-v-sami", "it", "", "font_big", "Se il giocatore continua a non far niente, dovremo cavarcela da soli.")

dialog_addDialog("ob-m-pst", "en", "", "font_small", "Shhh, don`t disturb the player. He thinks again...")
dialog_addDialog("ob-m-pst", "cs", "sound/share/borejokes/cs/ob-m-pst.ogg", "font_small", "Pssst, neruš hráče, přemýšlí...")
dialog_addDialog("ob-m-pst", "fr", "", "font_small", "Chut, ne dérange pas le joueur. Il réfléchit encore...")
dialog_addDialog("ob-m-pst", "de", "", "font_small", "Psst, störe den Spieler nicht. Er denkt wieder...")
dialog_addDialog("ob-m-pst", "it", "", "font_small", "Ssst, non disturbare il giocatore. Sta di nuovo pensando...")

dialog_addDialog("ob-m-hlavu", "en", "", "font_small", "Keep calm.")
dialog_addDialog("ob-m-hlavu", "cs", "sound/share/borejokes/cs/ob-m-hlavu.ogg", "font_small", "Zachovej chladnou hlavu.")
dialog_addDialog("ob-m-hlavu", "fr", "", "font_small", "Reste calme.")
dialog_addDialog("ob-m-hlavu", "de", "", "font_small", "Bleib ruhig.")
dialog_addDialog("ob-m-hlavu", "it", "", "font_small", "Calma...")

dialog_addDialog("ob-m-klid", "en", "", "font_small", "Take it easy.")
dialog_addDialog("ob-m-klid", "cs", "sound/share/borejokes/cs/ob-m-klid.ogg", "font_small", "Jen klid.")
dialog_addDialog("ob-m-klid", "fr", "", "font_small", "Détends toi.")
dialog_addDialog("ob-m-klid", "de", "", "font_small", "Nur keine Hektik.")
dialog_addDialog("ob-m-klid", "it", "", "font_small", "Rilassati.")

dialog_addDialog("ob-m-jesteneco", "en", "", "font_small", "Will there be some action?")
dialog_addDialog("ob-m-jesteneco", "cs", "sound/share/borejokes/cs/ob-m-jesteneco.ogg", "font_small", "Tak bude se ještě něco dít?")
dialog_addDialog("ob-m-jesteneco", "fr", "", "font_small", "N'y aurait-il pas quelque chose à faire ?")
dialog_addDialog("ob-m-jesteneco", "de", "", "font_small", "Wird etwas passieren?")
dialog_addDialog("ob-m-jesteneco", "it", "", "font_small", "Allora? un po' di azione?")

dialog_addDialog("ob-m-nedeje", "en", "", "font_small", "Why aren`t we doing anything?")
dialog_addDialog("ob-m-nedeje", "cs", "sound/share/borejokes/cs/ob-m-nedeje.ogg", "font_small", "Proč se nic neděje?")
dialog_addDialog("ob-m-nedeje", "fr", "", "font_small", "Pourquoi ne faisons-nous rien ?")
dialog_addDialog("ob-m-nedeje", "de", "", "font_small", "Warum tun wir nichts?")
dialog_addDialog("ob-m-nedeje", "it", "", "font_small", "Perché non stiamo facendo niente?")

dialog_addDialog("ob-m-proc", "en", "", "font_small", "Why are we idle?")
dialog_addDialog("ob-m-proc", "cs", "sound/share/borejokes/cs/ob-m-proc.ogg", "font_small", "Proč se nic neděje?")
dialog_addDialog("ob-m-proc", "fr", "", "font_small", "Pourquoi attendons-nous ?")
dialog_addDialog("ob-m-proc", "de", "", "font_small", "Warum faulenzen wir?")
dialog_addDialog("ob-m-proc", "it", "", "font_small", "Perché restiamo inoperosi?")

dialog_addDialog("ob-m-ceka", "en", "", "font_small", "Does he expect us to solve ourselves?")
dialog_addDialog("ob-m-ceka", "cs", "sound/share/borejokes/cs/ob-m-ceka.ogg", "font_small", "On snad čeká, že to vyřešíme za něj?!")
dialog_addDialog("ob-m-ceka", "fr", "", "font_small", "Espère-t-il que nous trouverons nous-même la solution ?")
dialog_addDialog("ob-m-ceka", "de", "", "font_small", "Erwartet er, dass wir es selbst lösen?")
dialog_addDialog("ob-m-ceka", "it", "", "font_small", "Si aspetta forse che lo risolviamo da soli?")

dialog_addDialog("ob-v-nerus", "en", "", "font_big", "Don`t disturb. The player thinks again...")
dialog_addDialog("ob-v-nerus", "cs", "sound/share/borejokes/cs/ob-v-nerus.ogg", "font_big", "Neruš, hráč přemýšlí...")
dialog_addDialog("ob-v-nerus", "fr", "", "font_big", "Dérange pas. Le joueur réfléchit toujours...")
dialog_addDialog("ob-v-nerus", "de", "", "font_big", "Störe nicht. Der Spieler denkt wieder...")
dialog_addDialog("ob-v-nerus", "it", "", "font_big", "Non disturbare. Il giocatore sta di nuovo pensando...")

dialog_addDialog("ob-m-jetam", "en", "", "font_small", "Is there the player at all?")
dialog_addDialog("ob-m-jetam", "cs", "sound/share/borejokes/cs/ob-m-jetam.ogg", "font_small", "Je tam ten hráč vůbec?")
dialog_addDialog("ob-m-jetam", "fr", "", "font_small", "Y a-t-il un joueur tout court ?")
dialog_addDialog("ob-m-jetam", "de", "", "font_small", "Gibt es den Spieler überhaupt?")
dialog_addDialog("ob-m-jetam", "it", "", "font_small", "Ma... c'è ancora un giocatore?")

dialog_addDialog("ob-v-leskne", "en", "", "font_big", "I don`t know. The screen glares too much from inside.")
dialog_addDialog("ob-v-leskne", "cs", "sound/share/borejokes/cs/ob-v-leskne.ogg", "font_big", "Nevím, obrazovka se zevnitř děsně leskne.")
dialog_addDialog("ob-v-leskne", "fr", "", "font_big", "Je ne sais pas. l'écran brille trop de l'intérieur.")
dialog_addDialog("ob-v-leskne", "de", "", "font_big", "Ich weiß nicht. Der Bildschirm glänzt so von innen.")
dialog_addDialog("ob-v-leskne", "de_CH", "", "font_big", "Ich weiss nicht. Der Bildschirm glänzt so von innen.")
dialog_addDialog("ob-v-leskne", "it", "", "font_big", "Non saprei: lo schermo riflette troppo dal di dentro.")

dialog_addDialog("ob-v-prestavka", "en", "", "font_big", "The little break will help.")
dialog_addDialog("ob-v-prestavka", "cs", "sound/share/borejokes/cs/ob-v-prestavka.ogg", "font_big", "Malá přestávka nezaškodí.")
dialog_addDialog("ob-v-prestavka", "fr", "", "font_big", "Une petite pause peut aider.")
dialog_addDialog("ob-v-prestavka", "de", "", "font_big", "Die kleine Pause wird helfen.")
dialog_addDialog("ob-v-prestavka", "it", "", "font_big", "Una piccola pausa aiuta.")

dialog_addDialog("ob-o-nebavi", "en", "", "font_both", "We are tired of waiting!")
dialog_addDialog("ob-o-nebavi", "cs", "sound/share/borejokes/cs/ob-o-nebavi.ogg", "font_both", "Už nás to čekání nebaví!")
dialog_addDialog("ob-o-nebavi", "fr", "", "font_both", "Nous sommes fatigués d'attendre !")
dialog_addDialog("ob-o-nebavi", "de", "", "font_both", "Wir wollen nicht länger warten!")
dialog_addDialog("ob-o-nebavi", "it", "", "font_both", "Siamo stufi di aspettare!")

dialog_addDialog("ob-o-halo", "en", "", "font_both", "Hello!")
dialog_addDialog("ob-o-halo", "cs", "sound/share/borejokes/cs/ob-o-halo.ogg", "font_both", "Halóóó!")
dialog_addDialog("ob-o-halo", "fr", "", "font_both", "Hello!")
dialog_addDialog("ob-o-halo", "de", "", "font_both", "Hallo!")
dialog_addDialog("ob-o-halo", "it", "", "font_both", "Ehilà!")

dialog_addDialog("ob-v-nelekl", "en", "", "font_big", "Did you flinch?")
dialog_addDialog("ob-v-nelekl", "cs", "sound/share/borejokes/cs/ob-v-nelekl.ogg", "font_big", "Nelekl ses?")
dialog_addDialog("ob-v-nelekl", "fr", "", "font_big", "Tu es timide ?")
dialog_addDialog("ob-v-nelekl", "de", "", "font_big", "Hast Du aufgegeben?")
dialog_addDialog("ob-v-nelekl", "it", "", "font_big", "Ti sei arreso?")

dialog_addDialog("ob-m-mysleli", "en", "", "font_small", "We were just afraid that you might have forgotten about us.")
dialog_addDialog("ob-m-mysleli", "cs", "sound/share/borejokes/cs/ob-m-mysleli.ogg", "font_small", "My jsme jen mysleli, jestli jsi na nás nezapomněl.")
dialog_addDialog("ob-m-mysleli", "fr", "", "font_small", "Nous avons simplement peur que tu nous aies oubliés.")
dialog_addDialog("ob-m-mysleli", "de", "", "font_small", "Wir hatten schon Angst, dass Du uns vergessen hast.")
dialog_addDialog("ob-m-mysleli", "it", "", "font_small", "Avevamo solo paura che ti fossi dimenticato di noi.")

dialog_addDialog("ob-v-nehybes", "en", "", "font_big", "Look, why don`t you move us a little bit?")
dialog_addDialog("ob-v-nehybes", "cs", "sound/share/borejokes/cs/ob-v-nehybes.ogg", "font_big", "Hele, proč s námi nehýbeš?")
dialog_addDialog("ob-v-nehybes", "fr", "", "font_big", "Regarde, pourquoi est-ce que tu ne nous bouges pas un petit peu ?")
dialog_addDialog("ob-v-nehybes", "de", "", "font_big", "Schau, warum bewegst Du uns nicht ein bißchen?")
dialog_addDialog("ob-v-nehybes", "de_CH", "", "font_big", "Schau, warum bewegst Du uns nicht ein bisschen?")
dialog_addDialog("ob-v-nehybes", "it", "", "font_big", "Scusa, perché non ci muovi un po'?")

dialog_addDialog("ob-m-resit", "en", "", "font_small", "We are the game, you are supposed to solve us.")
dialog_addDialog("ob-m-resit", "cs", "sound/share/borejokes/cs/ob-m-resit.ogg", "font_small", "My jsme hra, nás máš řešit.")
dialog_addDialog("ob-m-resit", "fr", "", "font_small", "Nous sommes le jeu, tu es sensé le résoudre.")
dialog_addDialog("ob-m-resit", "de", "", "font_small", "Wir sind das Spiel und Du solltest es lösen.")
dialog_addDialog("ob-m-resit", "it", "", "font_small", "Noi siamo il video-gioco, dovresti risolverci.")

dialog_addDialog("ob-v-akvarium", "en", "", "font_big", "Buy yourself a fish tank for observations.")
dialog_addDialog("ob-v-akvarium", "cs", "sound/share/borejokes/cs/ob-v-akvarium.ogg", "font_big", "Na koukání si pořiď akvárium.")
dialog_addDialog("ob-v-akvarium", "fr", "", "font_big", "Achète un bocal pour faire des observations.")
dialog_addDialog("ob-v-akvarium", "de", "", "font_big", "Kauf Dir ein Aquarium für Beobachtungen.")
dialog_addDialog("ob-v-akvarium", "it", "", "font_big", "Comprati un acquario se vuoi solo osservare.")

dialog_addDialog("ob-v-halo", "en", "", "font_big", "Hellooo! We are here! Did you forget about us?")
dialog_addDialog("ob-v-halo", "cs", "sound/share/borejokes/cs/ob-v-halo.ogg", "font_big", "Halóóó! My jsme tady! Nezapomněl jsi na nás?")
dialog_addDialog("ob-v-halo", "fr", "", "font_big", "Hellooo ! Nous sommes ici ! Nous as-tu oubliés ?")
dialog_addDialog("ob-v-halo", "de", "", "font_big", "Haalooo! Wir sind hier! Hast Du uns vergessen?")
dialog_addDialog("ob-v-halo", "it", "", "font_big", "Ehilaa! Siamo qui! Ti sei scordato di noi?")

dialog_addDialog("ob-m-tezky", "en", "", "font_small", "Difficult, isn`t it?")
dialog_addDialog("ob-m-tezky", "cs", "sound/share/borejokes/cs/ob-m-tezky.ogg", "font_small", "Těžký, co?")
dialog_addDialog("ob-m-tezky", "fr", "", "font_small", "Difficile, n'est-ce pas ?")
dialog_addDialog("ob-m-tezky", "de", "", "font_small", "Schwierig, oder?")
dialog_addDialog("ob-m-tezky", "it", "", "font_small", "Difficile, vero?")

dialog_addDialog("ob-v-jidlo", "en", "", "font_big", "Look player, couldn`t you bring us something to eat? Put it in the TEMP directory, we`ll eat it momentarily.")
dialog_addDialog("ob-v-jidlo", "cs", "sound/share/borejokes/cs/ob-v-jidlo.ogg", "font_big", "Hele, hráči, neskočil bys nám pro něco k jídlu? Dej nám to do adresáře TMP, hned to sníme.")
dialog_addDialog("ob-v-jidlo", "fr", "", "font_big", "Attends joueur, tu ne peux pas nous apporter quelque chose à manger ? Mets le dans le répertoire temporaire, nous le mangerons à l'occasion.")
dialog_addDialog("ob-v-jidlo", "de", "", "font_big", "Schau Spieler, könntest Du uns nicht etwas zu essen bringen? Lege es ins TEMP-Verzeichnis, wir werden es augenblicklich essen.")
dialog_addDialog("ob-v-jidlo", "it", "", "font_big", "Ascolta, potresti portarci qualcosa da mangiare? Mettilo nella cartella TEMP, così nel frattempo lo mangiamo.")

dialog_addDialog("ob-m-strach", "en", "", "font_small", "When you stop playing, don`t turn off the computer, please. It`s so dark and scary here if you do.")
dialog_addDialog("ob-m-strach", "cs", "sound/share/borejokes/cs/ob-m-strach.ogg", "font_small", "Prosím tě, až přestaneš hrát, nevypínej počítač... je tady pak hrozná tma a mám strach.")
dialog_addDialog("ob-m-strach", "fr", "", "font_small", "Quand tu arrêtes de jouer, n'éteins pas l'ordinateur, s'il te plaît. C'est si noir et effrayant quand tu éteins.")
dialog_addDialog("ob-m-strach", "de", "", "font_small", "Wenn Du aufhörst zu spielen, mach den Rechner bitte nicht aus. Es ist sonst so dunkel und gruselig hier.")
dialog_addDialog("ob-m-strach", "it", "", "font_small", "Quando smetti di giocare, non spegnere il computer per favore. Se lo fai sarà tutto così buio e spaventoso.")

dialog_addDialog("ob-m-jakdlouho", "en", "", "font_small", "How long are we going to solve it?")
dialog_addDialog("ob-m-jakdlouho", "cs", "sound/share/borejokes/cs/ob-m-jakdlouho.ogg", "font_small", "Jak dlouho to ještě budeme řešit?")
dialog_addDialog("ob-m-jakdlouho", "fr", "", "font_small", "Combien de temps il nous faudra pour trouver la solution ?")
dialog_addDialog("ob-m-jakdlouho", "de", "", "font_small", "Wie lange werden wir es lösen?")
dialog_addDialog("ob-m-jakdlouho", "it", "", "font_small", "Quanto ci metteremo per finire?")

dialog_addDialog("ob-v-zvykacka", "en", "", "font_big", "As long as the taste of this chewing gum lasts.")
dialog_addDialog("ob-v-zvykacka", "cs", "sound/share/borejokes/cs/ob-v-zvykacka.ogg", "font_big", "Tak dlouho, jak dlouho vydrží chuť téhle žvýkačky...")
dialog_addDialog("ob-v-zvykacka", "fr", "", "font_big", "Aussi longtemps que ce chewing-gum a du goût.")
dialog_addDialog("ob-v-zvykacka", "de", "", "font_big", "So lange wie der Geschmack dieses Kaugummis hält.")
dialog_addDialog("ob-v-zvykacka", "it", "", "font_big", "Fiché dura il gusto di questo chewing-gum.")

dialog_addDialog("ob-m-zvykacka", "en", "", "font_small", "What, you are finished? But this chewing gum still tastes extraordinary.")
dialog_addDialog("ob-m-zvykacka", "cs", "sound/share/borejokes/cs/ob-m-zvykacka.ogg", "font_small", "Cože, hotovo? Vždyť ta žvýkačka chutná ještě pořád skvěle.")
dialog_addDialog("ob-m-zvykacka", "fr", "", "font_small", "Quoi, tu as fini ? Mais ce chewing-gum a encore un goût extraordinaire.")
dialog_addDialog("ob-m-zvykacka", "de", "", "font_small", "Was, Du bist fertig? Aber dieser Kaugummi schmeckt noch außerordentlich gut.")
dialog_addDialog("ob-m-zvykacka", "it", "", "font_small", "Cosa? già finito? Ma il chewing-gum è ancora buono.")

dialog_addDialog("ob-v-ostani", "en", "", "font_big", "What do you think, how are the other faring?")
dialog_addDialog("ob-v-ostani", "cs", "sound/share/borejokes/cs/ob-v-ostani.ogg", "font_big", "Co myslíš, jak jsou na tom ostatní?")
dialog_addDialog("ob-v-ostani", "fr", "", "font_big", "Dis donc, comment sont les autres fish-filleteurs ?")
dialog_addDialog("ob-v-ostani", "de", "", "font_big", "Was denkst Du, wie geht es den anderen?")
dialog_addDialog("ob-v-ostani", "it", "", "font_big", "Come pensi se la stiano cavando gli altri?")

dialog_addDialog("ob-m-kdo", "en", "", "font_small", "The other who?")
dialog_addDialog("ob-m-kdo", "cs", "sound/share/borejokes/cs/ob-m-kdo.ogg", "font_small", "To jako kdo?")
dialog_addDialog("ob-m-kdo", "fr", "", "font_small", "Les autres quoi ?")
dialog_addDialog("ob-m-kdo", "de", "", "font_small", "Welchen anderen?")
dialog_addDialog("ob-m-kdo", "in", "", "font_small", "Gli altri... chi?")

dialog_addDialog("ob-v-kdoresi", "en", "", "font_big", "The other players who are solving this game. Maybe they managed to solve more levels.")
dialog_addDialog("ob-v-kdoresi", "cs", "sound/share/borejokes/cs/ob-v-kdoresi.ogg", "font_big", "No ostatní, kdo to řeší. Třeba už mají víc místností.")
dialog_addDialog("ob-v-kdoresi", "fr", "", "font_big", "Les autres joueurs qui cogitent sur ce jeux. Peut-être qu'ils ont résolu plus de niveaux.")
dialog_addDialog("ob-v-kdoresi", "de", "", "font_big", "Die anderen Spieler, die das Spiel lösen. Vielleicht haben sie geschafft, mehr Ebenen zu lösen.")
dialog_addDialog("ob-v-kdoresi", "it", "", "font_big", "Gli altri giocatori che stanno risolvendo il gioco. Forse hanno già risolto altri livelli.")

dialog_addDialog("ob-m-pravdepodobne", "en", "", "font_small", "It`s very likely.")
dialog_addDialog("ob-m-pravdepodobne", "cs", "sound/share/borejokes/cs/ob-m-pravdepodobne.ogg", "font_small", "To je dost pravděpodobné.")
dialog_addDialog("ob-m-pravdepodobne", "fr", "", "font_small", "C'est très probable.")
dialog_addDialog("ob-m-pravdepodobne", "de", "", "font_small", "Das ist sehr wahrscheinlich.")
dialog_addDialog("ob-m-pravdepodobne", "it", "", "font_small", "E` molto probabile.")

dialog_addDialog("ob-m-ach", "en", "", "font_small", "Oh, yeah.")
dialog_addDialog("ob-m-ach", "cs", "sound/share/borejokes/cs/ob-m-ach.ogg", "font_small", "Ach jo.")
dialog_addDialog("ob-m-ach", "fr", "", "font_small", "Oh, non.")
dialog_addDialog("ob-m-ach", "de", "", "font_small", "Oh, ja.")
dialog_addDialog("ob-m-ach", "it", "", "font_small", "Oh, sì.")

dialog_addDialog("ob-v-copak", "en", "", "font_big", "What happened?")
dialog_addDialog("ob-v-copak", "cs", "sound/share/borejokes/cs/ob-v-copak.ogg", "font_big", "Copak?")
dialog_addDialog("ob-v-copak", "fr", "", "font_big", "Que se passe-t-il ?")
dialog_addDialog("ob-v-copak", "de", "", "font_big", "Was ist passiert?")
dialog_addDialog("ob-v-copak", "it", "", "font_big", "Che succede?")

dialog_addDialog("ob-m-lito", "en", "", "font_small", "I just feel so sorry...")
dialog_addDialog("ob-m-lito", "cs", "sound/share/borejokes/cs/ob-m-lito.ogg", "font_small", "Přišlo mi to tak nějak líto.")
dialog_addDialog("ob-m-lito", "fr", "", "font_small", "Je me sens si navrée...")
dialog_addDialog("ob-m-lito", "de", "", "font_small", "Das tut mir so leid...")
dialog_addDialog("ob-m-lito", "it", "", "font_small", "Sono così dispiaciuta...")

dialog_addDialog("ob-v-colito", "en", "", "font_big", "Sorry for what?")
dialog_addDialog("ob-v-colito", "cs", "sound/share/borejokes/cs/ob-v-colito.ogg", "font_big", "Co ti přišlo líto?")
dialog_addDialog("ob-v-colito", "fr", "", "font_big", "Navrée de quoi ?")
dialog_addDialog("ob-v-colito", "de", "", "font_big", "Was tut Dir leid?")
dialog_addDialog("ob-v-colito", "it", "", "font_big", "Dispiaciuta per cosa?")

dialog_addDialog("ob-m-vsechno", "en", "", "font_small", "Sorry for everything.")
dialog_addDialog("ob-m-vsechno", "cs", "sound/share/borejokes/cs/ob-m-vsechno.ogg", "font_small", "No... všechno.")
dialog_addDialog("ob-m-vsechno", "fr", "", "font_small", "Navrée de tout.")
dialog_addDialog("ob-m-vsechno", "de", "", "font_small", "Alles tut mir leid.")
dialog_addDialog("ob-m-vsechno", "it", "", "font_small", "Per tutto.")

dialog_addDialog("ob-v-covsechno", "en", "", "font_big", "What everything?")
dialog_addDialog("ob-v-covsechno", "cs", "sound/share/borejokes/cs/ob-v-covsechno.ogg", "font_big", "Co všechno?")
dialog_addDialog("ob-v-covsechno", "fr", "", "font_big", "Quoi tout ?")
dialog_addDialog("ob-v-covsechno", "de", "", "font_big", "Was alles?")
dialog_addDialog("ob-v-covsechno", "it", "", "font_big", "Tutto cosa?")

dialog_addDialog("ob-m-uplnevse", "en", "", "font_small", "Completely everything! And leave me alone, I beg you!")
dialog_addDialog("ob-m-uplnevse", "cs", "sound/share/borejokes/cs/ob-m-uplnevse.ogg", "font_small", "Úplně všechno! A vůbec, starej se o sebe!")
dialog_addDialog("ob-m-uplnevse", "fr", "", "font_small", "Vraiment tout ! Et laisse moi seule, je t'en supplie !")
dialog_addDialog("ob-m-uplnevse", "de", "", "font_small", "Na alles! Und lass mich bitte allein!")
dialog_addDialog("ob-m-uplnevse", "it", "", "font_small", "Tutto completamente! E lasciami sola, ti prego!")


