dialog_addDialog("pap-v-ha", "en", "", "font_big", "Look. Another energy source.")
dialog_addDialog("pap-v-ha", "cs", "sound/"..codename.."/cs/pap-v-ha.ogg", "font_big", "Ha. Další zdroj energie.")
dialog_addDialog("pap-v-ha", "fr", "", "font_big", "Regarde. Une nouvelle source d'énergie.")
dialog_addDialog("pap-v-ha", "de", "", "font_big", "Schau. Noch eine Energiequelle.")
dialog_addDialog("pap-v-ha", "it", "", "font_big", "Guarda: un'altra fonte di energia.")

dialog_addDialog("pap-m-magnet", "en", "", "font_small", "Don`t worry. This magnet is here only to hinder us.")
dialog_addDialog("pap-m-magnet", "cs", "sound/"..codename.."/cs/pap-m-magnet.ogg", "font_small", "Dej pokoj, ten magnet je tady jen proto, aby nám překážel.")
dialog_addDialog("pap-m-magnet", "fr", "", "font_small", "Fais pas attention. Cet aimant n'est là que pour nous gêner.")
dialog_addDialog("pap-m-magnet", "de", "", "font_small", "Keine Angst, der Magnet ist nur hier, um uns zu behindern.")
dialog_addDialog("pap-m-magnet", "it", "", "font_small", "Non agitarti. Quella calamita è qui solo per ostacolarci.")

dialog_addDialog("pap-v-potrebovat", "en", "", "font_big", "I think we are going to need it.")
dialog_addDialog("pap-v-potrebovat", "cs", "sound/"..codename.."/cs/pap-v-potrebovat.ogg", "font_big", "Já myslím, že ho ještě budeme potřebovat.")
dialog_addDialog("pap-v-potrebovat", "fr", "", "font_big", "Je pense que nous allons en avoir besoin.")
dialog_addDialog("pap-v-potrebovat", "de", "", "font_big", "Ich denke, wir werden ihn brauchen.")
dialog_addDialog("pap-v-potrebovat", "it", "", "font_big", "Penso che ne avremo bisogno.")

dialog_addDialog("pap-m-zvlastni", "en", "", "font_small", "This is a very strange object.")
dialog_addDialog("pap-m-zvlastni", "cs", "sound/"..codename.."/cs/pap-m-zvlastni.ogg", "font_small", "To je ale zvláštní předmět.")
dialog_addDialog("pap-m-zvlastni", "fr", "", "font_small", "Quel drôle d'objet.")
dialog_addDialog("pap-m-zvlastni", "de", "", "font_small", "Das ist ein ziemlich seltsames Ding.")
dialog_addDialog("pap-m-zvlastni", "it", "", "font_small", "Questo oggetto è molto strano.")

dialog_addDialog("pap-v-prekvapeni", "en", "", "font_big", "I think that UFO is going to be full of such surprises.")
dialog_addDialog("pap-v-prekvapeni", "cs", "sound/"..codename.."/cs/pap-v-prekvapeni.ogg", "font_big", "Myslím, že v Ufu bude spousta takových překvapení.")
dialog_addDialog("pap-v-prekvapeni", "fr", "", "font_big", "Je pense que les ovnis sont pleins de surprises similaires.")
dialog_addDialog("pap-v-prekvapeni", "de", "", "font_big", "Ich denke, dieses UFO wird voller Überraschungen sein.")
dialog_addDialog("pap-v-prekvapeni", "it", "", "font_big", "Immagino che l'UFO sarà pieno di queste soprese.")

dialog_addDialog("pap-m-teorie", "en", "", "font_small", "Stop developing your theories and start solving.")
dialog_addDialog("pap-m-teorie", "cs", "sound/"..codename.."/cs/pap-m-teorie.ogg", "font_small", "Nerozvíjej svoje teorie a raději to nějak vyřešme.")
dialog_addDialog("pap-m-teorie", "fr", "", "font_small", "Arrête de rêver et cherchons la solution.")
dialog_addDialog("pap-m-teorie", "de", "", "font_small", "Hör auf, Theorien zu entwickeln und such eine Lösung.")
dialog_addDialog("pap-m-teorie", "it", "", "font_small", "Smettila di sviluppare le tue teorie e inizia a risolvere.")

dialog_addDialog("pap-m-radio", "en", "", "font_small", "This looks like a radio.")
dialog_addDialog("pap-m-radio", "cs", "sound/"..codename.."/cs/pap-m-radio.ogg", "font_small", "Tohle vypadá jako rádio.")
dialog_addDialog("pap-m-radio", "fr", "", "font_small", "Ca ressemble à une radio.")
dialog_addDialog("pap-m-radio", "de", "", "font_small", "Das sieht aus wie ein Radio.")
dialog_addDialog("pap-m-radio", "it", "", "font_small", "Sembra una radio.")

dialog_addDialog("pap-v-radio", "en", "", "font_big", "How could a radio get here?")
dialog_addDialog("pap-v-radio", "cs", "sound/"..codename.."/cs/pap-v-radio.ogg", "font_big", "Kde by se tady vzalo rádio?")
dialog_addDialog("pap-v-radio", "fr", "", "font_big", "Comment est-se qu'une radio pourrait arriver ici ?")
dialog_addDialog("pap-v-radio", "de", "", "font_big", "Wie kommt ein Radio hierher?")
dialog_addDialog("pap-v-radio", "it", "", "font_big", "Come può essere arrivata qui una radio?")

dialog_addDialog("pap-m-nechme", "en", "", "font_small", "Let it be.")
dialog_addDialog("pap-m-nechme", "cs", "sound/"..codename.."/cs/pap-m-nechme.ogg", "font_small", "Nechme toho.")
dialog_addDialog("pap-m-nechme", "fr", "", "font_small", "Laissons ça.")
dialog_addDialog("pap-m-nechme", "de", "", "font_small", "Lass es.")
dialog_addDialog("pap-m-nechme", "it", "", "font_small", "Lascia stare.")

dialog_addDialog("pap-v-divny", "en", "", "font_big", "This is a strange radio.")
dialog_addDialog("pap-v-divny", "cs", "sound/"..codename.."/cs/pap-v-divny.ogg", "font_big", "To je ale divný rádio.")
dialog_addDialog("pap-v-divny", "fr", "", "font_big", "C'est une radio bizarre.")
dialog_addDialog("pap-v-divny", "de", "", "font_big", "Das ist ein seltsames Radio.")
dialog_addDialog("pap-v-divny", "it", "", "font_big", "E` una strana radio.")

dialog_addDialog("pap-m-coje", "en", "", "font_small", "What have we here?")
dialog_addDialog("pap-m-coje", "cs", "sound/"..codename.."/cs/pap-m-coje.ogg", "font_small", "Co je to tady?")
dialog_addDialog("pap-m-coje", "fr", "", "font_small", "Qu'avons-nous là ?")
dialog_addDialog("pap-m-coje", "de", "", "font_small", "Was ist das hier?")
dialog_addDialog("pap-m-coje", "it", "", "font_small", "Che cosa abbiamo qui?")

dialog_addDialog("pap-m-pistole", "en", "", "font_small", "It looks like a pistol to me.")
dialog_addDialog("pap-m-pistole", "cs", "sound/"..codename.."/cs/pap-m-pistole.ogg", "font_small", "Připomíná to pistoli.")
dialog_addDialog("pap-m-pistole", "fr", "", "font_small", "Pour moi, ça ressemble à un pistolet.")
dialog_addDialog("pap-m-pistole", "de", "", "font_small", "Sieht aus wie eine Pistole.")
dialog_addDialog("pap-m-pistole", "it", "", "font_small", "A me sembra come una pistola.")

dialog_addDialog("pap-v-laserova", "en", "", "font_big", "Maybe it`s a laser weapon.")
dialog_addDialog("pap-v-laserova", "cs", "sound/"..codename.."/cs/pap-v-laserova.ogg", "font_big", "Třeba je to laserová zbraň.")
dialog_addDialog("pap-v-laserova", "fr", "", "font_big", "Peut-être c'est un pistolet laser.")
dialog_addDialog("pap-v-laserova", "de", "", "font_big", "Vielleicht ist es eine Laserwaffe.")
dialog_addDialog("pap-v-laserova", "it", "", "font_big", "Forse è un'arma laser.")

dialog_addDialog("pap-m-jejedno", "en", "", "font_small", "It doesn`t matter. We don`t need it.")
dialog_addDialog("pap-m-jejedno", "cs", "sound/"..codename.."/cs/pap-m-jejedno.ogg", "font_small", "To je jedno, tu snad nepotřebujeme.")
dialog_addDialog("pap-m-jejedno", "fr", "", "font_small", "Peu importe, nous n'en avons pas besoin.")
dialog_addDialog("pap-m-jejedno", "de", "", "font_small", "Egal, wir brauchen sie nicht.")
dialog_addDialog("pap-m-jejedno", "it", "", "font_small", "Non importa. Non ne abbiamo bisogno.")

dialog_addDialog("pap-v-nemir", "en", "", "font_big", "Stop pointing at me with it!")
dialog_addDialog("pap-v-nemir", "cs", "sound/"..codename.."/cs/pap-v-nemir.ogg", "font_big", "Hlavně s ní nemiř na mě!")
dialog_addDialog("pap-v-nemir", "fr", "", "font_big", "Arrête de me viser avec ça !")
dialog_addDialog("pap-v-nemir", "de", "", "font_big", "Hör auf, damit auf mich zu zielen!")
dialog_addDialog("pap-v-nemir", "it", "", "font_big", "Non puntarmi addosso quel coso!")

dialog_addDialog("pap-m-nejde", "en", "", "font_small", "As if you don`t know that you can`t turn objects in this game.")
dialog_addDialog("pap-m-nejde", "cs", "sound/"..codename.."/cs/pap-m-nejde.ogg", "font_small", "Jako bys nevěděl, že v této hře nejde předměty otáčet!")
dialog_addDialog("pap-m-nejde", "fr", "", "font_small", "Comme si tu ne savais pas que tu ne peux pas faire pivoter les objets dans ce jeu.")
dialog_addDialog("pap-m-nejde", "de", "", "font_small", "Als wenn du nicht wüsstest, dass man in diesem Spiel keine Gegenstände drehen kann.")
dialog_addDialog("pap-m-nejde", "it", "", "font_small", "Come se non sapessi che in questo gioco non si possono ruotare gli oggetti.")

dialog_addDialog("pap-m-ocel", "en", "", "font_small", "There are too many steel constructions here.")
dialog_addDialog("pap-m-ocel", "cs", "sound/"..codename.."/cs/pap-m-ocel.ogg", "font_small", "Je tu nějak moc těch ocelových konstrukcí.")
dialog_addDialog("pap-m-ocel", "fr", "", "font_small", "Il y a trop d'acier ici.")
dialog_addDialog("pap-m-ocel", "de", "", "font_small", "Hier sind zu viele Stahlkonstruktionen.")
dialog_addDialog("pap-m-ocel", "it", "", "font_small", "Ci sono troppe strutture in acciaio qui.")

dialog_addDialog("pap-v-vufu", "en", "", "font_big", "Don`t forget that we are inside of the flying saucer!")
dialog_addDialog("pap-v-vufu", "cs", "sound/"..codename.."/cs/pap-v-vufu.ogg", "font_big", "Nezapomínej, že jsme uvnitř létajícího talíře!")
dialog_addDialog("pap-v-vufu", "fr", "", "font_big", "N'oublie pas que nous sommes à bord d'une soucoupe volante.")
dialog_addDialog("pap-v-vufu", "de", "", "font_big", "Vergiss nicht, dass wir innerhalb einer fliegenden Untertasse sind!")
dialog_addDialog("pap-v-vufu", "it", "", "font_big", "Non dimenticarti che siamo dentro al disco volante!")

dialog_addDialog("pap-m-naucit", "en", "", "font_small", "Maybe I could learn how to manipulate these steel tubes.")
dialog_addDialog("pap-m-naucit", "cs", "sound/"..codename.."/cs/pap-m-naucit.ogg", "font_small", "Možná bych se mohla naučit manipulovat s těmi ocelovými válci.")
dialog_addDialog("pap-m-naucit", "fr", "", "font_small", "Peut-être que je pourrais apprendre à porter ces tubes d'acier.")
dialog_addDialog("pap-m-naucit", "de", "", "font_small", "Vielleicht kann ich lernen, die Stahlrohre zu verschieben.")
dialog_addDialog("pap-m-naucit", "it", "", "font_small", "Forse dovrei imparare a manipolare questi tubi d'acciaio.")

dialog_addDialog("pap-m-nepohnu", "en", "", "font_small", "No, I can`t move it.")
dialog_addDialog("pap-m-nepohnu", "cs", "sound/"..codename.."/cs/pap-m-nepohnu.ogg", "font_small", "Ne, s tím nepohnu.")
dialog_addDialog("pap-m-nepohnu", "fr", "", "font_small", "Non, je ne peux le déplacer.")
dialog_addDialog("pap-m-nepohnu", "de", "", "font_small", "Nein, ich kann sie nicht bewegen.")
dialog_addDialog("pap-m-nepohnu", "it", "", "font_small", "No, non ci riesco.")

dialog_addDialog("pap-v-tesno", "en", "", "font_big", "It`s quite tight here.")
dialog_addDialog("pap-v-tesno", "cs", "sound/"..codename.."/cs/pap-v-tesno.ogg", "font_big", "Je  tu nějak těsno.")
dialog_addDialog("pap-v-tesno", "fr", "", "font_big", "Je me sens un peu à l'étroit ici.")
dialog_addDialog("pap-v-tesno", "de", "", "font_big", "Ziemlich eng hier.")
dialog_addDialog("pap-v-tesno", "it", "", "font_big", "E` piuttosto stretto qui.")

dialog_addDialog("pap-m-mraz", "en", "", "font_small", "These magnets are giving me the creeps.")
dialog_addDialog("pap-m-mraz", "cs", "sound/"..codename.."/cs/pap-m-mraz.ogg", "font_small", "Běhá mi z těch magnetů mráz po zádech.")
dialog_addDialog("pap-m-mraz", "fr", "", "font_small", "Ces aimants me hérissent les écailles.")
dialog_addDialog("pap-m-mraz", "de", "", "font_small", "Von den Magneten bekomme ich eine Gänsehaut.")
dialog_addDialog("pap-m-mraz", "it", "", "font_small", "Questi magneti mi fanno accapponare la pelle.")

dialog_addDialog("pap-v-pole", "en", "", "font_big", "This magnetic field probably has some invigorating effects.")
dialog_addDialog("pap-v-pole", "cs", "sound/"..codename.."/cs/pap-v-pole.ogg", "font_big", "To magnetické pole má asi povzbuzující účinky.")
dialog_addDialog("pap-v-pole", "fr", "", "font_big", "Ce champs magnétique à probablement des effets fortifiants.")
dialog_addDialog("pap-v-pole", "de", "", "font_big", "Dieses Magnetfeld hat wahrscheinlich eine belebende Wirkung.")
dialog_addDialog("pap-v-pole", "it", "", "font_big", "Probabilmente questo campo magnetico ha qualche effetto rinvigorente.")

dialog_addDialog("pap-m-nedobre", "en", "", "font_small", "It`s doing me no good.")
dialog_addDialog("pap-m-nedobre", "cs", "sound/"..codename.."/cs/pap-m-nedobre.ogg", "font_small", "Mně to teda moc dobře nedělá.")
dialog_addDialog("pap-m-nedobre", "fr", "", "font_small", "Il ne me procure aucun bien être.")
dialog_addDialog("pap-m-nedobre", "de", "", "font_small", "Mir wird schlecht davon.")
dialog_addDialog("pap-m-nedobre", "it", "", "font_small", "A me non fa niente di buono.")
