-- this file is automatically generated
setParam("fullscreen", "0")
setParam("sound", "1")
setParam("loglevel", "6")
setParam("screen_bpp", "32")
setParam("screen_height", "480")
setParam("screen_width", "640")
