-- this file is automatically generated
setParam("fullscreen", "0")
setParam("level", "script/Pravidla.lua")
setParam("screen_bpp", "32")
setParam("screen_height", "480")
setParam("screen_width", "640")
