
node_bestSolution("start", 54, "Pavel Danihelka")
node_bestSolution("briefcase", 225, "Pavel Danihelka")
node_bestSolution("cellar", 375, "Pavel Danihelka")
node_bestSolution("library", 111, "Pavel Danihelka")
node_bestSolution("stairs", 163, "Pavel Danihelka")
node_bestSolution("broom", 193, "Ivo Danihelka")
node_bestSolution("reef", 169, "Pavel Danihelka")
node_bestSolution("wc", 100, "Pavel Danihelka")
 
node_bestSolution("submarine", 83, "Pavel Danihelka")
node_bestSolution("party1", 240, "Josef Peterka")
node_bestSolution("elk", 257, "Pavel Danihelka")
node_bestSolution("wreck", 93, "Pavel Danihelka")
node_bestSolution("viking1", 119, "Pavel Danihelka")
node_bestSolution("airplane", 259, "Josef Peterka")
node_bestSolution("bathyscaph", 82, "Pavel Danihelka")
node_bestSolution("tank", 402, "Josef Peterka")
node_bestSolution("viking2", 359, "Jan Danihelka")
node_bestSolution("party2", 285, "Josef Peterka")
node_bestSolution("gods", 943, "Josef Peterka")
 
node_bestSolution("elevator1", 200, "Pavel Danihelka")
node_bestSolution("city", 517, "Josef Peterka")
node_bestSolution("ufo", 287, "Jan Danihelka")
node_bestSolution("columns", 283, "Josef Peterka")
node_bestSolution("pavement", 630, "Josef Peterka")
node_bestSolution("pyramid", 262, "Charles Goodwin")
node_bestSolution("music", 393, "Josef Peterka")
node_bestSolution("crabshow", 344, "Jan Danihelka")
node_bestSolution("elevator2", 469, "Josef Peterka")
node_bestSolution("atlantis", 642, "Josef Peterka")
 
node_bestSolution("corals", 256, "Josef Peterka")
node_bestSolution("labyrinth", 280, "Josef Peterka")
node_bestSolution("imprisoned", 275, "Josef Peterka")
node_bestSolution("society", 122, "Josef Peterka")
node_bestSolution("creatures", 447, "Josef Peterka")
node_bestSolution("cancan", 876, "Josef Peterka")
node_bestSolution("pearls", 513, "Josef Peterka")
--node_bestSolution("turtle", 0, "")
 
node_bestSolution("computer", 156, "Josef Peterka")
node_bestSolution("noground", 44, "Heiko Luettges")
node_bestSolution("bathroom", 90, "Josef Peterka")
node_bestSolution("duckie", 98, "Ronny Standtke")
node_bestSolution("puzzle", 144, "Josef Peterka")
node_bestSolution("dump", 426, "Josef Peterka")
--node_bestSolution("barrel", 0, "")
 
node_bestSolution("cabin1", 168, "Pavel Danihelka")
node_bestSolution("snowman", 66, "Pavel Danihelka")
node_bestSolution("cannons", 39, "Pavel Danihelka")
node_bestSolution("kitchen", 564, "Josef Peterka")
node_bestSolution("cabin2", 413, "Josef Peterka")
node_bestSolution("captain", 571, "Tibor Zenis")
node_bestSolution("map", 4930, "Eric Estievenart")
 
node_bestSolution("reactor", 163, "Pavel Danihelka")
node_bestSolution("magnet", 408, "Josef Peterka")
node_bestSolution("engine", 270, "Josef Peterka")
node_bestSolution("steel", 185, "Josef Peterka")
node_bestSolution("corridor", 574, "Ronny Standtke")
node_bestSolution("experiments", 804, "Ronny Standtke")
--node_bestSolution("propulsion", 0, "")
 
node_bestSolution("aztec", 378, "Josef Peterka")
node_bestSolution("gems", 61, "Josef Peterka")
node_bestSolution("chest", 464, "Josef Peterka")
node_bestSolution("alibaba", 465, "Ronny Standtke")
node_bestSolution("cave", 190, "Josef Peterka")
--node_bestSolution("grail", 0, "")
 
node_bestSolution("tetris", 138, "Josef Peterka")
node_bestSolution("emulator", 976, "Josef Peterka")
node_bestSolution("warcraft", 573, "Josef Peterka")
node_bestSolution("windoze", 605, "Josef Peterka")
node_bestSolution("hardware", 739, "Josef Peterka")
--node_bestSolution("floppy", 0, "")
 
