
node_bestSolution("start", 54, "Pavel Danihelka")
node_bestSolution("briefcase", 225, "Pavel Danihelka")
node_bestSolution("cellar", 375, "Pavel Danihelka")
node_bestSolution("library", 111, "Pavel Danihelka")
node_bestSolution("stairs", 163, "Pavel Danihelka")
node_bestSolution("broom", 193, "Ivo Danihelka")
node_bestSolution("reef", 169, "Pavel Danihelka")
node_bestSolution("wc", 100, "Pavel Danihelka")
 
node_bestSolution("submarine", 83, "Pavel Danihelka")
node_bestSolution("party1", 254, "Pavel Danihelka")
node_bestSolution("elk", 257, "Pavel Danihelka")
node_bestSolution("wreck", 93, "Pavel Danihelka")
node_bestSolution("viking1", 119, "Pavel Danihelka")
node_bestSolution("airplane", 307, "Frederic Panico")
node_bestSolution("bathyscaph", 82, "Pavel Danihelka")
node_bestSolution("tank", 428, "Evin Robertson")
node_bestSolution("viking2", 359, "Jan Danihelka")
node_bestSolution("party2", 297, "Jan Danihelka")
--node_bestSolution("gods", 0, "")
 
node_bestSolution("elevator1", 200, "Pavel Danihelka")
node_bestSolution("city", 591, "Pavel Danihelka")
node_bestSolution("ufo", 287, "Jan Danihelka")
node_bestSolution("columns", 285, "Eric Estievenart")
node_bestSolution("pavement", 696, "Tibor Zenis")
node_bestSolution("pyramid", 262, "Charles Goodwin")
node_bestSolution("music", 397, "Charles Goodwin")
node_bestSolution("crabshow", 344, "Jan Danihelka")
node_bestSolution("elevator2", 503, "Ronny Standtke")
node_bestSolution("atlantis", 2088, "Eric Estievenart")
 
node_bestSolution("corals", 304, "Ronny Standtke")
node_bestSolution("labyrinth", 304, "Ronny Standtke")
node_bestSolution("imprisoned", 307, "Jan Danihelka")
node_bestSolution("society", 160, "Ronny Standtke")
node_bestSolution("creatures", 455, "Ronny Standtke")
node_bestSolution("cancan", 880, "Jan Danihelka")
node_bestSolution("pearls", 537, "Ronny Standtke")
--node_bestSolution("turtle", 0, "")
 
node_bestSolution("computer", 164, "Charles Goodwin")
node_bestSolution("noground", 44, "Heiko Luettges")
node_bestSolution("bathroom", 92, "Pavel Danihelka")
node_bestSolution("duckie", 98, "Ronny Standtke")
node_bestSolution("puzzle", 239, "Ronny Standtke")
node_bestSolution("dump", 454, "Ronny Standtke")
--node_bestSolution("barrel", 0, "")
 
node_bestSolution("cabin1", 168, "Pavel Danihelka")
node_bestSolution("snowman", 66, "Pavel Danihelka")
node_bestSolution("cannons", 39, "Pavel Danihelka")
node_bestSolution("kitchen", 626, "Frederic Panico")
node_bestSolution("cabin2", 445, "Ronny Standtke")
node_bestSolution("captain", 571, "Tibor Zenis")
node_bestSolution("map", 4930, "Eric Estievenart")
 
node_bestSolution("reactor", 163, "Pavel Danihelka")
node_bestSolution("magnet", 410, "Ronny Standtke")
node_bestSolution("engine", 323, "Ronny Standtke")
node_bestSolution("steel", 189, "Tibor Zenis")
node_bestSolution("corridor", 574, "Ronny Standtke")
--node_bestSolution("experiments", 0, "")
--node_bestSolution("propulsion", 0, "")
 
node_bestSolution("aztec", 418, "Ronny Standtke")
node_bestSolution("gems", 63, "Ivo Danihelka")
node_bestSolution("chest", 738, "Ronny Standtke")
node_bestSolution("alibaba", 465, "Ronny Standtke")
node_bestSolution("cave", 198, "Ronny Standtke")
--node_bestSolution("grail", 0, "")
 
node_bestSolution("tetris", 156, "Ronny Standtke")
node_bestSolution("emulator", 1024, "Ronny Standtke")
node_bestSolution("warcraft", 577, "Ronny Standtke")
node_bestSolution("windoze", 659, "Ronny Standtke")
node_bestSolution("hardware", 741, "Ronny Standtke")
--node_bestSolution("floppy", 0, "")
 
