
-- worldmap_addDesc(codename, lang, levelname, desc)
worldmap_addDesc("menu", "en", "Game menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "cs", "Hern?? menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "fr", "Menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "de", "Men??", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "it", "Men??", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "pl", "Menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "es", "Men??", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "nl", "Menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "bg", "Меню", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "sv", "Meny", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "sl", "Menu igre", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "pt_BR", "Menu", "Fish Fillets - Next Generation")
worldmap_addDesc("menu", "ru", "Меню", "Fish Fillets - Next Generation")

worldmap_addDesc("start", "en", "How It All Started", "Fish House")
worldmap_addDesc("start", "cs", "Jak to v??echno za??alo", "Ryb?? dome??ek")
worldmap_addDesc("start", "fr", "Comment tout a commenc??", "Maison Poisson")
worldmap_addDesc("start", "de", "Wie alles anfing", "Fischhaus")
worldmap_addDesc("start", "it", "Come ?? iniziato tutto", "La Casa dei Pesci")
worldmap_addDesc("start", "pl", "Jak to si?? wszystko zacz????o", "Rybi domek")
worldmap_addDesc("start", "es", "Como Empez?? Todo", "Casa Pez")
worldmap_addDesc("start", "nl", "Hoe het allemaal begon", "Vissenhuis")
worldmap_addDesc("start", "bg", "Как започна всичко", "Дома на рибките")
worldmap_addDesc("start", "sv", "Hur allt b??rjade", "Fiskhuset")
worldmap_addDesc("start", "sl", "Kako se je vse za??elo", "Ribja hi??a")
worldmap_addDesc("start", "pt_BR", "Como Tudo Come??ou", "Peixaria")
worldmap_addDesc("start", "ru", "Как это началось", "Рыбий дом")

worldmap_addDesc("briefcase", "en", "Briefcase Message", "Fish House")
worldmap_addDesc("briefcase", "cs", "Podivn?? z??silka", "Ryb?? dome??ek")
worldmap_addDesc("briefcase", "fr", "La Valise-Message", "Maison Poisson")
worldmap_addDesc("briefcase", "de", "Die Nachricht in der Aktentasche", "Fischhaus")
worldmap_addDesc("briefcase", "it", "Messaggio nella valigetta", "La Casa dei Pesci")
worldmap_addDesc("briefcase", "pl", "Wiadomo???? z walizki", "Rybi domek")
worldmap_addDesc("briefcase", "es", "Mensaje de un Malet??n", "Casa Pez")
worldmap_addDesc("briefcase", "nl", "Het bericht in het koffertje", "Vissenhuis")
worldmap_addDesc("briefcase", "bg", "Събщение в куфарче", "Дома на рибките")
worldmap_addDesc("briefcase", "sv", "Portf??ljmeddelandet", "Fiskhuset")
worldmap_addDesc("briefcase", "sl", "Sporo??ilo v kov??ku", "Ribja hi??a")
worldmap_addDesc("briefcase", "pt_BR", "Mensagem na Maleta", "Peixaria")
worldmap_addDesc("briefcase", "ru", "Сообщение в портфеле", "Рыбий дом")

worldmap_addDesc("cellar", "en", "Rehearsal in Cellar", "Fish House")
worldmap_addDesc("cellar", "cs", "Zkou??ka ve sklep??", "Ryb?? dome??ek")
worldmap_addDesc("cellar", "fr", "R??p??tition dans la cave", "Maison Poisson")
worldmap_addDesc("cellar", "de", "Die Probe im Keller", "Fischhaus")
worldmap_addDesc("cellar", "it", "Prove in cantina", "La Casa dei Pesci")
worldmap_addDesc("cellar", "pl", "??wiczenia w piwnicy", "Rybi domek")
worldmap_addDesc("cellar", "es", "Ensayo en el S??tano", "Casa Pez")
worldmap_addDesc("cellar", "nl", "De oefening in de kelder", "Vissenhuis")
worldmap_addDesc("cellar", "bg", "Упражнение в мазето", "Дома на рибките")
worldmap_addDesc("cellar", "sv", "Repetition i k??llaren", "Fiskhuset")
worldmap_addDesc("cellar", "sl", "Generalka v kleti", "Ribja hi??a")
worldmap_addDesc("cellar", "pt_BR", "Ensaio no Por??o", "Peixaria")
worldmap_addDesc("cellar", "ru", "Репетиция в подвале", "Рыбий дом")

worldmap_addDesc("library", "en", "Library Flotsam", "Fish House")
worldmap_addDesc("library", "cs", "Co zbylo z knihovny", "Ryb?? dome??ek")
worldmap_addDesc("library", "fr", "La biblioth??que", "Maison Poisson")
worldmap_addDesc("library", "de", "Bibliothek Strandgut", "Fischhaus")
worldmap_addDesc("library", "it", "Relitto di biblioteca", "La Casa dei Pesci")
worldmap_addDesc("library", "pl", "Wrak w bibliotece", "Rybi domek")
worldmap_addDesc("library", "es", "La Biblioteca", "Casa Pez")
worldmap_addDesc("library", "nl", "Strandjutterbiblioteek", "Vissenhuis")
worldmap_addDesc("library", "bg", "Потъналата библиотека", "Дома на рибките")
worldmap_addDesc("library", "sv", "Vrakgods i biblioteket", "Fiskhuset")
worldmap_addDesc("library", "pt_BR", "A Biblioteca", "Peixaria")
worldmap_addDesc("library", "ru", "Заброшенная библиотека", "Рыбий дом")

worldmap_addDesc("stairs", "en", "Plants on the Stairs", "Fish House")
worldmap_addDesc("stairs", "cs", "Zele?? na schodi??ti", "Ryb?? dome??ek")
worldmap_addDesc("stairs", "fr", "Des plantes dans les escaliers", "Maison Poisson")
worldmap_addDesc("stairs", "de", "Pflanzen auf der Treppe", "Fischhaus")
worldmap_addDesc("stairs", "it", "Piante sulle scale", "La Casa dei Pesci")
worldmap_addDesc("stairs", "pl", "Kwiatek na schodach", "Rybi domek")
worldmap_addDesc("stairs", "es", "Plantas en las Escaleras", "Casa Pez")
worldmap_addDesc("stairs", "nl", "Planten op de trap", "Vissenhuis")
worldmap_addDesc("stairs", "bg", "Цветя на стълбите", "Дома на рибките")
worldmap_addDesc("stairs", "sv", "Krukv??xten i trappan", "Fiskhuset")
worldmap_addDesc("stairs", "sl", "Zelenje na stopnicah", "Ribja hi??a")
worldmap_addDesc("stairs", "pt_BR", "Plantas nas Escadas", "Peixaria")
worldmap_addDesc("stairs", "ru", "Расстояние в ступеньку", "Рыбий дом")

worldmap_addDesc("broom", "en", "A Mess in the Boiler Room", "Fish House")
worldmap_addDesc("broom", "cs", "Nepo????dek v koteln??", "Ryb?? dome??ek")
worldmap_addDesc("broom", "fr", "R??union dans la chaudi??re", "Maison Poisson")
worldmap_addDesc("broom", "de", "Unordnung im Kesselraum", "Fischhaus")
worldmap_addDesc("broom", "it", "Casino in sala caldaia", "La Casa dei Pesci")
worldmap_addDesc("broom", "pl", "Ba??agan w kot??owni", "Rybi domek")
worldmap_addDesc("broom", "es", "Un Desorden en la Caldera", "Casa Pez")
worldmap_addDesc("broom", "nl", "Rommel in het boilerhok", "Vissenhuis")
worldmap_addDesc("broom", "bg", "Бъркотия в котелното", "Дома на рибките")
worldmap_addDesc("broom", "sv", "Oreda i pannrummet", "Fiskhuset")
worldmap_addDesc("broom", "sl", "Zmeda v kotlovnici", "Ribja hi??a")
worldmap_addDesc("broom", "pt_BR", "Bagun??a na Caldeira", "Peixaria")
worldmap_addDesc("broom", "ru", "Беспорядок в катальне", "Рыбий дом")

worldmap_addDesc("reef", "en", "Under the Reef", "Fish House")
worldmap_addDesc("reef", "cs", "Pod ??tesem", "Ryb?? dome??ek")
worldmap_addDesc("reef", "fr", "Sous le r??cif", "Maison Poisson")
worldmap_addDesc("reef", "de", "Unter dem Riff", "Fischhaus")
worldmap_addDesc("reef", "it", "Sotto la scogliera", "La Casa dei Pesci")
worldmap_addDesc("reef", "pl", "Pod raf??", "Rybi domek")
worldmap_addDesc("reef", "es", "Bajo el Arrecife", "Casa Pez")
worldmap_addDesc("reef", "nl", "Onder het rif", "Vissenhuis")
worldmap_addDesc("reef", "bg", "Под рифа", "Дома на рибките")
worldmap_addDesc("reef", "sv", "Under revet", "Fiskhuset")
worldmap_addDesc("reef", "sl", "Pod grebenom", "Ribja Hi??a")
worldmap_addDesc("reef", "pt_BR", "Abaixo do Recife", "Peixaria")
worldmap_addDesc("reef", "ru", "Под рифом", "Рыбий дом")

worldmap_addDesc("wc", "en", "Closed in the Closet", "Fish House")
worldmap_addDesc("wc", "cs", "Zam??eni na WC", "Ryb?? dome??ek")
worldmap_addDesc("wc", "fr", "Bloqu??s dans les toilettes", "Maison Poisson")
worldmap_addDesc("wc", "de", "Eingeschlossen auf Toilette", "Fischhaus")
worldmap_addDesc("wc", "it", "Rinchiusi in bagno", "La Casa dei Pesci")
worldmap_addDesc("wc", "pl", "Zamkni??ci w klozecie", "Rybi domek")
worldmap_addDesc("wc", "es", "Encerrado en el W.C.", "Casa Pez")
worldmap_addDesc("wc", "nl", "Opgesloten op de wc", "Vissenhuis")
worldmap_addDesc("wc", "bg", "Затворени в клозета", "Дома на рибките")
worldmap_addDesc("wc", "sv", "Inl??st i garderoben", "Fiskhuset")
worldmap_addDesc("wc", "sl", "Zaprti na strani????u", "Ribja hi??a")
worldmap_addDesc("wc", "pt_BR", "Trancado no Banheiro", "Peixaria")
worldmap_addDesc("wc", "ru", "Закрыто в туалете", "Рыбий дом")

worldmap_addDesc("submarine", "en", "Drowned Submarine", "Ship Wrecks")
worldmap_addDesc("submarine", "cs", "Utonul?? ponorka", "Vrakovi??t??")
worldmap_addDesc("submarine", "fr", "Le sous-marin englouti", "Les ??paves")
worldmap_addDesc("submarine", "de", "Versunkenes U-Boot", "Schiffswracks")
worldmap_addDesc("submarine", "it", "Il sottomarino annegato", "Navi fracassate")
worldmap_addDesc("submarine", "pl", "Zatopiona ????d?? podwodna", "Cmentarzysko statk??w")
worldmap_addDesc("submarine", "es", "Submarino Ahogado", "Ruinas del Barco")
worldmap_addDesc("submarine", "nl", "De gezonken duikboot", "Scheepswrakken")
worldmap_addDesc("submarine", "bg", "Потъналата подводница", "Корабни останки")
worldmap_addDesc("submarine", "sv", "Den sjunkna ub??ten", "Skeppsvrak")
worldmap_addDesc("submarine", "sl", "Potopljena podmornica", "Ladijske razbitine")
worldmap_addDesc("submarine", "pt_BR", "Naufr??gio do Submarino", "Destro??os do Navio")
worldmap_addDesc("submarine", "ru", "Тонуть на субмарине", "Кораблекрушение")

worldmap_addDesc("party1", "en", "Picnic Boat", "Ship Wrecks")
worldmap_addDesc("party1", "cs", "V??letn?? lo??", "Vrakovi??t??")
worldmap_addDesc("party1", "fr", "le bateau pique-nique", "Les ??paves")
worldmap_addDesc("party1", "de", "Picknickboot", "Schiffswracks")
worldmap_addDesc("party1", "it", "Pic-nic in barca", "Navi fracassate")
worldmap_addDesc("party1", "pl", "????d?? wycieczkowa", "Cmentarzysko statk??w")
worldmap_addDesc("party1", "es", "Bote Picnic", "Ruinas del Barco")
worldmap_addDesc("party1", "nl", "Picknickboot", "Scheepswrakken")
worldmap_addDesc("party1", "bg", "Лодка за пикник", "Корабни останки")
worldmap_addDesc("party1", "sv", "Picknickb??ten", "Skeppsvrak")
worldmap_addDesc("party1", "sl", "Ladja za piknik", "Ladijske razbitine")
worldmap_addDesc("party1", "pt_BR", "Pique-nique no Barco", "Destro??os do Navio")
worldmap_addDesc("party1", "ru", "Пикник на лодке", "Кораблекрушение")

worldmap_addDesc("elk", "en", "Great War", "Ship Wrecks")
worldmap_addDesc("elk", "cs", "Velk?? vlasteneck?? v??lka", "Vrakovi??t??")
worldmap_addDesc("elk", "fr", "La grande guerre", "Les ??paves")
worldmap_addDesc("elk", "de", "Erster Weltkrieg", "Schiffswracks")
worldmap_addDesc("elk", "it", "La Grande Guerra", "Navi fracassate")
worldmap_addDesc("elk", "pl", "Wojna ??wiatowa", "Cmentarzysko statk??w")
worldmap_addDesc("elk", "es", "Gran Guerra", "Ruinas del Barco")
worldmap_addDesc("elk", "nl", "De Eerste Wereldoorlog", "Scheepswrakken")
worldmap_addDesc("elk", "bg", "Световната война", "Корабни останки")
worldmap_addDesc("elk", "sv", "V??rldskriget", "Skeppsvrak")
worldmap_addDesc("elk", "sl", "Velika vojna", "Ladijske razbitine")
worldmap_addDesc("elk", "pt_BR", "A Grande Guerra", "Destro??os do Navio")
worldmap_addDesc("elk", "ru", "Отличная война", "Кораблекрушение")

worldmap_addDesc("wreck", "en", "The Ship of Captain Silver", "Ship Wrecks")
worldmap_addDesc("wreck", "cs", "Lo?? kapit??na Silvera", "Vrakovi??t??")
worldmap_addDesc("wreck", "fr", "Le navire du Capitaine Silver", "Les ??paves")
worldmap_addDesc("wreck", "de", "Das Schiff von Kapit??n Silver", "Schiffswracks")
worldmap_addDesc("wreck", "it", "La nave di Capitan Silver", "Navi fracassate")
worldmap_addDesc("wreck", "pl", "Statek Kapitana Silvera", "Cmentarzysko statk??w")
worldmap_addDesc("wreck", "es", "El Barco del Capit??n Silver", "Ruinas del Barco")
worldmap_addDesc("wreck", "nl", "Het schip van Kapitein Silver", "Scheepswrakken")
worldmap_addDesc("wreck", "bg", "Корабът на капитан Силвър", "Корабни останки")
worldmap_addDesc("wreck", "sv", "Kapten Silvers skepp", "Skeppsvrak")
worldmap_addDesc("wreck", "sl", "Ladja Kapitana Srebra", "Ladijske razbitine")
worldmap_addDesc("wreck", "pt_BR", "O Navio do Capit??o Silver", "Destro??os do Navio")
worldmap_addDesc("wreck", "ru", "На корабле капитана Сильвира", "Кораблекрушение")

worldmap_addDesc("viking1", "en", "The Last Voyage", "Ship Wrecks")
worldmap_addDesc("viking1", "cs", "Posledn?? plavba", "Vrakovi??t??")
worldmap_addDesc("viking1", "fr", "Le dernier voyage", "Les ??paves")
worldmap_addDesc("viking1", "de", "Die letzte Reise", "Schiffswracks")
worldmap_addDesc("viking1", "it", "L'ultimo viaggio", "Navi fracassate")
worldmap_addDesc("viking1", "pl", "Ostatnia podr????", "Cmentarzysko statk??w")
worldmap_addDesc("viking1", "es", "El Ultimo Viaje", "Ruinas del Barco")
worldmap_addDesc("viking1", "nl", "De laatste reis", "Scheepswrakken")
worldmap_addDesc("viking1", "bg", "Последното пътешествие", "Корабни останки")
worldmap_addDesc("viking1", "sv", "Den sista f??rden", "Skeppsvrak")
worldmap_addDesc("viking1", "sl", "Zadnje potovanje", "Ladijske razbitine")
worldmap_addDesc("viking1", "pt_BR", "A ??ltima Viagem", "Destro??os do Navio")
worldmap_addDesc("viking1", "ru", "Последнее плаванье", "Кораблекрушение")

worldmap_addDesc("airplane", "en", "Altitude: Minus 9000 Feet", "Ship Wrecks")
worldmap_addDesc("airplane", "cs", "V????ka: -9000 stop", "Vrakovi??t??")
worldmap_addDesc("airplane", "fr", "Altitude: moins 9000 pieds", "Les ??paves")
worldmap_addDesc("airplane", "de", "H??he: Minus 3000 Meter", "Schiffswracks")
worldmap_addDesc("airplane", "it", "Altitudine: meno 9000 piedi", "Navi fracassate")
worldmap_addDesc("airplane", "pl", "Wysoko????: minus 9000 st??p", "Cmentarzysko statk??w")
worldmap_addDesc("airplane", "es", "Altitud: Bajo 3000 Metros", "Ruinas del Barco")
worldmap_addDesc("airplane", "nl", "Hoogte: min 3000 meter", "Scheepswrakken")
worldmap_addDesc("airplane", "bg", "Височина: минус 3000 метра", "Корабни останки")
worldmap_addDesc("airplane", "sv", "Altitud: minus 9000 fot", "Skeppsvrak")
worldmap_addDesc("airplane", "sl", "Nadmorska vi??ina: -3000 metrov", "Ladijske razbitine")
worldmap_addDesc("airplane", "pt_BR", "Altitude: -2.740 metros", "Destro??os do Navio")
worldmap_addDesc("airplane", "ru", "Высота над морем: -3000 метров", "Кораблекрушение")

worldmap_addDesc("bathyscaph", "en", "Bathyscaph", "Ship Wrecks")
worldmap_addDesc("bathyscaph", "cs", "Batyskaf", "Vrakovi??t??")
worldmap_addDesc("bathyscaph", "fr", "Bathyscaphe", "Les ??paves")
worldmap_addDesc("bathyscaph", "de", "Tauchboot", "Schiffswracks")
worldmap_addDesc("bathyscaph", "it", "Batiscafo", "Navi fracassate")
worldmap_addDesc("bathyscaph", "pl", "Batyskaf", "Cmentarzysko statk??w")
worldmap_addDesc("bathyscaph", "es", "Batiscafo", "Ruinas del Barco")
worldmap_addDesc("bathyscaph", "nl", "Bathyscaaf", "Scheepswrakken")
worldmap_addDesc("bathyscaph", "bg", "Батискаф", "Корабни останки")
worldmap_addDesc("bathyscaph", "sv", "Batyskaf", "Skeppsvrak")
worldmap_addDesc("bathyscaph", "sl", "Batiskaf", "Ladijske razbitine")
worldmap_addDesc("bathyscaph", "pt_BR", "Submerso", "Destro??os do Navio")
worldmap_addDesc("bathyscaph", "en", "Батискаф", "Кораблекрушение")

worldmap_addDesc("tank", "en", "Amphibious Tank", "Ship Wrecks")
worldmap_addDesc("tank", "cs", "Oboj??iveln?? tank", "Vrakovi??t??")
worldmap_addDesc("tank", "fr", "Le char amphibie", "Les ??paves")
worldmap_addDesc("tank", "de", "Schwimmpanzer", "Schiffswracks")
worldmap_addDesc("tank", "it", "Carro anfibio", "Navi fracassate")
worldmap_addDesc("tank", "pl", "Amfibia", "Cmentarzysko statk??w")
worldmap_addDesc("tank", "es", "Tanque Anfibio", "Ruinas del Barco")
worldmap_addDesc("tank", "nl", "Amfibievoertuig", "Scheepswrakken")
worldmap_addDesc("tank", "bg", "Танкът - амфибия", "Корабни останки")
worldmap_addDesc("tank", "sv", "Amfibietank", "Skeppsvrak")
worldmap_addDesc("tank", "sl", "Amfibijski tank", "Ladijske razbitine")
worldmap_addDesc("tank", "pt_BR", "Tanque Anf??bio", "Destro??os do Navio")
worldmap_addDesc("tank", "ru", "Танк амфибия", "Кораблекрушение")

worldmap_addDesc("viking2", "en", "Eight Vikings in a Boat", "Ship Wrecks")
worldmap_addDesc("viking2", "cs", "Osm viking?? a pes", "Vrakovi??t??")
worldmap_addDesc("viking2", "fr", "Huit vikings dans un bateau", "Les ??paves")
worldmap_addDesc("viking2", "de", "Acht Wikinger in einem Boot", "Schiffswracks")
worldmap_addDesc("viking2", "it", "Otto vichinghi in una barca", "Navi fracassate")
worldmap_addDesc("viking2", "pl", "O??miu wiking??w w ??odzi", "Cmentarzysko statk??w")
worldmap_addDesc("viking2", "es", "Ocho Vikingos en un Bote", "Ruinas del Barco")
worldmap_addDesc("viking2", "nl", "Acht vikingen in een boot", "Scheepswrakken")
worldmap_addDesc("viking2", "bg", "Осем викинки в една лодка", "Корабни останки")
worldmap_addDesc("viking2", "sv", "??tta vikingar i en b??t", "Skeppsvrak")
worldmap_addDesc("viking2", "sl", "Osem vikingov v ??olnu", "Ladijske razbitine")
worldmap_addDesc("viking2", "pt_BR", "Oito Vikings em um Navio", "Destro??os do Navio")
worldmap_addDesc("viking2", "ru", "Восемь викингов в одной лодке", "Кораблекрушение")

worldmap_addDesc("party2", "en", "Return from the Party", "Ship Wrecks")
worldmap_addDesc("party2", "cs", "N??vrat z v??letu", "Vrakovi??t??")
worldmap_addDesc("party2", "fr", "Retour de la f??te", "Les ??paves")
worldmap_addDesc("party2", "de", "R??ckkehr von der Feier", "Schiffswracks")
worldmap_addDesc("party2", "it", "Ritorno dalla festa", "Navi fracassate")
worldmap_addDesc("party2", "pl", "Powr??t z imprezy", "Cmentarzysko statk??w")
worldmap_addDesc("party2", "es", "Regreso de la Fiesta", "Ruinas del Barco")
worldmap_addDesc("party2", "nl", "Terugkeer van het feest", "Scheepswrakken")
worldmap_addDesc("party2", "bg", "Завръщане от партито", "Корабни останки")
worldmap_addDesc("party2", "sv", "Hem efter festen", "Skeppsvrak")
worldmap_addDesc("party2", "sl", "Vrnitev z zabave", "Ladijske razbitine")
worldmap_addDesc("party2", "pt_BR", "Retorno da Festa", "Destro??os do Navio")
worldmap_addDesc("party2", "ru", "Возвращение с вечеринки", "Кораблекрушение")

worldmap_addDesc("gods", "en", "The Gods Must Be Mad", "Ship Wrecks")
worldmap_addDesc("gods", "cs", "Bohov?? mus?? b??t ????len??", "Vrakovi??t??")
worldmap_addDesc("gods", "fr", "Les dieux doivent ??tre fou", "Les ??paves")
worldmap_addDesc("gods", "de", "Die G??tter m??ssen verr??ckt sein", "Schiffswracks")
worldmap_addDesc("gods", "it", "Gli Dei devono essere impazziti", "Navi fracassate")
worldmap_addDesc("gods", "pl", "Bogowie musz?? by?? szaleni", "Cmentarzysko statk??w")
worldmap_addDesc("gods", "es", "Los Dioses Deben de Estar Locos", "Ruinas del Barco")
worldmap_addDesc("gods", "nl", "De goden zijn gek", "Scheepswrakken")
worldmap_addDesc("gods", "bg", "Боговете сигурно са полудели", "Корабни останки")
worldmap_addDesc("gods", "sv", "Gudarna m??ste vara tokiga", "Skeppsvrak")
worldmap_addDesc("gods", "sl", "Bogovi morajo biti noriu", "Ladijske razbitine")
worldmap_addDesc("gods", "pt_BR", "Os Deuses devem estar loucos", "Destro??os do Navio")
worldmap_addDesc("gods", "ru", "Наверное боги безумны", "Кораблекрушение")

worldmap_addDesc("elevator1", "en", "House with an Elevator", "City In the Deep")
worldmap_addDesc("elevator1", "cs", "D??m s v??tahem", "M??sto v hlubin??ch")
worldmap_addDesc("elevator1", "fr", "Maison avec ascenseur", "Cit??e des profondeurs")
worldmap_addDesc("elevator1", "de", "Haus mit einem Fahrstuhl", "Stadt in der Tiefe")
worldmap_addDesc("elevator1", "it", "Casa con ascensore", "Citt?? profonda")
worldmap_addDesc("elevator1", "pl", "Dom z wind??", "Miasto w g????binach")
worldmap_addDesc("elevator1", "es", "Casa con Ascensor", "Ciudad en lo Profundo")
worldmap_addDesc("elevator1", "nl", "Huis met een lift", "De verzonken stad")
worldmap_addDesc("elevator1", "bg", "Къща с асансьор", "Потъналият град")
worldmap_addDesc("elevator1", "sv", "Hus med en hiss", "Staden i djupet")
worldmap_addDesc("elevator1", "sl", "Hi??a z dvigalom", "Mesto v Globini")
worldmap_addDesc("elevator1", "pt_BR", "A Casa do Elevador", "Destro??os do Navio")
worldmap_addDesc("elevator1", "ru", "Лифт в доме", "Глубоководный город")

worldmap_addDesc("city", "en", "Welcome To Our City", "City In the Deep")
worldmap_addDesc("city", "cs", "V??tejte ve m??st??!", "M??sto v hlubin??ch")
worldmap_addDesc("city", "fr", "Bienvenue dans notre cit??", "Cit??e des profondeurs")
worldmap_addDesc("city", "de", "Willkommen in unserer Stadt", "Stadt in der Tiefe")
worldmap_addDesc("city", "it", "Benvenuti nella nostra citt??", "Citt?? profonda")
worldmap_addDesc("city", "pl", "Witajcie w naszym mie??cie", "Miasto w g????binach")
worldmap_addDesc("city", "es", "Bienvenido a nuestra Ciudad", "Ciudad en lo Profundo")
worldmap_addDesc("city", "nl", "Welkom in onze stad", "De verzonken stad")
worldmap_addDesc("city", "sv", "V??lkommen till v??r stad", "Staden i djupet")
worldmap_addDesc("city", "sl", "Dobrodo??li v na??em mestu", "Mesto v Globini")
worldmap_addDesc("city", "pt_BR", "Bem vindo ?? Nossa Cidade", "A Cidade Profunda")
worldmap_addDesc("city", "ru", "Добро пожаловать в город", "Глубоководный город")

worldmap_addDesc("ufo", "en", "Independence Day", "City In the Deep")
worldmap_addDesc("ufo", "cs", "Den nez??vislosti", "M??sto v hlubin??ch")
worldmap_addDesc("ufo", "fr", "Jour d'ind??pendance", "Cit??e des profondeurs")
worldmap_addDesc("ufo", "de", "Unabh??ngigkeitstag", "Stadt in der Tiefe")
worldmap_addDesc("ufo", "it", "Independence Day", "Citt?? profonda")
worldmap_addDesc("ufo", "pl", "Dzie?? Niepodleg??o??ci", "Miasto w g??ebinach")
worldmap_addDesc("ufo", "es", "D??a de la Independencia", "Ciudad en lo Profundo")
worldmap_addDesc("ufo", "nl", "Independence Day", "De verzonken stad")
worldmap_addDesc("ufo", "bg", "Денят на независимостта", "Потъналият град")
worldmap_addDesc("ufo", "sv", "Sj??lvst??ndighetsdagen", "Staden i djupet")
worldmap_addDesc("ufo", "sl", "Dan neodvisnosti", "Mesto v Globini")
worldmap_addDesc("ufo", "pt_BR", "Dia da Independ??ncia", "A Cidade Profunda")
worldmap_addDesc("ufo", "ru", "День независимости", "Глубоководный город")

worldmap_addDesc("columns", "en", "The Columns", "City In the Deep")
worldmap_addDesc("columns", "cs", "Na kolon??d??", "M??sto v hlubin??ch")
worldmap_addDesc("columns", "fr", "Les colonnes", "Cit??e des profondeurs")
worldmap_addDesc("columns", "de", "Die S??ulen", "Stadt in der Tiefe")
worldmap_addDesc("columns", "it", "Le colonne", "Citt?? profonda")
worldmap_addDesc("columns", "pl", "Kolumny", "Miasto w g????binach")
worldmap_addDesc("columns", "es", "Las Columnas", "Ciudad en lo Profundo")
worldmap_addDesc("columns", "nl", "De pilaren", "De verzonken stad")
worldmap_addDesc("columns", "bg", "Колоните", "Потъналият град")
worldmap_addDesc("columns", "sv", "Pelarna", "Staden i djupet")
worldmap_addDesc("columns", "pt_BR", "As Colunas", "A Cidade Profunda")
worldmap_addDesc("columns", "ru", "Колонны", "Глубоководный город")

worldmap_addDesc("pavement", "en", "Uneven Pavement", "City In the Deep")
worldmap_addDesc("pavement", "cs", "Nerovn?? dla??ba", "M??sto v hlubin??ch")
worldmap_addDesc("pavement", "fr", "Chauss??e ab??m??e", "Cit??e des profondeurs")
worldmap_addDesc("pavement", "de", "Unebener B??rgersteig", "Stadt in der Tiefe")
worldmap_addDesc("pavement", "it", "Pavimento sconnesso", "Citt?? profonda")
worldmap_addDesc("pavement", "pl", "Nier??wny chodnik", "Miasto w g????binach")
worldmap_addDesc("pavement", "es", "Pavimento en Desnivel", "Ciudad en lo Profundo")
worldmap_addDesc("pavement", "nl", "Hobbelig trottoir", "De verzonken stad")
worldmap_addDesc("pavement", "bg", "Неравен паваж", "Потъналият град")
worldmap_addDesc("pavement", "sv", "Oj??mn trottoar", "Staden i djupet")
worldmap_addDesc("pavement", "pt_BR", "Pavimento Irregular", "A Cidade Profunda")
worldmap_addDesc("pavement", "ru", "Неправильный художник", "Глубоководный город")

worldmap_addDesc("pyramid", "en", "Mr. Cheops??? House", "City In the Deep")
worldmap_addDesc("pyramid", "cs", "D??m pana Cheopse", "M??sto v hlubin??ch")
worldmap_addDesc("pyramid", "fr", "Chez Mr. Kheops", "Cit??e des profondeurs")
worldmap_addDesc("pyramid", "de", "Das Haus des Herrn Cheops", "Stadt in der Tiefe")
worldmap_addDesc("pyramid", "it", "La casa del Sig. Cheope", "Citt?? profonda")
worldmap_addDesc("pyramid", "pl", "Dom pana Cheopsa", "Miasto w g????binach")
worldmap_addDesc("pyramid", "es", "La Casa de Mr. Cheops", "Ciudad en lo Profundo")
worldmap_addDesc("pyramid", "nl", "Het huis van Cheops", "De verzonken stad")
worldmap_addDesc("pyramid", "bg", "Къщата на г-н Хеопс", "Потъналият град")
worldmap_addDesc("pyramid", "sv", "Cheops hus", "Staden i djupet")
worldmap_addDesc("pyramid", "pt_BR", "A Casa do Sr. Cheops", "A Cidade Profunda")
worldmap_addDesc("pyramid", "ru", "Дом товарища Хеопса", "Глубоководный город")

worldmap_addDesc("music", "en", "A Bit of Music", "City In the Deep")
worldmap_addDesc("music", "cs", "Pro pot????en??", "M??sto v hlubin??ch")
worldmap_addDesc("music", "fr", "Une note de musique", "Cit??e des profondeurs")
worldmap_addDesc("music", "de", "Ein bisschen Musik", "Stadt in der Tiefe")
worldmap_addDesc("music", "it", "Un po' di musica", "Citt?? profonda")
worldmap_addDesc("music", "pl", "Nieco muzyki", "Miasto w g??ebinach")
worldmap_addDesc("music", "es", "Un Poco de M??sica", "Ciudad en lo Profundo")
worldmap_addDesc("music", "nl", "Een beetje muziek", "De verzonken stad")
worldmap_addDesc("music", "bg", "Малко музика", "Потъналият град")
worldmap_addDesc("music", "sv", "Lite musik", "Staden i djupet")
worldmap_addDesc("music", "pt_BR", "Um Pouco de M??sica", "A Cidade Profunda")
worldmap_addDesc("music", "ru", "Небольшая музыка", "Глубоководный город")

worldmap_addDesc("crabshow", "en", "Crab Freak Show", "City In the Deep")
worldmap_addDesc("crabshow", "cs", "Panoptikum kor??????", "M??sto v hlubin??ch")
worldmap_addDesc("crabshow", "fr", "La danse des crabes", "Cit??e des profondeurs")
worldmap_addDesc("crabshow", "de", "Krabben-Monster-Schau", "Stadt in der Tiefe")
worldmap_addDesc("crabshow", "it", "Granchi da baraccone", "Citt?? profonda")
worldmap_addDesc("crabshow", "pl", "Krabie muzeum osobliwo??ci", "Miasto w g????binach")
worldmap_addDesc("crabshow", "es", "Loco Show del Cangrejo", "Ciudad en lo Profundo")
worldmap_addDesc("crabshow", "nl", "Krabbenrariteitenkabinet", "De verzonken stad")
worldmap_addDesc("crabshow", "bg", "Шоуто на лудия рак", "Потъналият град")
worldmap_addDesc("crabshow", "sv", "Krabbmonstershow", "Staden i djupet")
worldmap_addDesc("crabshow", "pt_BR", "Show Maluco do Caranguejo", "A Cidade Profunda")
worldmap_addDesc("crabshow", "ru", "Причуда краба", "Глубоководный город")

worldmap_addDesc("elevator2", "en", "Another elevator", "City In the Deep")
worldmap_addDesc("elevator2", "cs", "Druh?? d??m s v??tahem", "M??sto v hlubin??ch")
worldmap_addDesc("elevator2", "fr", "Un autre ascenseur", "Cit??e des profondeurs")
worldmap_addDesc("elevator2", "de", "Noch ein Fahrstuhl", "Stadt in der Tiefe")
worldmap_addDesc("elevator2", "it", "Un altro ascensore", "Citt?? profonda")
worldmap_addDesc("elevator2", "pl", "Jeszcze jedna winda", "Miasto w g????binach")
worldmap_addDesc("elevator2", "es", "Otro Ascensor", "Ciudad en lo Profundo")
worldmap_addDesc("elevator2", "nl", "Nog een lift", "De verzonken stad")
worldmap_addDesc("elevator2", "bg", "Още един асаньор", "Потъналият град")
worldmap_addDesc("elevator2", "sv", "??nnu en hiss", "Staden i djupet")
worldmap_addDesc("elevator2", "pt_BR", "Outro Elevador", "A Cidade Profunda")
worldmap_addDesc("elevator2", "ru", "Очередной лифт", "Глубоководный город")

worldmap_addDesc("atlantis", "en", "And How It Was", "City In the Deep")
worldmap_addDesc("atlantis", "cs", "Tak takhle to bylo", "M??sto v hlubin??ch")
worldmap_addDesc("atlantis", "fr", "Comment ce fut",  "Cit??e des profondeurs")
worldmap_addDesc("atlantis", "de", "Wie es war",  "Stadt in der Tiefe")
worldmap_addDesc("atlantis", "it", "L'arcano svelato", "Citt?? profonda")
worldmap_addDesc("atlantis", "pl", "Tak to by??o", "Miasto w g????binach")
worldmap_addDesc("atlantis", "es", "Y C??mo Era",  "Ciudad en lo Profundo")
worldmap_addDesc("atlantis", "nl", "Hoe het zat",  "De verzonken stad")
worldmap_addDesc("atlantis", "bg", "Така беше едно време", "Потъналият град")
worldmap_addDesc("atlantis", "sv", "Som det var", "Staden i djupet")
worldmap_addDesc("atlantis", "pt_BR", "E Como Era", "A Cidade Profunda")
worldmap_addDesc("atlantis", "ru", "Итак что это было", "Глубоководный город")

worldmap_addDesc("corals", "en", "First Bizarre Things", "Coral reef")
worldmap_addDesc("corals", "cs", "Prvn?? bizarnosti", "Kor??lov?? ??tes")
worldmap_addDesc("corals", "fr", "Premi??re chose bizarre", "R??cif de corail")
worldmap_addDesc("corals", "de", "Erste bizarre Dinge", "Korallenriff")
worldmap_addDesc("corals", "it", "Le prime bizzarrie", "Barriera corallina")
worldmap_addDesc("corals", "pl", "Pierwsze dziwy", "Rafa koralowa")
worldmap_addDesc("corals", "es", "Primeras cosas Bizarras", "Arrecife de Coral")
worldmap_addDesc("corals", "nl", "De eerste bizarre dingen", "Koraalrif")
worldmap_addDesc("corals", "bg", "Първите странни неща", "Коралов риф")
worldmap_addDesc("corals", "sv", "F??rsta bisarra saken", "Korallrev")
worldmap_addDesc("corals", "pt_BR", "Primeiras Coisas Bizarras", "Recife de Corais")
worldmap_addDesc("corals", "ru", "Первый безумный предмет", "Коралловый риф")

worldmap_addDesc("labyrinth", "en", "Labyrinth", "Coral reef")
worldmap_addDesc("labyrinth", "cs", "Bludi??t??", "Kor??lov?? ??tes")
worldmap_addDesc("labyrinth", "fr", "Labyrinthe", "R??cif de corail")
worldmap_addDesc("labyrinth", "de", "Labyrinth", "Korallenriff")
worldmap_addDesc("labyrinth", "it", "Labirinto", "Barriera corallina")
worldmap_addDesc("labyrinth", "pl", "Labirynt", "Rafa koralowa")
worldmap_addDesc("labyrinth", "es", "Laberinto", "Arrecife de Coral")
worldmap_addDesc("labyrinth", "nl", "Labyrint", "Koraalrif")
worldmap_addDesc("labyrinth", "bg", "Лабиринт", "Коралов риф")
worldmap_addDesc("labyrinth", "sv", "Labyrinten", "Korallrev")
worldmap_addDesc("labyrinth", "pt_BR", "Labirinto", "Recife de Corais")
worldmap_addDesc("labyrinth", "ru", "Лабиринт", "Коралловый риф")

worldmap_addDesc("imprisoned", "en", "Imprisoned", "Coral reef")
worldmap_addDesc("imprisoned", "cs", "Uv??zn??ni", "Kor??lov?? ??tes")
worldmap_addDesc("imprisoned", "fr", "En prison", "R??cif de corail")
worldmap_addDesc("imprisoned", "de", "Gefangen", "Korallenriff")
worldmap_addDesc("imprisoned", "it", "Imprigionati", "Barriera corallina")
worldmap_addDesc("imprisoned", "pl", "Uwi??zieni", "Rafa koralowa")
worldmap_addDesc("imprisoned", "es", "En Prisi??n", "Arrecife de Coral")
worldmap_addDesc("imprisoned", "nl", "Gevangen", "Koraalrif")
worldmap_addDesc("imprisoned", "bg", "Затворени", "Коралов риф")
worldmap_addDesc("imprisoned", "sv", "F??ngslad", "Korallrev")
worldmap_addDesc("imprisoned", "pt_BR", "Preso", "Recife de Corais")
worldmap_addDesc("imprisoned", "ru", "Заключенный", "Коралловый риф")

worldmap_addDesc("society", "en", "Closed Society", "Coral reef")
worldmap_addDesc("society", "cs", "Uzav??en?? spole??nost", "Kor??lov?? ??tes")
worldmap_addDesc("society", "fr", "Soci??t?? ferm??e", "R??cif de corail")
worldmap_addDesc("society", "de", "Geschlossene Gesellschaft", "Korallenriff")
worldmap_addDesc("society", "it", "Societ?? chiusa", "Barriera corallina")
worldmap_addDesc("society", "pl", "Zamkni??ta spo??eczno????", "Rafa koralowa")
worldmap_addDesc("society", "es", "Sociedad Cerrada", "Arrecife de Coral")
worldmap_addDesc("society", "nl", "Besloten gezelschap", "Koraalrif")
worldmap_addDesc("society", "bg", "Затворено общество", "Коралов риф")
worldmap_addDesc("society", "sv", "Slutet s??llskap", "Korallrev")
worldmap_addDesc("society", "pt_BR", "Sociedade Fechada", "Recife de Corais")
worldmap_addDesc("society", "ru", "Закрытое общество", "Коралловый риф")

worldmap_addDesc("creatures", "en", "Sleeping Creatures", "Coral reef")
worldmap_addDesc("creatures", "cs", "Sp??c?? tvore??kov??", "Kor??lov?? ??tes")
worldmap_addDesc("creatures", "fr", "Cr??atures dormantes", "R??cif de corail")
worldmap_addDesc("creatures", "de", "Schlafende Wesen", "Korallenriff")
worldmap_addDesc("creatures", "it", "Creature dormienti", "Barriera corallina")
worldmap_addDesc("creatures", "pl", "??pi??ce stworzenia", "Rafa koralowa")
worldmap_addDesc("creatures", "es", "Criaturas Durmientes", "Arrecife de Coral")
worldmap_addDesc("creatures", "nl", "Slapende diertjes", "Koraalrif")
worldmap_addDesc("creatures", "bg", "Спящи създания", "Коралов риф")
worldmap_addDesc("creatures", "sv", "Sovande djur", "Korallrev")
worldmap_addDesc("creatures", "pt_BR", "Criaturas Adormecidas", "Recife de Corais")
worldmap_addDesc("creatures", "ru", "Спящие создания", "Коралловый риф")

worldmap_addDesc("cancan", "en", "Cancan Crabs", "Coral reef")
worldmap_addDesc("cancan", "cs", "Kank??nov?? krab??ci", "Kor??lov?? ??tes")
worldmap_addDesc("cancan", "fr", "Le cancan des crabes", "R??cif de corail")
worldmap_addDesc("cancan", "de", "Cancan-Krabben", "Korallenriff")
worldmap_addDesc("cancan", "it", "Cancan Crabs", "Barriera corallina")
worldmap_addDesc("cancan", "pl", "Kankanowe kraby", "Rafa koralowa")
worldmap_addDesc("cancan", "es", "Cangrejos Cancan", "Arrecife de Coral")
worldmap_addDesc("cancan", "nl", "Cancan-krabben", "Koraalrif")
worldmap_addDesc("cancan", "bg", "Раци кан-кан", "Коралов риф")
worldmap_addDesc("cancan", "sv", "Cancankrabbor", "Korallrev")
worldmap_addDesc("cancan", "pt_BR", "Dan??a do Caranguejo", "Recife de Corais")
worldmap_addDesc("cancan", "ru", "Дикий кан-кан", "Коралловый риф")

worldmap_addDesc("pearls", "en", "One More Pearl; Please!", "Coral reef")
worldmap_addDesc("pearls", "cs", "Je??t?? jednu perli??ku!", "Kor??lov?? ??tes")
worldmap_addDesc("pearls", "fr", "Une perle de plus; s'il vous pla??t !", "R??cif de corail")
worldmap_addDesc("pearls", "de", "Bitte noch eine Perle!", "Korallenriff")
worldmap_addDesc("pearls", "it", "Un'altra perla, per favore!", "Barriera corallina")
worldmap_addDesc("pearls", "pl", "Prosz??, jeszcze jedna per??a!", "Rafa koralowa")
worldmap_addDesc("pearls", "es", "Una Perla M??s; ??Por Favor!", "Arrecife de Coral")
worldmap_addDesc("pearls", "nl", "Nog een parel, alsjeblieft!", "Koraalrif")
worldmap_addDesc("pearls", "bg", "Още една перла. Моля!", "Коралов риф")
worldmap_addDesc("pearls", "sv", "En till p??rla, tack!", "Korallrev")
worldmap_addDesc("pearls", "pt_BR", "Mais uma p??rola; Por Favor!", "Recife de Corais")
worldmap_addDesc("pearls", "ru", "Ещё один перл, пожалуйста!", "Коралловый риф")

worldmap_addDesc("turtle", "en", "Telepathic Devil", "Coral reef")
worldmap_addDesc("turtle", "cs", "Telepatick?? mrcha", "Kor??lov?? ??tes")
worldmap_addDesc("turtle", "fr", "Le diable t??l??pathique", "R??cif de corail")
worldmap_addDesc("turtle", "de", "Telepathischer Teufel", "Korallenriff")
worldmap_addDesc("turtle", "it", "Malvagit?? telepatica", "Barriera corallina")
worldmap_addDesc("turtle", "pl", "Telepatyczny diabe??", "Rafa koralowa")
worldmap_addDesc("turtle", "es", "Diablo Telep??tico", "Arrecife de Coral")
worldmap_addDesc("turtle", "nl", "Telepathische duivel", "Koraalrif")
worldmap_addDesc("turtle", "bg", "Телепатичен дявол", "Коралов риф")
worldmap_addDesc("turtle", "sv", "Telepatisk dj??vul", "Korallrev")
worldmap_addDesc("turtle", "pt_BR", "Dem??nio Telepata", "Recife de Corais")
worldmap_addDesc("turtle", "ru", "Телепатия дьявола", "Коралловый риф")

worldmap_addDesc("computer", "en", "The Deep Server", "Dump")
worldmap_addDesc("computer", "cs", "Hlubinn?? server", "Smeti??t??")
worldmap_addDesc("computer", "fr", "Le serveur des profondeurs", "le d??potoir")
worldmap_addDesc("computer", "de", "Der tiefe Server", "Halde")
worldmap_addDesc("computer", "it", "Il Server Profondo", "Pattumiera")
worldmap_addDesc("computer", "pl", "Serwer g????binowy", "??mietnisko")
worldmap_addDesc("computer", "es", "El Servidor en lo Profundo", "Vertedero")
worldmap_addDesc("computer", "nl", "De diepe server", "Vuilnis")
worldmap_addDesc("computer", "bg", "Дълбокия сървър", "Боклук")
worldmap_addDesc("computer", "sv", "Den djupa servern", "Avfall")
worldmap_addDesc("computer", "pt_BR", "O Servidor Profundo", "Aterro")
worldmap_addDesc("computer", "ru", "Глубоководный сервер", "Глубина")

worldmap_addDesc("noground", "en", "Almost No Wall", "Dump")
worldmap_addDesc("noground", "cs", "Skoro ????dn?? ze??", "Smeti??t??")
worldmap_addDesc("noground", "fr", "Presque pas de mur", "le d??potoir")
worldmap_addDesc("noground", "de", "Fast keine Wand", "Halde")
worldmap_addDesc("noground", "it", "Quasi senza muri", "Pattumiera")
worldmap_addDesc("noground", "pl", "Prawie bez ??cian", "??mietnisko")
worldmap_addDesc("noground", "es", "Casi Ninguna Muralla", "Vertedero")
worldmap_addDesc("noground", "nl", "Bijna geen muur", "Vuilnis")
worldmap_addDesc("noground", "bg", "Почти без стени", "Боклук")
worldmap_addDesc("noground", "sv", "N??stan inga v??ggar", "Avfall")
worldmap_addDesc("noground", "pt_BR", "Quase Sem Muro", "Aterro")
worldmap_addDesc("noground", "ru", "Почти без стен", "Глубина")

worldmap_addDesc("bathroom", "en", "Plumbman???s Refuse", "Dump")
worldmap_addDesc("bathroom", "cs", "Instalat??rsk?? odpad", "Smeti??t??")
worldmap_addDesc("bathroom", "fr", "Le refus du bonhomme de plomb", "le d??potoir")
worldmap_addDesc("bathroom", "de", "Der Abfall des Installateurs", "Halde")
worldmap_addDesc("bathroom", "it", "Gli scarti dell'idraulico", "Pattumiera")
worldmap_addDesc("bathroom", "pl", "Odpadki hydrauliczne", "??mietnisko")
worldmap_addDesc("bathroom", "es", "El Rechazo del Plomero", "Vertedero")
worldmap_addDesc("bathroom", "nl", "Het afval van de loodgieter", "Vuilnis")
worldmap_addDesc("bathroom", "bg", "Отказът на водопроводчика", "Боклук")
worldmap_addDesc("bathroom", "sv", "R??rmokarens avfall", "Avfall")
worldmap_addDesc("bathroom", "pt_BR", "Restos do Encanador", "Aterro")
worldmap_addDesc("bathroom", "ru", "Отказ водопроводчика", "Глубина")

worldmap_addDesc("duckie", "en", "Adventure with Pink Duckie", "Dump")
worldmap_addDesc("duckie", "cs", "Dobrodru??stv?? s kachni??kou", "Smeti??t??")
worldmap_addDesc("duckie", "fr", "Aventure avec le canard rose", "le d??potoir")
worldmap_addDesc("duckie", "de", "Abenteuer mit Rosa Entlein", "Halde")
worldmap_addDesc("duckie", "it", "Avventura con Paperetta Rosa", "Pattumiera")
worldmap_addDesc("duckie", "pl", "Przygoda z r????ow?? kaczuszk??", "??mietnisko")
worldmap_addDesc("duckie", "es", "Aventura con el Patito Rosado", "Vertedero")
worldmap_addDesc("duckie", "nl", "Avontuur met een roze badeendje", "Vuilnis")
worldmap_addDesc("duckie", "bg", "Приключения с розово пате", "Боклук")
worldmap_addDesc("duckie", "sv", "??ventyr med den rosa ankan", "Avfall")
worldmap_addDesc("duckie", "pt_BR", "Aventura com o Patinho Rosa", "Aterro")
worldmap_addDesc("duckie", "ru", "Приключения с розовой пантерой", "Глубина")

worldmap_addDesc("puzzle", "en", "Shredded Stickman", "Dump")
worldmap_addDesc("puzzle", "cs", "Rozst????han?? ??m??ranice", "Smeti??t??")
worldmap_addDesc("puzzle", "fr", "Eparpillement", "le d??potoir")
worldmap_addDesc("puzzle", "de", "Ablenkung", "Halde")
worldmap_addDesc("puzzle", "it", "Omino ingarbugliato", "Pattumiera")
worldmap_addDesc("puzzle", "pl", "Podarty bohomaz", "??mietnisko")
worldmap_addDesc("puzzle", "es", "Dispersi??n", "Vertedero")
worldmap_addDesc("puzzle", "nl", "Verknipt plaatje", "Vuilnis")
worldmap_addDesc("puzzle", "bg", "Накълцания палач", "Боклук")
worldmap_addDesc("puzzle", "sv", "Utspridd croupier", "Avfall")
worldmap_addDesc("puzzle", "pt_BR", "Distra????o", "Aterro")
worldmap_addDesc("puzzle", "ru", "Рубящий палач", "Глубина")

worldmap_addDesc("dump", "en", "Real Chaos", "Dump")
worldmap_addDesc("dump", "cs", "Opravdov?? chaos", "Smeti??t??")
worldmap_addDesc("dump", "fr", "Le vrai chaos", "le d??potoir")
worldmap_addDesc("dump", "de", "Echtes Durcheinander", "Halde")
worldmap_addDesc("dump", "it", "Caos totale", "Pattumiera")
worldmap_addDesc("dump", "pl", "Prawdziwy chaos", "??mietnisko")
worldmap_addDesc("dump", "es", "Caos Real", "Vertedero")
worldmap_addDesc("dump", "nl", "Totale chaos", "Vuilnis")
worldmap_addDesc("dump", "bg", "Истински хаос", "Боклук")
worldmap_addDesc("dump", "sv", "Fullst??ndigt kaos", "Avfall")
worldmap_addDesc("dump", "pt_BR", "Caos Total", "Aterro")
worldmap_addDesc("dump", "ru", "Истинный хаос", "Глубина")

worldmap_addDesc("barrel", "en", "Outraged Greenpeace", "Dump")
worldmap_addDesc("barrel", "cs", "Greenpeace by zu??ili", "Smeti??t??")
worldmap_addDesc("barrel", "fr", "Greenpeace scandalis??", "le d??potoir")
worldmap_addDesc("barrel", "de", "Emp??rtes Greenpeace", "Halde")
worldmap_addDesc("barrel", "it", "Greenpeace oltraggiata", "Pattumiera")
worldmap_addDesc("barrel", "pl", "Obraza Greenpeace", "??mietnisko")
worldmap_addDesc("barrel", "es", "Greenpeace Ultrajado", "Vertedero")
worldmap_addDesc("barrel", "nl", "Boze Greenpeace", "Vuilnis")
worldmap_addDesc("barrel", "bg", "Оскърбен Greenpeace", "Боклук")
worldmap_addDesc("barrel", "sv", "Uppretat Greenpeace", "Avfall")
worldmap_addDesc("barrel", "pt_BR", "Greenpeace Revoltado", "Aterro")
worldmap_addDesc("barrel", "кг", "Обиженный Гринпис", "Глубина")

worldmap_addDesc("cabin1", "en", "The First Mate???s Cabin", "Silver's Ship")
worldmap_addDesc("cabin1", "cs", "Kajuta prvn??ho d??stojn??ka", "Silverova lo??")
worldmap_addDesc("cabin1", "fr", "La cabine du premier matelot", "Le navire de Silver")
worldmap_addDesc("cabin1", "de", "Die Kaj??te des ersten Offiziers", "Silvers Schiff")
worldmap_addDesc("cabin1", "it", "La cabina del primo ufficiale", "La nave di Silver")
worldmap_addDesc("cabin1", "pl", "Kajuta pierwszego mata", "Statek Silvera")
worldmap_addDesc("cabin1", "es", "La Cabina del Primer Oficial", "El Barco de Silver")
worldmap_addDesc("cabin1", "nl", "De hut van de eerste officier", "Het schip van Kapitein Silver")
worldmap_addDesc("cabin1", "bg", "Каютата на първия помощник", "Корабът на Силвър")
worldmap_addDesc("cabin1", "sv", "F??rste officerens hytt", "Silvers skepp")
worldmap_addDesc("cabin1", "pt_BR", "A Cabine do Primeiro Oficial", "O Navio de Silver")
worldmap_addDesc("cabin1", "ru", "Каюта первого помощника", "На корабле Сильвeра")

worldmap_addDesc("snowman", "en", "The Winter Mess Hall", "Silver's Ship")
worldmap_addDesc("snowman", "cs", "Zimn?? j??delna", "Silverova lo??")
worldmap_addDesc("snowman", "fr", "Le salon d'hiver", "Le navire de Silver")
worldmap_addDesc("snowman", "de", "Die Wintermesse", "Silvers Schiff")
worldmap_addDesc("snowman", "it", "Mensa Invernale", "La nave di Silver")
worldmap_addDesc("snowman", "pl", "Zimowa mesa", "Statek Silvera")
worldmap_addDesc("snowman", "es", "El L??o en el Sal??n de Invierno", "El Barco de Silver")
worldmap_addDesc("snowman", "nl", "De winterkajuit", "Het schip van Kapitein Silver")
worldmap_addDesc("snowman", "bg", "Зимна бъркотия", "Корабът на Силвър")
worldmap_addDesc("snowman", "sv", "Vinterm??ssen", "Silvers skepp")
worldmap_addDesc("snowman", "pt_BR", "A Bagun??a no Sal??o de Inverno", "O Navio de Silver")
worldmap_addDesc("snowman", "ru", "Зима в зале", "На корабле Сильвра")

worldmap_addDesc("cannons", "en", "Fire!", "Silver's Ship")
worldmap_addDesc("cannons", "cs", "Pal!", "Silverova lo??")
worldmap_addDesc("cannons", "fr", "Feu !", "Le navire de Silver")
worldmap_addDesc("cannons", "de", "Feuer!", "Silvers Schiff")
worldmap_addDesc("cannons", "it", "Fuoco!", "La nave di Silver")
worldmap_addDesc("cannons", "pl", "Ognia!", "Statek Silvera")
worldmap_addDesc("cannons", "es", "Fuego!", "El Barco de Silver")
worldmap_addDesc("cannons", "nl", "Vuur!", "Het schip van Kapitein Silver")
worldmap_addDesc("cannons", "bg", "Пожар!", "Корабът на Силвър")
worldmap_addDesc("cannons", "sv", "Eld!", "Silvers skepp")
worldmap_addDesc("cannons", "pt_BR", "Fogo!", "O Navio de Silver")
worldmap_addDesc("cannons", "ru", "Пожар!", "На корабле Сильвра")

worldmap_addDesc("kitchen", "en", "Ship Kitchen", "Silver's Ship")
worldmap_addDesc("kitchen", "cs", "Lodn?? kuchyn??", "Silverova lo??")
worldmap_addDesc("kitchen", "fr", "La cuisine du navire", "Le navire de Silver")
worldmap_addDesc("kitchen", "de", "Schiffsk??che", "Silvers Schiff")
worldmap_addDesc("kitchen", "it", "La cucina di bordo", "La nave di Silver")
worldmap_addDesc("kitchen", "pl", "Kuchnia okr??towa", "Statek Silvera")
worldmap_addDesc("kitchen", "es", "Cocina del Barco", "El Barco de Silver")
worldmap_addDesc("kitchen", "nl", "De kombuis", "Het schip van Kapitein Silver")
worldmap_addDesc("kitchen", "bg", "Корабната кухня", "Корабът на Силвър")
worldmap_addDesc("kitchen", "sv", "Skeppsk??ket", "Silvers skepp")
worldmap_addDesc("kitchen", "pt_BR", "A Cozinha do Navio", "O Navio de Silver")
worldmap_addDesc("kitchen", "ru", "Кухня корабля", "На корабле Сильвра")

worldmap_addDesc("cabin2", "en", "Second Mate???s Cabin", "Silver's Ship")
worldmap_addDesc("cabin2", "cs", "Kajuta druh??ho d??stojn??ka", "Silverova lo??")
worldmap_addDesc("cabin2", "fr", "La cabine du second", "Le navire de Silver")
worldmap_addDesc("cabin2", "de", "Die Kaj??te des zweiten Offiziers", "Silvers Schiff")
worldmap_addDesc("cabin2", "it", "La cabina dell'ufficiale in seconda", "La nave di Silver")
worldmap_addDesc("cabin2", "pl", "Kajuta drugiego mata", "Statek Silvera")
worldmap_addDesc("cabin2", "es", "La Cabina del Segundo Oficial", "El Barco de Silver")
worldmap_addDesc("cabin2", "nl", "De hut van de tweede officier", "Het schip van Kapitein Silver")
worldmap_addDesc("cabin2", "bg", "Каютата на втория помощник", "Корабът на Силвър")
worldmap_addDesc("cabin2", "sv", "Andre officerens hytt", "Silvers skepp")
worldmap_addDesc("cabin2", "pt_BR", "A Cabine do Segundo Oficial", "O Navio de Silver")
worldmap_addDesc("cabin2", "ru", "Каюта второго помощника", "На корабле Сильвра")

worldmap_addDesc("captain", "en", "Captain???s Cabin", "Silver's Ship")
worldmap_addDesc("captain", "cs", "Kapit??nova kajuta", "Silverova lo??")
worldmap_addDesc("captain", "fr", "La cabine du Capitaine", "Le navire de Silver")
worldmap_addDesc("captain", "de", "Kapit??nskaj??te", "Silvers Schiff")
worldmap_addDesc("captain", "it", "La cabina del capitano", "La nave di Silver")
worldmap_addDesc("captain", "pl", "Kajuta kapita??ska", "Statek Silvera")
worldmap_addDesc("captain", "es", "La Cabina del Capit??n", "El Barco de Silver")
worldmap_addDesc("captain", "nl", "De hut van de kapitein", "Het schip van Kapitein Silver")
worldmap_addDesc("captain", "bg", "Каютата на капитана", "Корабът на Силвър")
worldmap_addDesc("captain", "sv", "Kaptens hytt", "Silvers skepp")
worldmap_addDesc("captain", "pt_BR", "A Cabine do Capit??o", "O Navio de Silver")
worldmap_addDesc("captain", "ru", "Каюта капитана", "На корабле Сильвра")

worldmap_addDesc("map", "en", "Silver???s Hideout", "Silver's Ship")
worldmap_addDesc("map", "cs", "Silverova tajn?? skr????", "Silverova lo??")
worldmap_addDesc("map", "fr", "La cache de Silver", "Le navire de Silver")
worldmap_addDesc("map", "de", "Silvers Versteck", "Silvers Schiff")
worldmap_addDesc("map", "it", "Il nascondiglio di Silver", "La nave di Silver")
worldmap_addDesc("map", "pl", "Kryj??wka Silvera", "Statek Silvera")
worldmap_addDesc("map", "es", "El Escondite de Silver", "El Barco de Silver")
worldmap_addDesc("map", "nl", "Silvers geheime plekje", "Het schip van Kapitein Silver")
worldmap_addDesc("map", "bg", "Скривалището на Силвър", "Корабът на Силвър")
worldmap_addDesc("map", "sv", "Silvers g??mst??lle", "Silvers skepp")
worldmap_addDesc("map", "pt_BR", "O Esconderijo de Silver", "O Navio de Silver")
worldmap_addDesc("map", "ru", "Сильвер спрятался", "На корабле Сильвра")

worldmap_addDesc("reactor", "en", "Power Plant", "UFO")
worldmap_addDesc("reactor", "cs", "Reaktor", "Ztroskotan?? UFO")
worldmap_addDesc("reactor", "fr", "Centrale ??lectrique", "ovni")
worldmap_addDesc("reactor", "de", "Kraftwerk", "UFO")
worldmap_addDesc("reactor", "it", "Centrale elettrica", "UFO")
worldmap_addDesc("reactor", "pl", "Reaktor", "UFO")
worldmap_addDesc("reactor", "es", "Central El??ctrica", "OVNI")
worldmap_addDesc("reactor", "nl", "Reactor", "Vliegende schotel")
worldmap_addDesc("reactor", "sv", "Reaktor", "UFO")
worldmap_addDesc("reactor", "pt_BR", "Esta????o de For??a", "UFO")
worldmap_addDesc("reactor", "ru", "Электростанция", "НЛО")

worldmap_addDesc("magnet", "en", "Strange Forces", "UFO")
worldmap_addDesc("magnet", "cs", "Nezn??m?? s??ly", "Ztroskotan?? UFO")
worldmap_addDesc("magnet", "fr", "Forces ??tranges", "ovni")
worldmap_addDesc("magnet", "de", "Seltsame Kr??fte", "UFO")
worldmap_addDesc("magnet", "it", "Strane forze", "UFO")
worldmap_addDesc("magnet", "pl", "Nieznane si??y", "UFO")
worldmap_addDesc("magnet", "es", "Fuerzas Extra??as", "OVNI")
worldmap_addDesc("magnet", "nl", "Vreemde krachten", "Vliegende schotel")
worldmap_addDesc("magnet", "bg", "Странни сили", "НЛО")
worldmap_addDesc("magnet", "sv", "Ok??nda krafter", "UFO")
worldmap_addDesc("magnet", "pt_BR", "For??as Estranhas", "UFO")
worldmap_addDesc("magnet", "ru", "Странные силы", "НЛО")

worldmap_addDesc("engine", "en", "Brm... Brm...", "UFO")
worldmap_addDesc("engine", "cs", "Brm brm...", "Ztroskotan?? UFO")
worldmap_addDesc("engine", "fr", "Brm... Brm...", "ovni")
worldmap_addDesc("engine", "de", "Brm... Brm...", "UFO")
worldmap_addDesc("engine", "pl", "Brum... Brum...", "UFO")
worldmap_addDesc("engine", "es", "Brm... Brm...", "OVNI")
worldmap_addDesc("engine", "nl", "Vroem... Vroem...", "Vliegende schotel")
worldmap_addDesc("engine", "bg", "Бърм... Бръм...", "НЛО")
worldmap_addDesc("engine", "sv", "Brum... Brum...", "UFO")
worldmap_addDesc("engine", "pt_BR", "Brm... Brm...", "UFO")
worldmap_addDesc("engine", "ru", "Брм... Брм...", "НЛО")

worldmap_addDesc("steel", "en", "Nothing but steel", "UFO")
worldmap_addDesc("steel", "cs", "Ocel; sam?? ocel", "Ztroskotan?? UFO")
worldmap_addDesc("steel", "fr", "Rien que du m??tal", "ovni")
worldmap_addDesc("steel", "de", "Alles nur Stahl", "UFO")
worldmap_addDesc("steel", "it", "Nient'altro che acciaio", "UFO")
worldmap_addDesc("steel", "pl", "Nic, tylko stal", "UFO")
worldmap_addDesc("steel", "es", "Nada mas que Acero", "OVNI")
worldmap_addDesc("steel", "nl", "Alleen maar staal", "Vliegende schotel")
worldmap_addDesc("steel", "bg", "Само стомана", "НЛО")
worldmap_addDesc("steel", "sv", "Inget annat ??n st??l", "UFO")
worldmap_addDesc("steel", "pt_BR", "Nada Mais Do Que a??o", "UFO")
worldmap_addDesc("steel", "ru", "Ничего кроме стали", "НЛО")

worldmap_addDesc("corridor", "en", "Guarded Corridor", "UFO")
worldmap_addDesc("corridor", "cs", "P????sn?? st??e??en?? chodba", "Ztroskotan?? UFO")
worldmap_addDesc("corridor", "fr", "Couloir gard??", "ovni")
worldmap_addDesc("corridor", "de", "Bewachter Korridor", "UFO")
worldmap_addDesc("corridor", "it", "Corridoio sorvegliato", "UFO")
worldmap_addDesc("corridor", "pl", "Strze??ony korytarz", "UFO")
worldmap_addDesc("corridor", "es", "Pasillo Resguardado", "OVNI")
worldmap_addDesc("corridor", "nl", "Bewaakte gang", "Vliegende schotel")
worldmap_addDesc("corridor", "bg", "Охраняван коридор", "НЛО")
worldmap_addDesc("corridor", "sv", "Bevakad korridor", "UFO")
worldmap_addDesc("corridor", "pt_BR", "Corredor Protegido", "UFO")
worldmap_addDesc("corridor", "ru", "Коридор охраны", "НЛО")

worldmap_addDesc("experiments", "en", "Biological Experiments", "UFO")
worldmap_addDesc("experiments", "cs", "Biologick?? experimenty", "Ztroskotan?? UFO")
worldmap_addDesc("experiments", "fr", "Exp??rience biologique", "ovni")
worldmap_addDesc("experiments", "de", "Biologische Experimente", "UFO")
worldmap_addDesc("experiments", "it", "Esperimenti biologici", "UFO")
worldmap_addDesc("experiments", "pl", "Do??wiadczenia biologiczne", "UFO")
worldmap_addDesc("experiments", "es", "Experimentos Biol??gicos", "OVNI")
worldmap_addDesc("experiments", "nl", "Biologische experimenten", "Vliegende schotel")
worldmap_addDesc("experiments", "bg", "Биологически експерименти", "НЛО")
worldmap_addDesc("experiments", "sv", "Biologiska experiment", "UFO")
worldmap_addDesc("experiments", "pt_BR", "Experi??ncias Biol??gicas", "UFO")
worldmap_addDesc("experiments", "ru", "Биологические эксперименты", "НЛО")

worldmap_addDesc("propulsion", "en", "The Real Propulsion", "UFO")
worldmap_addDesc("propulsion", "cs", "Skute??n?? pohon", "Ztroskotan?? UFO")
worldmap_addDesc("propulsion", "fr", "La vraie propulsion", "ovni")
worldmap_addDesc("propulsion", "de", "Der echte Antrieb", "UFO")
worldmap_addDesc("propulsion", "it", "Il vero propulsore", "UFO")
worldmap_addDesc("propulsion", "pl", "Prawdziwy nap??d", "UFO")
worldmap_addDesc("propulsion", "es", "La Propulsi??n Real", "OVNI")
worldmap_addDesc("propulsion", "nl", "De echte aandrijving", "Vliegende schotel")
worldmap_addDesc("propulsion", "bg", "Истинска тяга", "НЛО")
worldmap_addDesc("propulsion", "sv", "Den riktiga drivkraften", "UFO")
worldmap_addDesc("propulsion", "pt_BR", "A Propuls??o Real", "UFO")
worldmap_addDesc("propulsion", "ru", "Сила инстинкта", "НЛО")

worldmap_addDesc("aztec", "en", "Aztec Art Hall", "Treasure Cave")
worldmap_addDesc("aztec", "cs", "S??l azt??ck??ho um??n??", "Jeskyn?? poklad??")
worldmap_addDesc("aztec", "fr", "La salle d'art Azt??que", "La grotte au tr??sor")
worldmap_addDesc("aztec", "de", "Azteken Kunstaustellung", "Schatzh??hle")
worldmap_addDesc("aztec", "it", "Museo d'arte azteca", "La grotta del tesoro")
worldmap_addDesc("aztec", "pl", "Wystawa sztuki azteckiej", "Grota skarb??w")
worldmap_addDesc("aztec", "es", "Sal??n de Arte Azteca", "Caverna del Tesoro")
worldmap_addDesc("aztec", "nl", "Azteekse kunstverzameling", "De grot met de schat")
worldmap_addDesc("aztec", "bg", "Ацтекско изкуство", "Пещерата със съкровищата")
worldmap_addDesc("aztec", "sv", "Aztekernas konsthall", "Skattgrottan")
worldmap_addDesc("aztec", "pt_BR", "Sal??o de Arte Azteca", "A Caverna do Tesouro")
worldmap_addDesc("aztec", "ru", "Азтекное искусство", "Пещера сокровищ")

worldmap_addDesc("gems", "en", "Shiny Cave-in", "Treasure Cave")
worldmap_addDesc("gems", "cs", "Bl??skav?? z??val", "Jeskyn?? poklad??")
worldmap_addDesc("gems", "fr", "La grotte lumineuse", "La grotte au tr??sor")
worldmap_addDesc("gems", "de", "Gl??nzender Einsturz", "Schatzh??hle")
worldmap_addDesc("gems", "it", "Immersi nello splendore", "La grotta del tesoro")
worldmap_addDesc("gems", "pl", "L??ni??ca jaskinia", "Grota skarb??w")
worldmap_addDesc("gems", "es", "Gruta Luminosa", "Caverna del Tesoro")
worldmap_addDesc("gems", "nl", "Schitterend ingestort", "De grot met de schat")
worldmap_addDesc("gems", "bg", "Блестяща пещера", "Пещерата със съкровищата")
worldmap_addDesc("gems", "sv", "Skimrande gruvras", "Skattgrottan")
worldmap_addDesc("gems", "pt_BR", "Caverna Luminosa", "A Caverna do Tesouro")
worldmap_addDesc("gems", "ru", "Блестящая пещера", "Пещера сокровищ")

worldmap_addDesc("chest", "en", "Giant???s Chest", "Treasure Cave")
worldmap_addDesc("chest", "cs", "Truhli??ka obra Kolod??je", "Jeskyn?? poklad??")
worldmap_addDesc("chest", "fr", "Le coffre g??ant", "La grotte au tr??sor")
worldmap_addDesc("chest", "de", "Die Truhe des Giganten", "Schatzh??hle")
worldmap_addDesc("chest", "it", "Lo scrigno del gigante", "La grotta del tesoro")
worldmap_addDesc("chest", "pl", "Kufer olbrzyma", "Grota skarb??w")
worldmap_addDesc("chest", "es", "El Pecho del Gigante", "Caverna del Tesoro")
worldmap_addDesc("chest", "nl", "De gigantische schatkist", "De grot met de schat")
worldmap_addDesc("chest", "bg", "Сандъка на гиганта", "Пещерата със съкровищата")
worldmap_addDesc("chest", "sv", "J??ttens kista", "Skattgrottan")
worldmap_addDesc("chest", "pt_BR", "O Cofre do Gigante", "A Caverna do Tesouro")
worldmap_addDesc("chest", "ru", "Сундук гиганта", "Пещера сокровищ")

worldmap_addDesc("alibaba", "en", "The Hall of Ali-baba", "Treasure Cave")
worldmap_addDesc("alibaba", "cs", "Alibab??v s??l", "Jeskyn?? poklad??")
worldmap_addDesc("alibaba", "fr", "La caverne d'Ali Baba", "La grotte au tr??sor")
worldmap_addDesc("alibaba", "de", "Die Halle von Ali Baba", "Schatzh??hle")
worldmap_addDesc("alibaba", "it", "La camera di Ali-baba", "La grotta del tesoro")
worldmap_addDesc("alibaba", "pl", "Komnata Ali-Baby", "Grota skarb??w")
worldmap_addDesc("alibaba", "es", "El Sal??n de Ali Baba", "Caverna del Tesoro")
worldmap_addDesc("alibaba", "nl", "De hal van Ali-Baba", "De grot met de schat")
worldmap_addDesc("alibaba", "bg", "Залата на Али Баба", "Пещерата със съкровищата")
worldmap_addDesc("alibaba", "sv", "Alibabas grotta", "Skattgrottan")
worldmap_addDesc("alibaba", "pt_BR", "O Sal??o de Ali-baba", "A Caverna do Tesouro")
worldmap_addDesc("alibaba", "ru", "Золото Али Бабы", "Пещера сокровищ")

worldmap_addDesc("cave", "en", "The Deepest Cave", "Treasure Cave")
worldmap_addDesc("cave", "cs", "Nejhlub???? jeskyn??", "Jeskyn?? poklad??")
worldmap_addDesc("cave", "fr", "La cave la plus profonde", "La grotte au tr??sor")
worldmap_addDesc("cave", "de", "Die tiefste H??hle", "Schatzh??hle")
worldmap_addDesc("cave", "it", "La pi?? profonda", "La grotta del tesoro")
worldmap_addDesc("cave", "pl", "Najg????bsza jaskinia", "Grota Skarb??w")
worldmap_addDesc("cave", "es", "La Caverna mas Profunda", "Caverna del Tesoro")
worldmap_addDesc("cave", "nl", "De diepste grot", "De grot met de schat")
worldmap_addDesc("cave", "bg", "Най-дълбоката пещера", "Пещерата със съкровищата")
worldmap_addDesc("cave", "sv", "Den djupaste grottan", "Skattgrottan")
worldmap_addDesc("cave", "pt_BR", "A Caverna mais Profunda", "A Caverna do Tesouro")
worldmap_addDesc("cave", "ru", "Углубляться в пещеру", "Пещера сокровищ")

worldmap_addDesc("grail", "en", "What Would King Arthur Say?", "Treasure Cave")
worldmap_addDesc("grail", "cs", "Artu?? by se divil", "Jeskyn?? poklad??")
worldmap_addDesc("grail", "fr", "Qu'aurait dit le roi Arthur ?", "La grotte au tr??sor")
worldmap_addDesc("grail", "de", "Was w??rde K??nig Arthur sagen?", "Schatzh??hle")
worldmap_addDesc("grail", "it", "Cosa direbbe Re Art???", "La grotta del tesoro")
worldmap_addDesc("grail", "pl", "Co by powiedzia?? Kr??l Artur?", "Grota skarb??w")
worldmap_addDesc("grail", "es", "??Qu?? Dir??a el Rey Arturo?", "Caverna del Tesoro")
worldmap_addDesc("grail", "nl", "Wat zou Koning Arthur ervan zeggen?", "De grot met de schat")
worldmap_addDesc("grail", "bg", "Какво ли би казал крал Артур?", "Пещерата със съкровищата")
worldmap_addDesc("grail", "sv", "Vad skulle kung Arthur ha sagt?", "Skattgruvan")
worldmap_addDesc("grail", "pt_BR", "O que diria Rei Arthur?", "A Caverna do Tesouro")
worldmap_addDesc("grail", "ru", "Какого слово короля Артура?", "Пещера сокровищ")

worldmap_addDesc("tetris", "en", "TETRIS", "Secret Computer")
worldmap_addDesc("tetris", "cs", "TETRIS", "Tajn?? po????ta??")
worldmap_addDesc("tetris", "fr", "TETRIS", "l'ordinateur secret")
worldmap_addDesc("tetris", "de", "TETRIS", "Geheimer Rechner")
worldmap_addDesc("tetris", "it", "TETRIS", "Il computer segreto")
worldmap_addDesc("tetris", "pl", "TETRIS", "Tajemniczy komputer")
worldmap_addDesc("tetris", "es", "TETRIS", "Computador Secreto")
worldmap_addDesc("tetris", "nl", "TETRIS", "Geheime computer")
worldmap_addDesc("tetris", "bg", "ТЕТРИС", "Тайният компютър")
worldmap_addDesc("tetris", "sv", "TETRIS", "Hemlig dator")
worldmap_addDesc("tetris", "pt_BR", "TETRIS", "Computador Secreto")
worldmap_addDesc("tetris", "ru", "ТЕТРИС", "Секреты компьютера")

worldmap_addDesc("emulator", "en", "Emulator", "Secret Computer")
worldmap_addDesc("emulator", "cs", "Emul??tor", "Tajn?? po????ta??")
worldmap_addDesc("emulator", "fr", "Emulateur", "l'ordinateur secret")
worldmap_addDesc("emulator", "de", "Emulator", "Geheimer Rechner")
worldmap_addDesc("emulator", "it", "Emulatore", "Il computer segreto")
worldmap_addDesc("emulator", "pl", "Emulator", "Tajemniczy komputer")
worldmap_addDesc("emulator", "es", "Emulador", "Computador Secreto")
worldmap_addDesc("emulator", "nl", "Emulator", "Geheime computer")
worldmap_addDesc("emulator", "bg", "Енулатор", "Тайният компютър")
worldmap_addDesc("emulator", "sv", "Emulator", "Hemlig dator")
worldmap_addDesc("emulator", "pt_BR", "Emulador", "Computador Secreto")
worldmap_addDesc("emulator", "ru", "Эмулятор", "Секреты компьютера")

worldmap_addDesc("warcraft", "en", "Garden of War", "Secret Computer")
worldmap_addDesc("warcraft", "cs", "Garden of War", "Tajn?? po????ta??")
worldmap_addDesc("warcraft", "fr", "Jardin de guerre", "l'ordinateur secret")
worldmap_addDesc("warcraft", "de", "Garten des Krieges", "Geheimer Rechner")
worldmap_addDesc("warcraft", "it", "Campo di battaglia", "Il computer segreto")
worldmap_addDesc("warcraft", "pl", "Wojenny ogr??d", "Tajemniczy komputer")
worldmap_addDesc("warcraft", "es", "Jard??n de Guerra", "Computador Secreto")
worldmap_addDesc("warcraft", "nl", "Oorlogstuin", "Geheime computer")
worldmap_addDesc("warcraft", "bg", "Военна градина", "Тайният компютър")
worldmap_addDesc("warcraft", "sv", "Krigstr??dg??rden", "Hemlig dator")
worldmap_addDesc("warcraft", "pt_BR", "Jardim da Guerra", "Computador Secreto")
worldmap_addDesc("warcraft", "ru", "Война на поле", "Секреты компьютера")

worldmap_addDesc("windoze", "en", "Favorites", "Secret Computer")
worldmap_addDesc("windoze", "cs", "Obl??ben?? polo??ky", "Tajn?? po????ta??")
worldmap_addDesc("windoze", "fr", "Favoris", "l'ordinateur secret")
worldmap_addDesc("windoze", "de", "Lesezeichen", "Geheimer Rechner")
worldmap_addDesc("windoze", "it", "Preferiti", "Il computer segreto")
worldmap_addDesc("windoze", "pl", "Ulubie??cy", "Tajemniczy komputer")
worldmap_addDesc("windoze", "es", "Favoritos", "Computador Secreto")
worldmap_addDesc("windoze", "nl", "Leestekens", "Geheime computer")
worldmap_addDesc("windoze", "bg", "Любими", "Тайният компютър")
worldmap_addDesc("windoze", "sv", "Favoriter", "Hemlig dator")
worldmap_addDesc("windoze", "pt_BR", "Favoritos", "Computador Secreto")
worldmap_addDesc("windoze", "ru", "Любимые", "Секреты компьютера")

worldmap_addDesc("hardware", "en", "A Hardware Problem", "Secret Computer")
worldmap_addDesc("hardware", "cs", "Hardwarov?? probl??m", "Tajn?? po????ta??")
worldmap_addDesc("hardware", "fr", "Probl??me mat??riel", "l'ordinateur secret")
worldmap_addDesc("hardware", "de", "Ein Hardwareproblem", "Geheimer Rechner")
worldmap_addDesc("hardware", "it", "Problemi di hardware", "Il computer segreto")
worldmap_addDesc("hardware", "pl", "Problem sprz??towy", "Tajemniczy komputer")
worldmap_addDesc("hardware", "es", "Un Problema de Hardware", "Computador Secreto")
worldmap_addDesc("hardware", "nl", "Een hardwareprobleem", "Geheime computer")
worldmap_addDesc("hardware", "bg", "Хардуерен проблем", "Тайният компютър")
worldmap_addDesc("hardware", "sv", "Ett h??rdvaruproblem", "Hemlig dator")
worldmap_addDesc("hardware", "pt_BR", "Um Problema de Hardware", "Computador Secreto")
worldmap_addDesc("hardware", "ru", "Проблемы с оборудованием", "Секреты компьютера")

worldmap_addDesc("floppy", "en", "Read Only", "Secret Computer")
worldmap_addDesc("floppy", "cs", "Read only", "Tajn?? po????ta??")
worldmap_addDesc("floppy", "fr", "En lecture seul", "l'ordinateur secret")
worldmap_addDesc("floppy", "de", "Nur lesen", "Geheimer Rechner")
worldmap_addDesc("floppy", "it", "Sola lettura", "Il computer segreto")
worldmap_addDesc("floppy", "pl", "Tylko do odczytu", "Tajemniczy komputer")
worldmap_addDesc("floppy", "es", "S??lo Lectura", "Computador Secreto")
worldmap_addDesc("floppy", "nl", "Alleen lezen", "Geheime computer")
worldmap_addDesc("floppy", "bg", "Само за четене", "Тайният компютър")
worldmap_addDesc("floppy", "sv", "Ej skrivbar", "Hemlig dator")
worldmap_addDesc("floppy", "pt_BR", "Somente Leitura", "Computador Secreto")
worldmap_addDesc("floppy", "ru", "Только чтение", "Секреты компьютера")

worldmap_addDesc("ending", "en", "At Home", "Fish House")
worldmap_addDesc("ending", "cs", "Doma", "Ryb?? dome??ek")
worldmap_addDesc("ending", "fr", "A la maison", "Maison Poisson")
worldmap_addDesc("ending", "de", "Zu Hause", "Fischhaus")
worldmap_addDesc("ending", "it", "A casa", "La casa dei pesci")
worldmap_addDesc("ending", "pl", "W domu", "Rybi domek")
worldmap_addDesc("ending", "es", "En Casa", "Casa Pez")
worldmap_addDesc("ending", "nl", "Thuis", "Vissenhuis")
worldmap_addDesc("ending", "bg", "У дома", "Дома на рибките")
worldmap_addDesc("ending", "sv", "Hemma", "Fiskhuset")
worldmap_addDesc("ending", "pt_BR", "Em Casa", "Peixaria")
worldmap_addDesc("ending", "ru", "В доме", "Рыбий дом")

worldmap_addDesc("score", "en", "Special Score", "")
worldmap_addDesc("score", "cs", "Special Score", "")
worldmap_addDesc("score", "fr", "Sp??cial Score", "")
worldmap_addDesc("score", "de", "Spezial-Spielstand", "")
worldmap_addDesc("score", "it", "Puntata speciale", "")
worldmap_addDesc("score", "pl", "Special Score", "")
worldmap_addDesc("score", "es", "Puntaje Especial", "")
worldmap_addDesc("score", "nl", "Speciale score", "")
worldmap_addDesc("score", "bg", "Специален резултат", "")
worldmap_addDesc("score", "sv", "Specialpo??ng", "")
worldmap_addDesc("score", "pt_BR", "Pontua????o Especial", "")
worldmap_addDesc("score", "ru", "Специальный результат", "")

worldmap_addDesc("fdto", "en", "FDTO Building", "Branch of New Generation")
worldmap_addDesc("fdto", "cs", "Budova FDTO", "V??tev Nov?? generace")
worldmap_addDesc("fdto", "de", "Haus FDTO", "NG")
worldmap_addDesc("fdto", "pl", "Kwatera FDTO", "NG")
worldmap_addDesc("fdto", "sv", "FDTO h??gkvarter", "Gren av en ny generation")
worldmap_addDesc("fdto", "nl", "Het VDTO gebouw", "Vissenhuis")
worldmap_addDesc("fdto", "bg", "Сградата на ООРД", "NG")
worldmap_addDesc("fdto", "sl", "Zgradba RDA", "NG")
worldmap_addDesc("fdto", "pt_BR", "Casa FDTO?", "NG")
worldmap_addDesc("fdto", "ru", "Здание FDTO", "Новая ветвь в NG")

worldmap_addDesc("hole", "en", "Hard Hole", "Branch of New Generation")
worldmap_addDesc("hole", "cs", "Nep????jemn?? propast", "V??tev Nov?? generace")
worldmap_addDesc("hole", "sv", "Sv??rt h??l", "Gren av en ny generation")
worldmap_addDesc("hole", "nl", "Een diep gat", "Tak van de nieuwe generatie")
worldmap_addDesc("hole", "ru", "Тяжёлая луза", "Новая ветвь в NG")

worldmap_addDesc("hanoi", "en", "Separated", "Branch of New Generation")
worldmap_addDesc("hanoi", "cs", "Odd??leni", "V??tev Nov?? Generace")
worldmap_addDesc("hanoi", "sv", "Separerade", "Gren av en ny generation")
worldmap_addDesc("hanoi", "nl", "Uitelkaar", "Tak van de nieuwe generatie")
worldmap_addDesc("hanoi", "ru", "Отделение", "Новая ветвь в NG")

worldmap_addDesc("rush", "en", "Filled Car Park", "Branch of New Generation")
worldmap_addDesc("rush", "cs", "Zapln??n?? parkovi??t??", "V??tev Nov?? Generace")
worldmap_addDesc("rush", "sv", "Full parkering", "Gren av en ny generation")
worldmap_addDesc("rush", "nl", "Volle parkeerplek", "Tak van de nieuwe generatie")
worldmap_addDesc("rush", "ru", "Полная стоянка", "Новая ветвь в NG")

worldmap_addDesc("nowall", "en", "No Wall at All", "Branch of New Generation")
worldmap_addDesc("nowall", "cs", "V??bec ????dn?? ze??", "V??tev Nov?? Generace")
worldmap_addDesc("nowall", "sv", "Inga v??ggar alls", "Gren av en ny generation")
worldmap_addDesc("nowall", "nl", "Helemaal geen muren", "Tak van de nieuwe generatie")
worldmap_addDesc("nowall", "ru", "Нет стен во всем", "Новая ветвь в NG")

