
local function isWater(x, y)
    -- index -1 is for empty space (water)
    return model_equals(-1, x, y)
end

local function charAt(s, i)
    return string.sub(s, i, i)
end
    
local function moveXY(model, symbols, destX, destY)
    local result = false
    local locX, locY = model:getLoc()
    local w = model:getW()
    local h = model:getH()

    print("TEST: move '"..symbols.."' "..locX..","..locY.." -> "..destX..","..destY)

    --TODO: find undirect path too
    if locX > destX and isWater(locX - 1, locY) then
        game_action_move(charAt(symbols, 3))
    elseif locX < destX and isWater(locX + w, locY) then
        game_action_move(charAt(symbols, 4))
    elseif locY > destY and isWater(locX, locY - 1) then
        game_action_move(charAt(symbols, 1))
    elseif locY < destY and isWater(locX, locY + h) then
        game_action_move(charAt(symbols, 2))
    else
        if locX ~= destX or locY ~= destY then
            error("moveXY - fish cannot move")
        end
        result = true
    end
    return result
end
local function bigMoveXY(x, y)
    return moveXY(big, 'UDLR', x, y)
end
local function smallMoveXY(x, y)
    return moveXY(small, 'udlr', x, y)
end
local function planDelay(delay)
    game_planAction(function(count)
        return count >= delay
    end)
end



-- ---------------------------------------------------------------
game_planAction(function(count)
    addm(0, "help1")
    return true
end)
planDelay(3)
-- line 9
game_planAction(function(count)
    return smallMoveXY(17, 25)
end)
planDelay(3)
planDelay(3)
-- line 49
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    addv(0, "help2")
    return true
end)
game_planAction(function(count)
    return bigMoveXY(18, 21)
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
-- line 63
planDelay(1)
planDelay(27)
-- line 136
planDelay(18)
-- line 171
game_planAction(function(count)
    return game_action_save()
end)
planDelay(6)
-- line 185
game_planAction(function(count)
    return smallMoveXY(9, 25)
end)
game_planAction(function(count)
    addm(0, "help3")
    return true
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return smallMoveXY(7, 17)
end)
planDelay(3)
-- line 231
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(5)
-- line 231
game_planAction(function(count)
    addv(0, "help4")
    return true
end)
planDelay(7)
planDelay(3)
-- line 265
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
planDelay(13)
-- line 301
game_planAction(function(count)
    addm(0, "help5")
    return true
end)
planDelay(7)
planDelay(10)
-- line 337
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(13)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(3)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(13)
-- line 401
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    addm(0, "help6")
    return true
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return smallMoveXY(9, 25)
end)
planDelay(1)
game_planAction(function(count)
    return smallMoveXY(7, 25)
end)
planDelay(6)
-- line 453
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(19)
-- line 499
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(39)
-- line 579
game_planAction(function(count)
    return game_action_restart()
end)
planDelay(11)
game_planAction(function(count)
    addv(0, "help7")
    return true
end)
planDelay(66)
-- line 729
game_planAction(function(count)
    return game_action_load()
end)
planDelay(8)
game_planAction(function(count)
    addv(0, "help8")
    return true
end)
planDelay(7)
planDelay(29)
-- line 781
game_planAction(function(count)
    return bigMoveXY(9, 23)
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return bigMoveXY(7, 30)
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
planDelay(3)
-- line 831
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(3)
game_planAction(function(count)
    addm(0, "help9")
    return true
end)
planDelay(3)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(5)
planDelay(10)
-- line 881
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(26)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(3)
-- line 943
game_planAction(function(count)
    return smallMoveXY(7, 25)
end)
planDelay(3)
game_planAction(function(count)
    addm(0, "help10")
    return true
end)
planDelay(5)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(16)
-- line 1009
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(25)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(44)
-- line 1151
game_planAction(function(count)
    return game_action_restart()
end)
planDelay(12)
game_planAction(function(count)
    addv(0, "help11")
    return true
end)
planDelay(39)
game_planAction(function(count)
    return game_action_load()
end)
planDelay(4)
planDelay(5)
-- line 1277
game_planAction(function(count)
    return bigMoveXY(9, 23)
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return bigMoveXY(7, 30)
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
planDelay(2)
-- line 1325
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(6)
planDelay(3)
game_planAction(function(count)
    addm(0, "help12")
    return true
end)
planDelay(4)
-- line 1359
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(1)
game_planAction(function(count)
    return smallMoveXY(8, 23)
end)
planDelay(1)
game_planAction(function(count)
    return smallMoveXY(8, 17)
end)
planDelay(7)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(8)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(3)
game_planAction(function(count)
    return game_action_move('r')
end)
-- line 1436
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return smallMoveXY(17, 25)
end)
-- line 1469
game_planAction(function(count)
    addm(0, "help13")
    return true
end)
planDelay(7)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(22)
-- line 1531
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(11)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(2)
-- line 1569
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(45)
-- line 1667
game_planAction(function(count)
    return game_action_restart()
end)
planDelay(8)
game_planAction(function(count)
    return game_action_load()
end)
planDelay(4)
game_planAction(function(count)
    addv(0, "help14")
    return true
end)
planDelay(10)
-- line 1717
game_planAction(function(count)
    return smallMoveXY(7, 25)
end)
planDelay(5)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(13)
game_planAction(function(count)
    addm(0, "help15")
    return true
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(7)
-- line 1815
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(5)
planDelay(2)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
planDelay(2)
-- line 1847
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
planDelay(1)
-- line 1857
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
-- line 1895
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(2)
game_planAction(function(count)
    addm(0, "help16")
    return true
end)
planDelay(6)
planDelay(4)
-- line 1923
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(7)
-- line 1955
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(29)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(3)
-- line 2023
game_planAction(function(count)
    return smallMoveXY(4, 27)
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(4)
planDelay(3)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(2)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(6)
planDelay(4)
-- line 2083
game_planAction(function(count)
    return smallMoveXY(10, 30)
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    addm(0, "help17")
    return true
end)
planDelay(11)
planDelay(8)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
planDelay(8)
-- line 2163
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return bigMoveXY(3, 28)
end)
planDelay(5)
planDelay(6)
game_planAction(function(count)
    addm(0, "help18")
    return true
end)
planDelay(4)
-- 2205
game_planAction(function(count)
    return smallMoveXY(7, 29)
end)
game_planAction(function(count)
    return smallMoveXY(7, 25)
end)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(3)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(6)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(6)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(4)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(4)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(5)
-- line 2301
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(5)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(4)
planDelay(3)
-- line 2343
game_planAction(function(count)
    return bigMoveXY(8, 28)
end)
game_planAction(function(count)
    return game_action_move('D')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
planDelay(5)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('U')
end)
game_planAction(function(count)
    return game_action_move('U')
end)
planDelay(11)
planDelay(3)
game_planAction(function(count)
    addm(0, "help19")
    return true
end)
planDelay(4)
-- line 2421
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
game_planAction(function(count)
    return game_action_move('d')
end)
planDelay(8)
-- line 2461
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(2)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return smallMoveXY(6, 22)
end)
game_planAction(function(count)
    return smallMoveXY(6, 28)
end)
planDelay(1)
game_planAction(function(count)
    return smallMoveXY(14, 28)
end)
game_planAction(function(count)
    return game_action_move('u')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return smallMoveXY(17, 22)
end)
planDelay(2)
-- line 2539
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(1)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(9)
game_planAction(function(count)
    addv(0, "help20")
    return true
end)
-- line 2571
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(3)
planDelay(3)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
game_planAction(function(count)
    return game_action_move('R')
end)
planDelay(3)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
planDelay(2)
planDelay(3)
-- line 2617
game_planAction(function(count)
    return smallMoveXY(17, 26)
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(3)
planDelay(3)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
game_planAction(function(count)
    return game_action_move('L')
end)
planDelay(4)
game_planAction(function(count)
    return bigMoveXY(10, 26)
end)
planDelay(4)
planDelay(3)
-- line 2683
game_planAction(function(count)
    return smallMoveXY(18, 26)
end)
planDelay(15)
game_planAction(function(count)
    return game_action_move('u')
end)
planDelay(2)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(1)
game_planAction(function(count)
    addm(0, "help21")
    return true
end)
planDelay(5)
planDelay(4)
-- line 2751
game_planAction(function(count)
    return bigMoveXY(15, 26)
end)
planDelay(4)
game_planAction(function(count)
    return game_action_move('R')
end)
planDelay(5)
planDelay(7)
-- line 2795
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(5)
game_planAction(function(count)
    return game_action_move('l')
end)
planDelay(8)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(2)
game_planAction(function(count)
    return game_action_move('r')
end)
planDelay(3)
game_planAction(function(count)
    addv(0, "help22")
    return true
end)
planDelay(70)
-- line 2981
game_planAction(function(count)
    addm(0, "help23")
    return true
end)
planDelay(114)
