dialog_addDialog("vit-hs-vitejteA", "en", "", "font_statue", "Welcome to the most beautiful city under the sun.")
dialog_addDialog("vit-hs-vitejteA", "cs", "sound/"..codename.."/cs/vit-hs-vitejteA.ogg", "font_statue", "Vítejte v nejkrásnějším městě pod sluncem.")
dialog_addDialog("vit-hs-vitejteA", "fr", "", "font_statue", "Bienvenu dans la plus belle cité éclairée par le soleil.")
dialog_addDialog("vit-hs-vitejteA", "de", "", "font_statue", "Willkommen in der schönsten Stadt unter der Sonne.")
dialog_addDialog("vit-hs-vitejteA", "it", "", "font_statue", "Benvenuti nella più bella città illuminata dal sole.")

dialog_addDialog("vit-hs-vitejteB", "en", "", "font_statue", "Welcome to our city - the city of unlimited opportunities.")
dialog_addDialog("vit-hs-vitejteB", "cs", "sound/"..codename.."/cs/vit-hs-vitejteB.ogg", "font_statue", "Vítejte v našem městě, městě neomezených možností.")
dialog_addDialog("vit-hs-vitejteB", "fr", "", "font_statue", "Bienvenu dans la plus belle cité - la cité de toutes les opportunités.")
dialog_addDialog("vit-hs-vitejteB", "de", "", "font_statue", "Willkommen in unserer Stadt - der Stadt der unbegrenzten Möglichkeiten.")
dialog_addDialog("vit-hs-vitejteB", "it", "", "font_statue", "Benvenuti nella nostra città - la città delle illimitate opportunità.")

dialog_addDialog("vit-hs-vitejteC", "en", "", "font_statue", "On behalf of the citizens of this town I welcome you.")
dialog_addDialog("vit-hs-vitejteC", "cs", "sound/"..codename.."/cs/vit-hs-vitejteC.ogg", "font_statue", "Dovoluji si vás přivítat jménem občanů našeho města.")
dialog_addDialog("vit-hs-vitejteC", "fr", "", "font_statue", "De la part de la moitié des citoyens de cette cité, je vous souhaite la bienvenue.")
dialog_addDialog("vit-hs-vitejteC", "de", "", "font_statue", "Im Namen der Bewohner dieser Stadt heiße ich euch willkommen.")
dialog_addDialog("vit-hs-vitejteC", "de_CH", "", "font_statue", "Im Namen der Bewohner dieser Stadt heiße ich euch willkommen.")
dialog_addDialog("vit-hs-vitejteC", "it", "", "font_statue", "A nome di tutti i cittadini, vi dò il benvenuto.")

dialog_addDialog("vit-hs-vitejteD", "en", "", "font_statue", "Welcome to our city, whose beauty eclipses that of the gods themselves.")
dialog_addDialog("vit-hs-vitejteD", "cs", "sound/"..codename.."/cs/vit-hs-vitejteD.ogg", "font_statue", "Vítejte v našem městě, před jehož krásou by mohli blednout i bohové.")
dialog_addDialog("vit-hs-vitejteD", "fr", "", "font_statue", "Bienvenu dans notre cité, dont la beauté éclipse les dieux eux-mêmes.")
dialog_addDialog("vit-hs-vitejteD", "de", "", "font_statue", "Willkommen in userer Stadt, dessen Schönheit selbst die der Götter übertrifft.")
dialog_addDialog("vit-hs-vitejteD", "it", "", "font_statue", "Benvenuti nella nostra città, la cui bellezza adombra quella degli Dei stessi.")

dialog_addDialog("vit-hs-klid1", "en", "", "font_statue", "Citizens, please remain calm.")
dialog_addDialog("vit-hs-klid1", "cs", "sound/"..codename.."/cs/vit-hs-klid1.ogg", "font_statue", "Občané. Zachovejte klid a rozvahu.")
dialog_addDialog("vit-hs-klid1", "fr", "", "font_statue", "Citoyens, s'il vous plaît restez calmes.")
dialog_addDialog("vit-hs-klid1", "de", "", "font_statue", "Werte Bürger, bitte bewahren sie Ruhe.")
dialog_addDialog("vit-hs-klid1", "it", "", "font_statue", "A tutti i cittadini: siete pregati di mantenere la calma.")

dialog_addDialog("vit-hs-klid2", "en", "", "font_statue", "There is no imminent danger.")
dialog_addDialog("vit-hs-klid2", "cs", "sound/"..codename.."/cs/vit-hs-klid2.ogg", "font_statue", "Nehrozí žádné nebezpečí.")
dialog_addDialog("vit-hs-klid2", "fr", "", "font_statue", "Il n'y a pas de danger imminent.")
dialog_addDialog("vit-hs-klid2", "de", "", "font_statue", "Es gibt keine drohende Gefahr.")
dialog_addDialog("vit-hs-klid2", "it", "", "font_statue", "Non vi è nessun pericolo immediato.")

dialog_addDialog("vit-hs-klid3", "en", "", "font_statue", "The sinking of the northern part of our island is only temporary.")
dialog_addDialog("vit-hs-klid3", "cs", "sound/"..codename.."/cs/vit-hs-klid3.ogg", "font_statue", "Potopení severní části ostrova je jen dočasné.")
dialog_addDialog("vit-hs-klid3", "fr", "", "font_statue", "L'engloutissement de la partie nord de notre île est seulement temporaire.")
dialog_addDialog("vit-hs-klid3", "de", "", "font_statue", "Der Untergang des nördlichen Teils unserer Insel ist nur vorübergehend.")
dialog_addDialog("vit-hs-klid3", "it", "", "font_statue", "L'affondamento della parte settentrionale della nostra isola è un fenomeno puramente temporaneo.")

dialog_addDialog("vit-hs-klid4", "en", "", "font_statue", "We have the situation completely under control.")
dialog_addDialog("vit-hs-klid4", "cs", "sound/"..codename.."/cs/vit-hs-klid4.ogg", "font_statue", "Situaci máme plně pod kontrolou.")
dialog_addDialog("vit-hs-klid4", "fr", "", "font_statue", "Nous contrôlons entièrement la situation.")
dialog_addDialog("vit-hs-klid4", "de", "", "font_statue", "Wir haben die Situation vollständig unter Kontrolle.")
dialog_addDialog("vit-hs-klid4", "it", "", "font_statue", "La situazione si trova pienamente sotto il nostro controllo.")

dialog_addDialog("vit-hs-lod0", "en", "", "font_statue", "The ship from Lemury has now docked at pier #5. This ship continues on to Utopia, Mu and Atlantis.")
dialog_addDialog("vit-hs-lod0", "cs", "sound/"..codename.."/cs/vit-hs-lod0.ogg", "font_statue", "K pátému molu připlula zpožděná loď z Lemurie. Loď dále pokračuje na Utopii, Mu a Atlantidu.")
dialog_addDialog("vit-hs-lod0", "fr", "", "font_statue", "Le navire lémurien a accosté à la jetée #5. Navire à destination de Utopia, Mu et Atlantide.")
dialog_addDialog("vit-hs-lod0", "de", "", "font_statue", "Das Schiff aus Lemurien hat an Landungssteg 5 angelegt. Dieses Schiff fährt weiter nach Utopia, Mu und Atlantis.")
dialog_addDialog("vit-hs-lod0", "it", "", "font_statue", "La nave proveniente dalla Lemuria ha attraccato al molo 5. Il viaggio continuerà successivamente verso Utopia, Mu ed Atlantide.")

dialog_addDialog("vit-hs-pojis0", "en", "", "font_statue", "With First Fishermen Insurance, your house is covered against damage caused by fire, tornadoes, hurricanes, acts of God and dragons` raids. Because fishermen think of everything, choose First Fisherman.")
dialog_addDialog("vit-hs-pojis0", "cs", "sound/"..codename.."/cs/vit-hs-pojis0.ogg", "font_statue", "První rybářská pojišťovna pojistí váš dům proti požárům, větrným smrštím, zřícení nebeské klenby a náletům draků. Rybáři myslí na vše.")
dialog_addDialog("vit-hs-pojis0", "fr", "", "font_statue", "Avec l'assurance Premier Pêcheur, votre maison est couverte contre les dommages dus au feu, les tornades, les ouragans, les actions divines et les raids de dragons. Parce que Pêcheur pense à tout, choisissez Premier Pêcheur.")
dialog_addDialog("vit-hs-pojis0", "de", "", "font_statue", "Mit der Allgemeinen Angler Versicherung ist ihr Haus gegen Feuer, Wirbelstürme, Windhosen, Gotteswerk und Drachenüberfälle versichert. Weil Angler an alles denkt, wählen sie die Allgemeine Angler Versicherung!")
dialog_addDialog("vit-hs-pojis0", "it", "", "font_statue", "Con le Assicurazioni Pescherecce, la vostra casa è coperta contro i danni provocati da incendi, trombe d'aria, uragani, ire divine e incursioni di draghi. Perché i pescatori pensano a tutto. Tu scegli Assicurazioni Pescherecce.")

dialog_addDialog("vit-x-beg", "en", "sound/"..codename.."/en/vit-x-beg.ogg")

dialog_addDialog("vit-x-end", "en", "sound/"..codename.."/en/vit-x-end.ogg")

dialog_addDialog("vit-hs-reklama1", "en", "", "font_statue", "Where are you running?")
dialog_addDialog("vit-hs-reklama1", "cs", "sound/"..codename.."/cs/vit-hs-reklama1.ogg", "font_statue", "Kam běžíš?")
dialog_addDialog("vit-hs-reklama1", "fr", "", "font_statue", "Ou cours-tu ?")
dialog_addDialog("vit-hs-reklama1", "de", "", "font_statue", "Wo läufst Du hin?")
dialog_addDialog("vit-hs-reklama1", "it", "", "font_statue", "Dove corri?")

dialog_addDialog("vit-hs-reklama2", "en", "", "font_white", "To Moon Street. I need to order eight swords.")
dialog_addDialog("vit-hs-reklama2", "cs", "sound/"..codename.."/cs/vit-hs-reklama2.ogg", "font_white", "Do Měsíční ulice, nechám si tam udělat osm mečů.")
dialog_addDialog("vit-hs-reklama2", "fr", "", "font_white", "A la rue Lune. Je dois passer commande de huit épées.")
dialog_addDialog("vit-hs-reklama2", "de", "", "font_white", "Zur Mondstraße. Ich muss acht Schwerter bestellen.")
dialog_addDialog("vit-hs-reklama2", "de_CH", "", "font_white", "Zur Mondstrasse. Ich muss acht Schwerter bestellen.")
dialog_addDialog("vit-hs-reklama2", "it", "", "font_white", "In Contrada della Luna. Devo ordinare otto spade.")

dialog_addDialog("vit-hs-reklama3", "en", "", "font_statue", "Why so many swords?")
dialog_addDialog("vit-hs-reklama3", "cs", "sound/"..codename.."/cs/vit-hs-reklama3.ogg", "font_statue", "A proč tolik mečů?")
dialog_addDialog("vit-hs-reklama3", "fr", "", "font_statue", "Pourquoi tant d'épées ?")
dialog_addDialog("vit-hs-reklama3", "de", "", "font_statue", "Warum so viele Schwerter?")
dialog_addDialog("vit-hs-reklama3", "it", "", "font_statue", "Perché così tante?")

dialog_addDialog("vit-hs-reklama4", "en", "", "font_white", "You haven`t heard?!? For every eight swords you purchase, you get a pair of bronze earrings absolutely FREE!")
dialog_addDialog("vit-hs-reklama4", "cs", "sound/"..codename.."/cs/vit-hs-reklama4.ogg", "font_white", "Ty to ještě nevíš? Ke každým osmi mečům ti tam dají bronzové náušnice zdarma.")
dialog_addDialog("vit-hs-reklama4", "fr", "", "font_white", "Tu n'as pas entendu ?!? Pour chaque huit épées achetées, une paire de boucle d'oreille en bronze est offerte gratuitement.")
dialog_addDialog("vit-hs-reklama4", "de", "", "font_white", "Hast du nicht gehört? Für jedes achte Schwert bekommst du ein paar Bronzeohrringe absolut KOSTENLOS!")
dialog_addDialog("vit-hs-reklama4", "it", "", "font_white", "Non hai sentito?!? Ogni otto spade acquistate, danno un paio di orecchini in regalo!")

dialog_addDialog("vit-hs-reklama5", "en", "", "font_statue", "Wait for me. I`m coming with you!")
dialog_addDialog("vit-hs-reklama5", "cs", "sound/"..codename.."/cs/vit-hs-reklama5.ogg", "font_statue", "Tak počkej na mě, jdu s tebou!")
dialog_addDialog("vit-hs-reklama5", "fr", "", "font_statue", "Attends moi. Je viens avec toi.")
dialog_addDialog("vit-hs-reklama5", "de", "", "font_statue", "Warte auf mich. Ich komme mit!")
dialog_addDialog("vit-hs-reklama5", "it", "", "font_statue", "Aspetta. Vengo anch'io!")

dialog_addDialog("vit-hs-soud0", "en", "", "font_statue", "The City Court kindly invites you to the annual town festival of interrogations and executions. Proper attire required.")
dialog_addDialog("vit-hs-soud0", "cs", "sound/"..codename.."/cs/vit-hs-soud0.ogg", "font_statue", "Městský soud si vás dovoluje pozvat na veselé pásmo výslechů a poprav. Společenský oděv podmínkou.")
dialog_addDialog("vit-hs-soud0", "fr", "", "font_statue", "Le Tribunal de la cité vous invite aimablement au festival annuel d'interrogations et d'exécutions. Tenue correcte exigée.")
dialog_addDialog("vit-hs-soud0", "de", "", "font_statue", "Das Stadtgericht lädt sie zum jährlichen Stadtfest der Verhöre und Hinrichtungen ein. Angemessene Kleidung erforderlich.")
dialog_addDialog("vit-hs-soud0", "it", "", "font_statue", "La Corte Cittadina vi invita cordialmente al festival annuale degli interrogatori e delle esecuzioni. E` richiesto un abbigliamento consono.")

dialog_addDialog("vit-hs-vodovod0", "en", "", "font_statue", "The City Council has decided to build an aqueduct, thereby providing direct water service to each home.")
dialog_addDialog("vit-hs-vodovod0", "cs", "sound/"..codename.."/cs/vit-hs-vodovod0.ogg", "font_statue", "Město se rozhodlo pro vaše pohodlí vybudovat vodovod. Zavedeme každému vodu až do domu.")
dialog_addDialog("vit-hs-vodovod0", "fr", "", "font_statue", "Le Conseil de la cité a décidé de construire un aqueduc pour fournir directement en eau toute les maisons.")
dialog_addDialog("vit-hs-vodovod0", "de", "", "font_statue", "Der Stadtrat hat beschlossen, ein Aquädukt zu bauen, um einen direkten Wasseranschluss für jedes Haus zu bieten.")
dialog_addDialog("vit-hs-vodovod0", "it", "", "font_statue", "Il Consiglio Cittadino ha deliberato la costruzione di un acquedotto, fornendo così un approvvigionamento diretto di acqua ad ogni abitazione.")

dialog_addDialog("vit-hs-dite0", "en", "", "font_statue", "Would the mother of the child who got lost on the grounds of city treasury please come to the front desk to pick up his remains.")
dialog_addDialog("vit-hs-dite0", "cs", "sound/"..codename.."/cs/vit-hs-dite0.ogg", "font_statue", "Prosíme maminku, jejíž dítě se zaběhlo ke střeženému objektu městské pokladny, aby si jeho ostatky vyzvedla na vrátnici.")
dialog_addDialog("vit-hs-dite0", "fr", "", "font_statue", "Est-ce que la maman de l'enfant qui est resté abandonné dans la salle au trésor de la cité peut venir récupérer ce qu'elle a oublié.")
dialog_addDialog("vit-hs-dite0", "de", "", "font_statue", "Die Mutter des Kindes, das sich in der Schatzkammer der Stadt verlaufen hat, möchte bitte zur Rezeption kommen und seine Überreste abholen.")
dialog_addDialog("vit-hs-dite0", "it", "", "font_statue", "La madre del bambino smarritosi nei pressi della tesoreria cittadina è pregata di recarsi al bancone d'entrata e ritirarne i resti.")

dialog_addDialog("vit-hs-demoni0", "en", "", "font_statue", "Citizens, our employees will be stopping by individual homes tomorrow after midnight in order to rid your home of demons and ghosts. We ask that you kindly let them in.")
dialog_addDialog("vit-hs-demoni0", "cs", "sound/"..codename.."/cs/vit-hs-demoni0.ogg", "font_statue", "Občané. Zítra v půlnočních hodinách se k vám dostaví náš pracovník za účelem zaříkávání proti temným duchům a démonům. Umožněte mu prosím přístup do domu.")
dialog_addDialog("vit-hs-demoni0", "fr", "", "font_statue", "Citoyens, nos employés ont été bloqués à l'extérieur hier soir après minuit alors qu'ils combattaient des démons et des fantômes. Nous vous demandons de gentiment les laisser entrer.")
dialog_addDialog("vit-hs-demoni0", "de", "", "font_statue", "Werte Bürger, unsere Angestellten werden morgen nach Mitternacht bei einigen Häusern vorbeisehen, um sie von Dämonen und Geistern zu befreien. Wir bitten höflich sie reinzulassen.")
dialog_addDialog("vit-hs-demoni0", "it", "", "font_statue", "A tutti i cittadini: nostri addetti passeranno domani, dopo mezzanotte, di casa in casa per liberare le vostre abitazioni da fantasmi e demoni. Vi preghiamo di lasciarli cortesemente entrare.")

dialog_addDialog("vit-hs-kacir", "en", "", "font_statue", "Our chief heretic Demikuls will present a lecture this evening in the small auditorium entitled `Do the gods really exist? or Rest assured they cannot harm you!`")
dialog_addDialog("vit-hs-kacir", "cs", "sound/"..codename.."/cs/vit-hs-kacir.ogg", "font_statue", "Dnes večer přednese v malém přednáškovém sále náš přední kacíř Demilukes přednášku na téma: `Existují bohové? aneb buďte v klidu, nic vám nemohou!`")
dialog_addDialog("vit-hs-kacir", "fr", "", "font_statue", "Notre chef hérétique Demikuls lira ce soir dans le petit auditorium 'Les dieux existent-ils ? ou soyez assuré qu'ils ne peuvent vous blesser!'")
dialog_addDialog("vit-hs-kacir", "de", "", "font_statue", "Unser Oberketzer Demikuls wird heute Abend einen Vortrag im kleinen Hörsaal halten mit dem Titel \"Gibt es die Götter wirklich? oder Seien Sie versichert, dass sie ihnen nichts anhaben können\".")
dialog_addDialog("vit-hs-kacir", "it", "", "font_statue", "Il nostro maestro eretico Demikulo presenterà questa sera una lettura nell'auditorium piccolo intitolata: 'Esistono davvero gli dei? o resta inteso che non possono farvi del male!'")

dialog_addDialog("vit-hs-jidelna1", "en", "", "font_statue", "Come visit our seafood restaurant located at the Main Square. Delicious fish specialties and...")
dialog_addDialog("vit-hs-jidelna1", "cs", "sound/"..codename.."/cs/vit-hs-jidelna1.ogg", "font_statue", "Navštivte rybí jídelnu na horním náměstí. Vybrané speciality z mořských...")
dialog_addDialog("vit-hs-jidelna1", "fr", "", "font_statue", "Venez visiter notre restaurant de la mer, dans le jardin principale. Succulentes spécialités de poissons et...")
dialog_addDialog("vit-hs-jidelna1", "de", "", "font_statue", "Besuchen sie unser Meeresrestaurant am Hauptplatz. Delikate Fischspezialitäten und...")
dialog_addDialog("vit-hs-jidelna1", "it", "", "font_statue", "Visitate il nostro ristorante marinaro situato in Piazza Maggiore. Deliziose specialità di pesce e...")

dialog_addDialog("vit-hs-jidelna2", "en", "", "font_statue", "Oh, excuse me.")
dialog_addDialog("vit-hs-jidelna2", "cs", "sound/"..codename.."/cs/vit-hs-jidelna2.ogg", "font_statue", "Och, promiňte.")
dialog_addDialog("vit-hs-jidelna2", "fr", "", "font_statue", "Oh, excuse moi.")
dialog_addDialog("vit-hs-jidelna2", "de", "", "font_statue", "Oh, Verzeihung.")
dialog_addDialog("vit-hs-jidelna2", "it", "", "font_statue", "Deh, perdonatemi.")

dialog_addDialog("vit-m-jakze", "en", "", "font_small", "What?! A fish restaurant?")
dialog_addDialog("vit-m-jakze", "cs", "sound/"..codename.."/cs/vit-m-jakze.ogg", "font_small", "Jakže, rybí jídelnu?")
dialog_addDialog("vit-m-jakze", "fr", "", "font_small", "Quoi ?! Un restaurant de poissons ?")
dialog_addDialog("vit-m-jakze", "de", "", "font_small", "Was?! Ein Fischrestaurant?")
dialog_addDialog("vit-m-jakze", "it", "", "font_small", "Cosa?! Un ristorante di pesce?")

dialog_addDialog("vit-v-vazne", "en", "", "font_big", "Are you serious?")
dialog_addDialog("vit-v-vazne", "cs", "sound/"..codename.."/cs/vit-v-vazne.ogg", "font_big", "To myslíte vážně?")
dialog_addDialog("vit-v-vazne", "fr", "", "font_big", "Tu es sérieuse ?")
dialog_addDialog("vit-v-vazne", "de", "", "font_big", "Ist das ihr Ernst?")
dialog_addDialog("vit-v-vazne", "it", "", "font_big", "Parli sul serio?")

dialog_addDialog("vit-m-nechutne", "en", "", "font_small", "How disgusting!")
dialog_addDialog("vit-m-nechutne", "cs", "sound/"..codename.."/cs/vit-m-nechutne.ogg", "font_small", "Jak nechutné!")
dialog_addDialog("vit-m-nechutne", "fr", "", "font_small", "C'est écoeurant !")
dialog_addDialog("vit-m-nechutne", "de", "", "font_small", "Wie abscheulich!")
dialog_addDialog("vit-m-nechutne", "it", "", "font_small", "Che orrore!")

dialog_addDialog("vit-v-nevsimla", "en", "", "font_big", "That sculpture obviously hasn`t noticed that the city sank a long time ago.")
dialog_addDialog("vit-v-nevsimla", "cs", "sound/"..codename.."/cs/vit-v-nevsimla.ogg", "font_big", "Ta socha si asi nevšimla, že se tohle město dávno potopilo.")
dialog_addDialog("vit-v-nevsimla", "fr", "", "font_big", "Cette statue n'a visiblement pas noté que la cité a sombré il y a longtemps.")
dialog_addDialog("vit-v-nevsimla", "de", "", "font_big", "Diese Skulptur hat offensichtlich nicht mitbekommen, dass die Stadt längst untergegangen ist.")
dialog_addDialog("vit-v-nevsimla", "it", "", "font_big", "Quella scultura non si è evidentemente accorta che la città è sprofondata già da molto tempo.")

dialog_addDialog("vit-v-automat", "en", "", "font_big", "It`s probably some kind of automaton. It still thinks that the city is alive.")
dialog_addDialog("vit-v-automat", "cs", "sound/"..codename.."/cs/vit-v-automat.ogg", "font_big", "Je to asi nějakej automat, pořád si myslí, že město žije.")
dialog_addDialog("vit-v-automat", "fr", "", "font_big", "C'est probablement un automate. Il pense encore que la cité vit.")
dialog_addDialog("vit-v-automat", "de", "", "font_big", "Der ist wahrscheinlich so eine Art Automat. Er glaubt noch, dass die Stadt lebt.")
dialog_addDialog("vit-v-automat", "it", "", "font_big", "Probabilmente è un qualche tipo di automa. Pensa ancora che la città sia viva.")

dialog_addDialog("vit-m-nebo", "en", "", "font_small", "Or it just can`t face the truth.")
dialog_addDialog("vit-m-nebo", "cs", "sound/"..codename.."/cs/vit-m-nebo.ogg", "font_small", "Nebo si to zkrátka nechce připustit.")
dialog_addDialog("vit-m-nebo", "fr", "", "font_small", "Ou il ne peut affronté la réalité.")
dialog_addDialog("vit-m-nebo", "de", "", "font_small", "Oder er kann einfach die Wahrheit nicht vertragen.")
dialog_addDialog("vit-m-nebo", "it", "", "font_small", "O forse non riesce semplicemente ad affrontare la raltà.")

dialog_addDialog("vit-m-hlava", "en", "", "font_small", "I`m getting a headache from that head.")
dialog_addDialog("vit-m-hlava", "cs", "sound/"..codename.."/cs/vit-m-hlava.ogg", "font_small", "Už mě z té hlavy bolí hlava.")
dialog_addDialog("vit-m-hlava", "fr", "", "font_small", "Je vais avoir une migraine.")
dialog_addDialog("vit-m-hlava", "de", "", "font_small", "Von diesem Kopf kriege ich Kopfschmerzen.")
dialog_addDialog("vit-m-hlava", "it", "", "font_small", "Quella testa mi fa venire il mal di testa.")

dialog_addDialog("vit-v-hlava", "en", "", "font_big", "That head is giving me a headache.")
dialog_addDialog("vit-v-hlava", "cs", "sound/"..codename.."/cs/vit-v-hlava.ogg", "font_big", "Už mě z té hlavy bolí hlava.")
dialog_addDialog("vit-v-hlava", "fr", "", "font_big", "Cette tête m'a donné la migraine.")
dialog_addDialog("vit-v-hlava", "de", "", "font_big", "Dieser Kopf macht mir Kopfschmerzen.")
dialog_addDialog("vit-v-hlava", "it", "", "font_big", "Quel testone mi fa venire il mal di testa.")

dialog_addDialog("vit-m-nezkusime", "en", "", "font_small", "Let`s try to shut that head up somehow.")
dialog_addDialog("vit-m-nezkusime", "cs", "sound/"..codename.."/cs/vit-m-nezkusime.ogg", "font_small", "Nezkusíme tu hlavu nějak umlčet?")
dialog_addDialog("vit-m-nezkusime", "fr", "", "font_small", "Essayons de faire taire cette tête par tout les moyens.")
dialog_addDialog("vit-m-nezkusime", "de", "", "font_small", "Lass uns versuchen, diesen Kopf irgendwie zum Schweigen zu bringen.")
dialog_addDialog("vit-m-nezkusime", "it", "", "font_small", "Proviamo a tappargli la bocca in qualche modo.")

dialog_addDialog("vit-v-proc", "en", "", "font_big", "Why? We`re getting invaluable information about the everyday life of our ancestors.")
dialog_addDialog("vit-v-proc", "cs", "sound/"..codename.."/cs/vit-v-proc.ogg", "font_big", "Proč? Dozvídáme se zde cenné poznatky z všedního života našich předků.")
dialog_addDialog("vit-v-proc", "fr", "", "font_big", "Pourquoi ? Nous récupérons de fabuleuses informations sur la vie quotidienne de nos ancêtres.")
dialog_addDialog("vit-v-proc", "de", "", "font_big", "Warum? Wir bekommen unschätzbare Informationen über das tägliche Leben unserer Vorfahren.")
dialog_addDialog("vit-v-proc", "it", "", "font_big", "Perché? Ci dà informazioni inestimabili sulla vita quotidiana dei nostri predecessori.")

dialog_addDialog("vit-v-krabi", "en", "", "font_big", "If we could get all these crabs up near the head...")
dialog_addDialog("vit-v-krabi", "cs", "sound/"..codename.."/cs/vit-v-krabi.ogg", "font_big", "Kdybychom všechny ty kraby dostali nahoru...")
dialog_addDialog("vit-v-krabi", "fr", "", "font_big", "Si nous pouvions attraper tous ces crabes prêts de la tête...")
dialog_addDialog("vit-v-krabi", "de", "", "font_big", "Wenn wir all diese Krabben oben zum Kopf bekommen würden...")
dialog_addDialog("vit-v-krabi", "it", "", "font_big", "Se riuscissimo a mettere tutti questi granchi là vicino al testone...")

dialog_addDialog("vit-m-tak", "en", "", "font_small", "...then...?")
dialog_addDialog("vit-m-tak", "cs", "sound/"..codename.."/cs/vit-m-tak.ogg", "font_small", "...tak...?")
dialog_addDialog("vit-m-tak", "fr", "", "font_small", "...Et...?")
dialog_addDialog("vit-m-tak", "de", "", "font_small", "...dann...?")
dialog_addDialog("vit-m-tak", "it", "", "font_small", "...allora...?")

dialog_addDialog("vit-v-pockej", "en", "", "font_big", "Wait, I have to think about it for a moment...")
dialog_addDialog("vit-v-pockej", "cs", "sound/"..codename.."/cs/vit-v-pockej.ogg", "font_big", "Počkej, ještě to nemám domyšlené...")
dialog_addDialog("vit-v-pockej", "fr", "", "font_big", "Attends, je dois y réfléchir un moment...")
dialog_addDialog("vit-v-pockej", "de", "", "font_big", "Warte, ich muss darüber einen Moment nachdenken...")
dialog_addDialog("vit-v-pockej", "it", "", "font_big", "Aspetta, devo pensarci ancora un momento...")

dialog_addDialog("vit-m-vecnost", "en", "", "font_small", "Just imagine - that head has been like doing this all these years...")
dialog_addDialog("vit-m-vecnost", "cs", "sound/"..codename.."/cs/vit-m-vecnost.ogg", "font_small", "Představ si, že ta hlava tohle dělá celou věčnost...")
dialog_addDialog("vit-m-vecnost", "fr", "", "font_small", "Pense un peu que cette tête est comme ça depuis tant d'année...")
dialog_addDialog("vit-m-vecnost", "de", "", "font_small", "Stell dir bloß vor, dass dieser Kopf die ganzen Jahre so war...")
dialog_addDialog("vit-m-vecnost", "it", "", "font_small", "Considera che quella testa è rimasta così per tutti questi anni...")

dialog_addDialog("vit-v-noa", "en", "", "font_big", "So what?")
dialog_addDialog("vit-v-noa", "cs", "sound/"..codename.."/cs/vit-v-noa.ogg", "font_big", "No a?")
dialog_addDialog("vit-v-noa", "fr", "", "font_big", "Et alors ?")
dialog_addDialog("vit-v-noa", "de", "", "font_big", "Na und?")
dialog_addDialog("vit-v-noa", "it", "", "font_big", "E allora?")

dialog_addDialog("vit-m-jak", "en", "", "font_small", "Well think about how these poor crabs must feel!")
dialog_addDialog("vit-m-jak", "cs", "sound/"..codename.."/cs/vit-m-jak.ogg", "font_small", "Jak asi musí být těm chudákům krabům!")
dialog_addDialog("vit-m-jak", "fr", "", "font_small", "Et bien réfléchis un peu à ce que ces pauvres crabes doivent ressentir !")
dialog_addDialog("vit-m-jak", "de", "", "font_small", "Na denk mal drüber nach, wie diese armen Krabben sich fühlen müssen!")
dialog_addDialog("vit-m-jak", "it", "", "font_small", "Beh, pensa a questi poveri granchietti, come devono sentirsi!")
