dialog_addDialog("re-v-koraly0", "en", "", "font_big", "I have never seen such violet corals.")
dialog_addDialog("re-v-koraly0", "cs", "sound/"..codename.."/cs/re-v-koraly0.ogg", "font_big", "Tak fialové korály jsem ještě neviděl.")
dialog_addDialog("re-v-koraly0", "fr", "", "font_big", "Je n'ai jamais vu ce type de corail violet.")
dialog_addDialog("re-v-koraly0", "de", "", "font_big", "Ich habe noch nie so violette Korallen gesehen.")
dialog_addDialog("re-v-koraly0", "it", "", "font_big", "Non ho mai visto dei coralli così viola.")

dialog_addDialog("re-v-koraly1", "en", "", "font_big", "I don`t like violet corals.")
dialog_addDialog("re-v-koraly1", "cs", "sound/"..codename.."/cs/re-v-koraly1.ogg", "font_big", "Nemám rád fialové korály.")
dialog_addDialog("re-v-koraly1", "fr", "", "font_big", "Je n'aime pas le corail violet.")
dialog_addDialog("re-v-koraly1", "de", "", "font_big", "Ich mag keine violetten Korallen.")
dialog_addDialog("re-v-koraly1", "it", "", "font_big", "Non mi piacciono i coralli viola.")

dialog_addDialog("re-m-libi0", "en", "", "font_small", "I love violet corals...")
dialog_addDialog("re-m-libi0", "cs", "sound/"..codename.."/cs/re-m-libi0.ogg", "font_small", "Líbí se mi fialové korály...")
dialog_addDialog("re-m-libi0", "fr", "", "font_small", "J'aime le corail violet.")
dialog_addDialog("re-m-libi0", "de", "", "font_small", "Ich liebe violette Korallen...")
dialog_addDialog("re-m-libi0", "it", "", "font_small", "Io adoro i coralli viola...")

dialog_addDialog("re-m-libi1", "en", "", "font_small", "They look nice to me.")
dialog_addDialog("re-m-libi1", "cs", "sound/"..codename.."/cs/re-m-libi1.ogg", "font_small", "Mně se celkem líbí.")
dialog_addDialog("re-m-libi1", "fr", "", "font_small", "Il me va bien.")
dialog_addDialog("re-m-libi1", "de", "", "font_small", "Die gefallen mir.")
dialog_addDialog("re-m-libi1", "it", "", "font_small", "Secondo me sono piacevoli.")

dialog_addDialog("re-m-libi2", "en", "", "font_small", "I hope there will be even more interesting corals in the levels to come.")
dialog_addDialog("re-m-libi2", "cs", "sound/"..codename.."/cs/re-m-libi2.ogg", "font_small", "Doufám, že v dalších místnostech budou ještě zajímavější korály.")
dialog_addDialog("re-m-libi2", "fr", "", "font_small", "J'espère qu'il y aura du corail plus intéressant dans les prochains niveaux.")
dialog_addDialog("re-m-libi2", "de", "", "font_small", "Ich hoffe, in den nächsten Ebenen werden noch interessantere Korallen sein.")
dialog_addDialog("re-m-libi2", "it", "", "font_small", "Spero che ci siano coralli ancora più interessanti nei livelli a venire.")

dialog_addDialog("re-v-pokoj", "en", "", "font_big", "God forbid.")
dialog_addDialog("re-v-pokoj", "cs", "sound/"..codename.."/cs/re-v-pokoj.ogg", "font_big", "Dej pokoj.")
dialog_addDialog("re-v-pokoj", "fr", "", "font_big", "Dieu soit loué.")
dialog_addDialog("re-v-pokoj", "de", "", "font_big", "Bitte nicht.")
dialog_addDialog("re-v-pokoj", "it", "", "font_big", "Dio ce ne scampi.")

dialog_addDialog("re-v-ocel", "en", "", "font_big", "We will have to lift this steel...")
dialog_addDialog("re-v-ocel", "cs", "sound/"..codename.."/cs/re-v-ocel.ogg", "font_big", "Tu ocel budeme muset asi zvednout...")
dialog_addDialog("re-v-ocel", "fr", "", "font_big", "Nous devons soulever cet acier...")
dialog_addDialog("re-v-ocel", "de", "", "font_big", "Wir müssen das Stahlteil anheben...")
dialog_addDialog("re-v-ocel", "it", "", "font_big", "Dovremo sollevare questo pezzo di ferro...")

dialog_addDialog("re-m-ahoj", "en", "", "font_small", "Hi, crab!")
dialog_addDialog("re-m-ahoj", "cs", "sound/"..codename.."/cs/re-m-ahoj.ogg", "font_small", "Ahoj, krabe!")
dialog_addDialog("re-m-ahoj", "fr", "", "font_small", "Salut, le crabe!")
dialog_addDialog("re-m-ahoj", "de", "", "font_small", "Hallo Krabbe!")
dialog_addDialog("re-m-ahoj", "it", "", "font_small", "Ciao, granchio!")

dialog_addDialog("re-m-rozveselit", "en", "", "font_small", "Won`t we try to cheer that crab up a little?")
dialog_addDialog("re-m-rozveselit", "cs", "sound/"..codename.."/cs/re-m-rozveselit.ogg", "font_small", "Nezkusíme toho kraba trochu rozveselit?")
dialog_addDialog("re-m-rozveselit", "fr", "", "font_small", "N'allons-nous pas remonter le moral de ce crabe un petit peu ?")
dialog_addDialog("re-m-rozveselit", "de", "", "font_small", "Wollen wir versuchen, die Krabbe ein bisschen aufzumuntern?")
dialog_addDialog("re-m-rozveselit", "it", "", "font_small", "Perché non tiriamo un po' sù il morale a quel granchio?")

dialog_addDialog("re-v-nevsimej", "en", "", "font_big", "Ignore it.")
dialog_addDialog("re-v-nevsimej", "cs", "sound/"..codename.."/cs/re-v-nevsimej.ogg", "font_big", "Nevšímej si ho.")
dialog_addDialog("re-v-nevsimej", "fr", "", "font_big", "Ignore le.")
dialog_addDialog("re-v-nevsimej", "de", "", "font_big", "Ignoriere sie.")
dialog_addDialog("re-v-nevsimej", "it", "", "font_big", "Ignoralo.")

dialog_addDialog("re-v-nech", "en", "", "font_big", "Leave that crab alone.")
dialog_addDialog("re-v-nech", "cs", "sound/"..codename.."/cs/re-v-nech.ogg", "font_big", "Nech toho kraba na pokoji.")
dialog_addDialog("re-v-nech", "fr", "", "font_big", "Laisse ce crabe tranquille.")
dialog_addDialog("re-v-nech", "de", "", "font_big", "Lass die Krabbe in Ruhe.")
dialog_addDialog("re-v-nech", "it", "", "font_big", "Lascia quel granchio da solo.")

dialog_addDialog("re-v-nervozni", "en", "", "font_big", "Can`t you see how nervous it is?")
dialog_addDialog("re-v-nervozni", "cs", "sound/"..codename.."/cs/re-v-nervozni.ogg", "font_big", "Nevidíš, jak je nervózní?")
dialog_addDialog("re-v-nervozni", "fr", "", "font_big", "Ne peux-tu pas voir comme il est nerveux ?")
dialog_addDialog("re-v-nervozni", "de", "", "font_big", "Siehst du nicht wie nervös sie ist?")
dialog_addDialog("re-v-nervozni", "it", "", "font_big", "Non vedi quanto è già nervoso?")

dialog_addDialog("re-v-obejit", "en", "", "font_big", "Try to do without that nervous crab.")
dialog_addDialog("re-v-obejit", "cs", "sound/"..codename.."/cs/re-v-obejit.ogg", "font_big", "Zkusme se raději obejít bez toho nervózního kraba.")
dialog_addDialog("re-v-obejit", "fr", "", "font_big", "Essaie de te passer de ce crabe nerveux.")
dialog_addDialog("re-v-obejit", "de", "", "font_big", "Versuch es ohne diese nervöse Krabbe.")
dialog_addDialog("re-v-obejit", "it", "", "font_big", "Prova a non pensare al granchio.")

dialog_addDialog("re-m-uzitecny0", "en", "", "font_small", "That crab could be useful.")
dialog_addDialog("re-m-uzitecny0", "cs", "sound/"..codename.."/cs/re-m-uzitecny0.ogg", "font_small", "Ten krab by mohl být užitečný.")
dialog_addDialog("re-m-uzitecny0", "fr", "", "font_small", "Ce crabe pourrait être utile.")
dialog_addDialog("re-m-uzitecny0", "de", "", "font_small", "Diese Krabbe könnte nützlich sein.")
dialog_addDialog("re-m-uzitecny0", "it", "", "font_small", "Quel granchio potrebbe essere utile.")

dialog_addDialog("re-m-uzitecny1", "en", "", "font_small", "This crab will surely help us to solve it.")
dialog_addDialog("re-m-uzitecny1", "cs", "sound/"..codename.."/cs/re-m-uzitecny1.ogg", "font_small", "S pomocí toho kraba to jistě vyřešíme.")
dialog_addDialog("re-m-uzitecny1", "fr", "", "font_small", "Ce crabe peut sûrement nous aider à trouver la solution.")
dialog_addDialog("re-m-uzitecny1", "de", "", "font_small", "Diese Krabbe wird uns sicher helfen, hier rauszukommen.")
dialog_addDialog("re-m-uzitecny1", "it", "", "font_small", "Questo granchio ci aiuterà di sicuro nella soluzione.")

dialog_addDialog("re-k-budi", "en", "", "font_crab", "Who woke me up?")
dialog_addDialog("re-k-budi", "cs", "sound/"..codename.."/cs/re-k-budi.ogg", "font_crab", "Kdo mě budí?")
dialog_addDialog("re-k-budi", "fr", "", "font_crab", "Qui me réveille ?")
dialog_addDialog("re-k-budi", "de", "", "font_crab", "Wer weckt mich auf?")
dialog_addDialog("re-k-budi", "it", "", "font_crab", "Chi mi desta?")

dialog_addDialog("re-k-spim", "en", "", "font_crab", "Leave me alone, I am sleeping here!")
dialog_addDialog("re-k-spim", "cs", "sound/"..codename.."/cs/re-k-spim.ogg", "font_crab", "Odejděte, já tu spím!")
dialog_addDialog("re-k-spim", "fr", "", "font_crab", "Laissez moi, je dors ici !")
dialog_addDialog("re-k-spim", "de", "", "font_crab", "Lass mich in Ruhe, ich schlafe hier!")
dialog_addDialog("re-k-spim", "it", "", "font_crab", "Lasciami in pace, stavo dormendo!")

dialog_addDialog("re-k-otravujete", "en", "", "font_crab", "What do you want from me?!?")
dialog_addDialog("re-k-otravujete", "cs", "sound/"..codename.."/cs/re-k-otravujete.ogg", "font_crab", "Co tady otravujete?!?")
dialog_addDialog("re-k-otravujete", "fr", "", "font_crab", "Que voulez-vous de moi ?!?")
dialog_addDialog("re-k-otravujete", "de", "", "font_crab", "Was willst du von mir?!?")
dialog_addDialog("re-k-otravujete", "it", "", "font_crab", "Che cosa vuoi da me?!?")

dialog_addDialog("re-k-nesahej", "en", "", "font_crab", "Don`t touch me!")
dialog_addDialog("re-k-nesahej", "cs", "sound/"..codename.."/cs/re-k-nesahej.ogg", "font_crab", "Nesahej na mě!")
dialog_addDialog("re-k-nesahej", "fr", "", "font_crab", "Ne me touchez pas !")
dialog_addDialog("re-k-nesahej", "de", "", "font_crab", "Fass mich nicht an!")
dialog_addDialog("re-k-nesahej", "it", "", "font_crab", "Non toccarmi!")

dialog_addDialog("re-k-au", "en", "", "font_crab", "Ooops.")
dialog_addDialog("re-k-au", "cs", "sound/"..codename.."/cs/re-k-au.ogg", "font_crab", "Auvajs.")
dialog_addDialog("re-k-au", "fr", "", "font_crab", "Oups.")
dialog_addDialog("re-k-au", "de", "", "font_crab", "Auah!")
dialog_addDialog("re-k-au", "it", "", "font_crab", "Aiut...")


